In [1]:
import pypsa
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import geopandas as gpd
from pypsa.plot import add_legend_lines, add_legend_patches, add_legend_semicircles
import yaml
from pathlib import Path
import pandas as pd
import yaml

Set parameter TokenServer to value "sophia1.hpc.ait.dtu.dk"

**Set Up**

In [2]:
fn = 'resources/Nordics_test/networks/base_s_100__12h_2050.nc'

In [3]:
n= pypsa.Network(fn)

config = yaml.safe_load(Path("config/config.nordics.yaml").read_text())

INFO:pypsa.network.io:New version 1.0.7 available! (Current: 1.0.6)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores, sub_networks

In [4]:
p = Path(fn)  
try:
    if p.exists():
        p.unlink()
        print(f"Deleted {p}")
    else:
        print(f"File not found: {p}")
except Exception as e:
    print(f"Failed to delete {p}: {e}")

Deleted resources/Nordics_test/networks/base_s_100__12h_2050.nc

**Options**

In [5]:
ongrid=False
cluster_cost_reduction=0
cluster_size=1000   
renewables={"solar",'solar-hsat','onwind'}

In [6]:
nodes_with_clusters = n.buses.loc[
    n.buses.index.str[:2].isin(config['countries']) &
    (n.buses['carrier'] == 'AC')
].index.tolist()

In [7]:
nodes_with_clusters

['DE0 0',
 'DE0 1',
 'DE0 10',
 'DE0 11',
 'DE0 12',
 'DE0 13',
 'DE0 14',
 'DE0 15',
 'DE0 16',
 'DE0 17',
 'DE0 18',
 'DE0 19',
 'DE0 2',
 'DE0 20',
 'DE0 21',
 'DE0 22',
 'DE0 23',
 'DE0 24',
 'DE0 25',
 'DE0 26',
 'DE0 27',
 'DE0 28',
 'DE0 29',
 'DE0 3',
 'DE0 30',
 'DE0 31',
 'DE0 32',
 'DE0 33',
 'DE0 34',
 'DE0 35',
 'DE0 36',
 'DE0 37',
 'DE0 38',
 'DE0 39',
 'DE0 4',
 'DE0 40',
 'DE0 5',
 'DE0 6',
 'DE0 7',
 'DE0 8',
 'DE0 9',
 'DK0 0',
 'DK1 0',
 'GB2 0',
 'GB2 1',
 'GB2 10',
 'GB2 11',
 'GB2 12',
 'GB2 13',
 'GB2 14',
 'GB2 15',
 'GB2 16',
 'GB2 17',
 'GB2 18',
 'GB2 19',
 'GB2 2',
 'GB2 20',
 'GB2 21',
 'GB2 22',
 'GB2 23',
 'GB2 24',
 'GB2 25',
 'GB2 3',
 'GB2 4',
 'GB2 5',
 'GB2 6',
 'GB2 7',
 'GB2 8',
 'GB2 9',
 'GB3 0',
 'NL0 0',
 'NL0 1',
 'NL0 2',
 'NL0 3',
 'NL0 4',
 'NL0 5',
 'NL0 6',
 'NL0 7',
 'NL0 8',
 'NO1 0',
 'NO1 1',
 'NO1 2',
 'NO1 3',
 'NO1 4',
 'NO1 5',
 'NO1 6',
 'NO1 7',
 'NO1 8',
 'NO1 9',
 'SE1 0',
 'SE1 1',
 'SE1 10',
 'SE1 2',
 'SE1 3',
 'SE1 4',
 'SE1 5',
 'SE1 6',
 'SE1 7',
 'SE1 8',
 'SE1 9']

**Buses and Generators of the Cluster Addition**

In [11]:
def assign_cluster_generators_and_electricity_buses(n, config, cluster_size, cluster_cost_reduction, renewables):
    
    nodes_renewables_cf = {}                #dictionary of dataframes by node and renewable type, sorting the generators by average capacity factor (descending order)
    clusters_generators={}                      #dictionary of dataframes by node and renewable type, containing the generators assigned to the cluster  

    for node in nodes_with_clusters:
        for renewable in renewables:

            nodes_renewables_cf[(node, renewable)] = pd.DataFrame(
                index=n.generators['p_nom_max'].loc[n.generators.index.astype(str).str.contains(rf"{node}.*{renewable}$")].index,
                columns=["p_max_pu","p_nom_max"]  
            )
            print(nodes_renewables_cf[(node, renewable)])

            clusters_generators[(node, renewable)] = pd.DataFrame()

            #we are considering the highest mean p_min_pu to determine the best generators per renewable available

            nodes_renewables_cf[(node, renewable)] ["p_max_pu"] = n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.astype(str).str.contains(rf"{node}.*{renewable}$")].mean()
            nodes_renewables_cf[(node, renewable)] ["p_nom_max"] = n.generators['p_nom_max'].loc[n.generators.index.astype(str).str.contains(rf"{node}.*{renewable}$")]

            nodes_renewables_cf[(node, renewable)] = nodes_renewables_cf[(node, renewable)].sort_values("p_max_pu", ascending=False)

            print(nodes_renewables_cf[(node, renewable)])

            #print(nodes_renewables_cf[(country, renewable)])

            number_gen=0



            while  nodes_renewables_cf[(node, renewable)].iloc[0:number_gen+1]["p_nom_max"].sum() <= cluster_size:

                if number_gen >= len(nodes_renewables_cf[(node, renewable)]):
                    raise ValueError(f"Not enough {renewable} generators to reach cluster_size.")
                
                number_gen=number_gen+1

            #print(f"{renewable} generators in cluster: {number_gen+1}")

            clusters_generators[(node, renewable)]  = n.generators.loc[nodes_renewables_cf[(node, renewable)].index[0:number_gen+1]]
            remaining_capacity = nodes_renewables_cf[(node, renewable)].iloc[0:number_gen+1]["p_nom_max"].sum() - cluster_size
            #nodes_renewables_cf[(country, renewable)].iloc[number_gen]["p_nom_max"] = remaining_capacity maybe it is better to do this step later

            print(f"Remaining top {renewable} capacity outside the cluster: {remaining_capacity} MW")

            
            clusters_generators[(node, renewable)].loc[clusters_generators[(node, renewable)].index[number_gen], "p_nom_max"] = cluster_size - clusters_generators[(node, renewable)].loc[clusters_generators[(node, renewable)].index[0:number_gen],"p_nom_max"].sum()

            print(f"Capacity of the last {renewable} generator adjusted to fit cluster size: {clusters_generators[(node, renewable)].loc[clusters_generators[(node, renewable)].index[number_gen], 'p_nom_max']} MW")

            print(clusters_generators[(node, renewable)])

            for idx in clusters_generators[(node, renewable)].index:

                ### Electricity bus and generators ###

                if not n.buses.index.str.contains(rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' cluster'}$").any():
        
                    n.add(
                        "Bus",
                        name=clusters_generators[(node, renewable)].loc[idx].bus + " cluster",
                        v_nom=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "v_nom"],
                        x=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "x"],
                        y=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "y"],
                        unit=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "unit"],
                        location=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "location"],
                        country=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "country"],
                        carrier=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "carrier"],
                        control=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "control"],
                        substation_lv=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "substation_lv"],
                        substation_off=n.buses.at[clusters_generators[(node, renewable)].loc[idx].bus, "substation_off"],
                    )

                n.add(
                    "Generator",
                    name=clusters_generators[(node, renewable)].loc[idx].name + " cluster",
                    bus=clusters_generators[(node, renewable)].loc[idx].bus + " cluster",
                    carrier=clusters_generators[(node, renewable)].loc[idx].carrier,
                    p_nom_max=clusters_generators[(node, renewable)].loc[idx].p_nom_max,
                    p_max_pu=clusters_generators[(node, renewable)].loc[idx].p_max_pu,
                    marginal_cost=clusters_generators[(node, renewable)].loc[idx].marginal_cost*(1-cluster_cost_reduction),
                    capital_cost=clusters_generators[(node, renewable)].loc[idx].capital_cost*(1-cluster_cost_reduction),
                    efficiency=clusters_generators[(node, renewable)].loc[idx].efficiency,
                    location=clusters_generators[(node, renewable)].loc[idx].location,
                    unit=clusters_generators[(node, renewable)].loc[idx].unit,
                    p_nom_extendable=True,
                    overwrite=True,)


                
                
                n.generators_t['p_max_pu'][clusters_generators[(node, renewable)].loc[idx].name + " cluster"] = n.generators_t['p_max_pu'][clusters_generators[(node, renewable)].loc[idx].name]


                ### H2 bus ##

                if not n.buses.index.str.contains(rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2 cluster'}$").any():

                    n.add(
                        "Bus",
                        name=clusters_generators[(node, renewable)].loc[idx].bus + " H2 cluster",
                        v_nom=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "v_nom"],
                        x=n.buses.at[rf"{clusters_generators[(node,renewable)].loc[idx].bus + ' H2'}", "x"],
                        y=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "y"],
                        unit=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "unit"],
                        location=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "location"],
                        country=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "country"],
                        carrier=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "carrier"],
                        control=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "control"],
                        substation_lv=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "substation_lv"],
                        substation_off=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' H2'}", "substation_off"],
                    )

                ### methanol bus ###

                if not n.buses.index.str.contains(rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' methanol cluster'}$").any():

                    n.add(
                        "Bus",
                        name=clusters_generators[(node, renewable)].loc[idx].bus + " methanol cluster",
                        v_nom=n.buses.at["EU methanol", "v_nom"],
                        x=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus}", "x"],
                        y=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus }", "y"],
                        unit=n.buses.at["EU methanol", "unit"],
                        location=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus  }", "location"],
                        country=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus }", "country"],
                        carrier=n.buses.at["EU methanol", "carrier"],
                        control=n.buses.at["EU methanol", "control"],
                        substation_lv=n.buses.at["EU methanol", "substation_lv"],
                        substation_off=n.buses.at["EU methanol", "substation_off"],
                    )
                
                ### Batteries bus ###

                if not n.buses.index.str.contains(rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery cluster'}$").any():

                    n.add(
                        "Bus",
                        name=clusters_generators[(node, renewable)].loc[idx].bus + " battery cluster",
                        v_nom=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "v_nom"],
                        x=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "x"],
                        y=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "y"],
                        unit=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "unit"],
                        location=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "location"],
                        country=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "country"],
                        carrier=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "carrier"],
                        control=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "control"],
                        substation_lv=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "substation_lv"],
                        substation_off=n.buses.at[rf"{clusters_generators[(node, renewable)].loc[idx].bus + ' battery'}", "substation_off"],
                    )



                if idx == nodes_renewables_cf[(node, renewable)].iloc[number_gen].name:
                    n.generators.loc[n.generators.index == idx, "p_nom_max"] = nodes_renewables_cf[(node, renewable)].iloc[0:number_gen+1]["p_nom_max"].sum() - cluster_size

                    print(f"Residual capacity of generator {clusters_generators[(node, renewable)].loc[idx].name} is {n.generators.loc[n.generators.index == idx, 'p_nom_max']} MW")
                
                else:


                    n.remove(
                            "Generator",
                            name=clusters_generators[(node, renewable)].loc[idx].name,
                    )



            

    return n

n= assign_cluster_generators_and_electricity_buses(n, config, cluster_size, cluster_cost_reduction, renewables)

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

                   p_max_pu p_nom_max
name
DE0 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 0 0 solar-hsat  0.130178  43706.374841
Remaining top solar-hsat capacity outside the cluster: 42706.3748412665 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 0 0 solar-hsat  DE0 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 0 0 solar-hsat is name
DE0 0 0 solar-hsat    42706.374841
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 0 0 solar      NaN       NaN
DE0 0 1 solar      NaN       NaN
DE0 0 2 solar      NaN       NaN
DE0 0 3 solar      NaN       NaN
DE0 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DE0 0 4 solar  0.110536   3302.066517
DE0 0 3 solar  0.109769  23538.563162
DE0 0 2 solar  0.108729  19745.882746
DE0 0 1 solar  0.107612   3500.112603
DE0 0 0 solar  0.106822    229.969033
Remaining top solar capacity outside the cluster: 2302.0665173861894 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 0 4 solar  DE0 0      PQ       269.082065        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 0 4 solar  269.082065     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DE0 0 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 0 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DE0 0 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 0 4 solar is name
DE0 0 4 solar    2302.066517
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 0 0 onwind      NaN       NaN
DE0 0 1 onwind      NaN       NaN
DE0 0 2 onwind      NaN       NaN
DE0 0 3 onwind      NaN       NaN
DE0 0 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 0 4 onwind  0.217625   267.204664
DE0 0 3 onwind  0.210481  3163.150668
DE0 0 2 onwind  0.203088  5150.491157
DE0 0 1 onwind  0.196350  6657.599905
DE0 0 0 onwind  0.190143  4138.896563
Remaining top onwind capacity outside the cluster: 2430.3553316915018 MW
Capacity of the last onwind generator adjusted to fit cluster size: 732.7953364114742 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 0 4 onwind  DE0 0      PQ        49.462095        0.0              True
DE0 0 3 onwind  DE0 0      PQ       620.885400        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 0 4 onwind   49.462095  267.204664        NaN       0.0  ...
DE0 0 3 onwind  620.885400  732.795336        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 0 4 onwind               1                 0            NaN
DE0 0 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 0 4 onwind              NaN                  1.0                   1.0
DE0 0 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 0 4 onwind    1.0        0.0
DE0 0 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 0 3 onwind is name
DE0 0 3 onwind    2430.355332
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 1 0 solar-hsat       NaN       NaN
DE0 10 0 solar-hsat      NaN       NaN
DE0 11 0 solar-hsat      NaN       NaN
DE0 12 0 solar-hsat      NaN       NaN
DE0 13 0 solar-hsat      NaN       NaN
DE0 14 0 solar-hsat      NaN       NaN
DE0 15 0 solar-hsat      NaN       NaN
DE0 16 0 solar-hsat      NaN       NaN
DE0 17 0 solar-hsat      NaN       NaN
DE0 18 0 solar-hsat      NaN       NaN
DE0 19 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 11 0 solar-hsat  0.143100  12889.860628
DE0 10 0 solar-hsat  0.137848  26995.289788
DE0 1 0 solar-hsat   0.137088  16726.584839
DE0 13 0 solar-hsat  0.136175  26848.995653
DE0 19 0 solar-hsat  0.134802  23758.812928
DE0 18 0 solar-hsat  0.130217  16028.091319
DE0 12 0 solar-hsat  0.125876  18656.499958
DE0 14 0 solar-hsat  0.125871  22458.717709
DE0 16 0 solar-hsat  0.125821  28698.720417
DE0 15 0 solar-hsat  0.124896  20208.792144
DE0 17 0 solar-hsat  0.124404  29486.069605
Remaining top solar-hsat capacity outside the cluster: 11889.860627619768 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 11 0 solar-hsat  DE0 11      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 11 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 11 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 11 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 11 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 11 0 solar-hsat is name
DE0 11 0 solar-hsat    11889.860628
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 1 0 solar       NaN       NaN
DE0 1 1 solar       NaN       NaN
DE0 1 2 solar       NaN       NaN
DE0 1 3 solar       NaN       NaN
DE0 1 4 solar       NaN       NaN
DE0 10 0 solar      NaN       NaN
DE0 10 1 solar      NaN       NaN
DE0 10 2 solar      NaN       NaN
DE0 10 3 solar      NaN       NaN
DE0 10 4 solar      NaN       NaN
DE0 11 0 solar      NaN       NaN
DE0 11 1 solar      NaN       NaN
DE0 11 2 solar      NaN       NaN
DE0 11 3 solar      NaN       NaN
DE0 11 4 solar      NaN       NaN
DE0 12 0 solar      NaN       NaN
DE0 12 1 solar      NaN       NaN
DE0 12 2 solar      NaN       NaN
DE0 12 3 solar      NaN       NaN
DE0 12 4 solar      NaN       NaN
DE0 13 0 solar      NaN       NaN
DE0 13 1 solar      NaN       NaN
DE0 13 2 solar      NaN       NaN
DE0 13 3 solar      NaN       NaN
DE0 13 4 solar      NaN       NaN
DE0 14 0 solar      NaN       NaN
DE0 14 1 solar      NaN       NaN
DE0 14 2 solar      NaN       NaN
DE0 14 3 solar      NaN       NaN
DE0 14 4 solar      NaN       NaN
DE0 15 0 solar      NaN       NaN
DE0 15 1 solar      NaN       NaN
DE0 15 2 solar      NaN       NaN
DE0 15 3 solar      NaN       NaN
DE0 15 4 solar      NaN       NaN
DE0 16 0 solar      NaN       NaN
DE0 16 1 solar      NaN       NaN
DE0 16 2 solar      NaN       NaN
DE0 16 3 solar      NaN       NaN
DE0 16 4 solar      NaN       NaN
DE0 17 0 solar      NaN       NaN
DE0 17 1 solar      NaN       NaN
DE0 17 2 solar      NaN       NaN
DE0 17 3 solar      NaN       NaN
DE0 17 4 solar      NaN       NaN
DE0 18 0 solar      NaN       NaN
DE0 18 1 solar      NaN       NaN
DE0 18 2 solar      NaN       NaN
DE0 18 3 solar      NaN       NaN
DE0 18 4 solar      NaN       NaN
DE0 19 0 solar      NaN       NaN
DE0 19 1 solar      NaN       NaN
DE0 19 2 solar      NaN       NaN
DE0 19 3 solar      NaN       NaN
DE0 19 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 11 4 solar  0.137903      0.506037
DE0 11 3 solar  0.129697    118.699940
DE0 10 2 solar  0.122134   1141.699434
DE0 11 1 solar  0.122082   7348.458721
DE0 13 4 solar  0.119594    492.223815
DE0 11 0 solar  0.117228   7371.678237
DE0 19 4 solar  0.117007    503.672261
DE0 10 1 solar  0.116435  27954.327442
DE0 1 4 solar   0.116314   5167.874596
DE0 13 3 solar  0.116061   8253.361525
DE0 1 3 solar   0.115146   6133.469027
DE0 19 3 solar  0.114123   6723.233998
DE0 13 2 solar  0.113930  17304.606160
DE0 1 2 solar   0.113421   4715.450732
DE0 18 4 solar  0.112864    392.339907
DE0 19 2 solar  0.112696  10036.209384
DE0 1 1 solar   0.111341   1035.183355
DE0 12 4 solar  0.111231    171.724616
DE0 13 1 solar  0.110976   3652.759478
DE0 10 0 solar  0.110834   1982.071978
DE0 18 3 solar  0.110720   4861.028928
DE0 19 1 solar  0.110132   7863.573608
DE0 1 0 solar   0.109099   2204.361495
DE0 16 4 solar  0.109084     39.799526
DE0 13 0 solar  0.109055   1206.727990
DE0 18 2 solar  0.109009   5024.434830
DE0 15 4 solar  0.108760   2460.205602
DE0 19 0 solar  0.108471   2225.443015
DE0 12 3 solar  0.108370   5038.259707
DE0 16 3 solar  0.107871   5353.839977
DE0 14 4 solar  0.107847   6050.895048
DE0 18 1 solar  0.107168   7604.657905
DE0 14 3 solar  0.106972  11975.036381
DE0 15 3 solar  0.106967   6419.313658
DE0 17 4 solar  0.106713   1175.655918
DE0 16 2 solar  0.106623   1580.999665
DE0 12 2 solar  0.105782   6909.592102
DE0 16 1 solar  0.105669  15773.002336
DE0 17 3 solar  0.105503  21166.069491
DE0 15 2 solar  0.105098   7901.275459
DE0 14 2 solar  0.104952   3593.709600
DE0 16 0 solar  0.104864  10291.517442
DE0 18 0 solar  0.104641    569.742883
DE0 12 1 solar  0.104462   8317.909924
DE0 17 2 solar  0.104076   8882.037635
DE0 15 1 solar  0.103612   4087.171694
DE0 14 1 solar  0.103156   2431.462574
DE0 17 1 solar  0.102435   2166.597270
DE0 12 0 solar  0.102281   1040.651300
DE0 14 0 solar  0.102071   1804.305046
DE0 15 0 solar  0.101630   2397.234475
DE0 17 0 solar  0.100626    555.227719
DE0 10 4 solar  0.000000      0.000000
DE0 11 2 solar  0.000000      0.000000
DE0 10 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 260.9054107881302 MW
Capacity of the last solar generator adjusted to fit cluster size: 880.7940233163182 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 11 4 solar  DE0 11      PQ        0.000000        0.0              True
DE0 11 3 solar  DE0 11      PQ        2.723977        0.0              True
DE0 10 2 solar  DE0 10      PQ       29.872419        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 11 4 solar   0.000000    0.506037        NaN       0.0  ...
DE0 11 3 solar   2.723977  118.699940        NaN       0.0  ...
DE0 10 2 solar  29.872419  880.794023        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 11 4 solar               1                 0            NaN
DE0 11 3 solar               1                 0            NaN
DE0 10 2 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 11 4 solar              NaN                  1.0                   1.0
DE0 11 3 solar              NaN                  1.0                   1.0
DE0 10 2 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 11 4 solar    1.0        0.0
DE0 11 3 solar    1.0        0.0
DE0 10 2 solar    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 10 2 solar is name
DE0 10 2 solar    260.905411
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 1 0 onwind       NaN       NaN
DE0 1 1 onwind       NaN       NaN
DE0 1 2 onwind       NaN       NaN
DE0 1 3 onwind       NaN       NaN
DE0 1 4 onwind       NaN       NaN
DE0 10 0 onwind      NaN       NaN
DE0 10 1 onwind      NaN       NaN
DE0 10 2 onwind      NaN       NaN
DE0 10 3 onwind      NaN       NaN
DE0 10 4 onwind      NaN       NaN
DE0 11 0 onwind      NaN       NaN
DE0 11 1 onwind      NaN       NaN
DE0 11 2 onwind      NaN       NaN
DE0 11 3 onwind      NaN       NaN
DE0 11 4 onwind      NaN       NaN
DE0 12 0 onwind      NaN       NaN
DE0 12 1 onwind      NaN       NaN
DE0 12 2 onwind      NaN       NaN
DE0 12 3 onwind      NaN       NaN
DE0 12 4 onwind      NaN       NaN
DE0 13 0 onwind      NaN       NaN
DE0 13 1 onwind      NaN       NaN
DE0 13 2 onwind      NaN       NaN
DE0 13 3 onwind      NaN       NaN
DE0 13 4 onwind      NaN       NaN
DE0 14 0 onwind      NaN       NaN
DE0 14 1 onwind      NaN       NaN
DE0 14 2 onwind      NaN       NaN
DE0 14 3 onwind      NaN       NaN
DE0 14 4 onwind      NaN       NaN
DE0 15 0 onwind      NaN       NaN
DE0 15 1 onwind      NaN       NaN
DE0 15 2 onwind      NaN       NaN
DE0 15 3 onwind      NaN       NaN
DE0 15 4 onwind      NaN       NaN
DE0 16 0 onwind      NaN       NaN
DE0 16 1 onwind      NaN       NaN
DE0 16 2 onwind      NaN       NaN
DE0 16 3 onwind      NaN       NaN
DE0 16 4 onwind      NaN       NaN
DE0 17 0 onwind      NaN       NaN
DE0 17 1 onwind      NaN       NaN
DE0 17 2 onwind      NaN       NaN
DE0 17 3 onwind      NaN       NaN
DE0 17 4 onwind      NaN       NaN
DE0 18 0 onwind      NaN       NaN
DE0 18 1 onwind      NaN       NaN
DE0 18 2 onwind      NaN       NaN
DE0 18 3 onwind      NaN       NaN
DE0 18 4 onwind      NaN       NaN
DE0 19 0 onwind      NaN       NaN
DE0 19 1 onwind      NaN       NaN
DE0 19 2 onwind      NaN       NaN
DE0 19 3 onwind      NaN       NaN
DE0 19 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 19 4 onwind  0.506091    390.361409
DE0 16 4 onwind  0.467779    918.590888
DE0 16 3 onwind  0.428759    176.632288
DE0 19 3 onwind  0.411390    475.170534
DE0 16 2 onwind  0.372320    567.247149
DE0 19 2 onwind  0.361437   2137.128663
DE0 16 1 onwind  0.314337   2633.036872
DE0 19 1 onwind  0.311226   1765.309617
DE0 18 4 onwind  0.290020    437.412268
DE0 19 0 onwind  0.263189   7211.330754
DE0 18 3 onwind  0.262023   1089.999749
DE0 16 0 onwind  0.257319   8627.365577
DE0 17 4 onwind  0.247599   3691.052757
DE0 18 2 onwind  0.241992   1572.573613
DE0 17 3 onwind  0.239818   7081.535508
DE0 14 4 onwind  0.237862   1316.258938
DE0 17 2 onwind  0.228141   1608.503179
DE0 18 1 onwind  0.227705   1395.032396
DE0 14 3 onwind  0.227191   4603.652840
DE0 14 2 onwind  0.214071   2442.756137
DE0 17 1 onwind  0.210847     15.161904
DE0 12 4 onwind  0.202423   2249.109573
DE0 14 1 onwind  0.201629   1477.451872
DE0 17 0 onwind  0.198826     27.933882
DE0 18 0 onwind  0.197658   6223.029002
DE0 14 0 onwind  0.190572    225.991830
DE0 15 4 onwind  0.190484   7006.093229
DE0 12 3 onwind  0.188755   4146.043820
DE0 1 4 onwind   0.184304    458.528777
DE0 15 3 onwind  0.183222   1826.177617
DE0 12 2 onwind  0.174612   2211.043784
DE0 12 1 onwind  0.168063   2401.561548
DE0 15 2 onwind  0.166622   2619.459960
DE0 1 3 onwind   0.164084    911.588042
DE0 1 2 onwind   0.162071   1245.149557
DE0 15 1 onwind  0.160181    775.186603
DE0 13 4 onwind  0.153440   1194.051476
DE0 12 0 onwind  0.152252    848.768875
DE0 15 0 onwind  0.151272   1228.797404
DE0 1 1 onwind   0.145392   1880.651087
DE0 11 4 onwind  0.137082   3495.312247
DE0 10 4 onwind  0.133797    165.729924
DE0 13 3 onwind  0.132740   3843.174861
DE0 1 0 onwind   0.130126    813.297780
DE0 13 2 onwind  0.120612   4432.518612
DE0 13 1 onwind  0.106326    882.280976
DE0 10 3 onwind  0.105948  11983.845342
DE0 11 3 onwind  0.105826     99.704081
DE0 13 0 onwind  0.085311    853.320871
DE0 10 2 onwind  0.076256   6605.968230
DE0 11 2 onwind  0.068589   1345.879657
DE0 11 1 onwind  0.051840   2538.669574
DE0 11 0 onwind  0.019025    959.941774
DE0 10 0 onwind  0.012583   1322.783035
DE0 10 1 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 308.9522969155969 MW
Capacity of the last onwind generator adjusted to fit cluster size: 609.6385909004197 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 19 4 onwind  DE0 19      PQ        28.748866        0.0              True
DE0 16 4 onwind  DE0 16      PQ       299.529889        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 19 4 onwind   28.748866  390.361409        NaN       0.0  ...
DE0 16 4 onwind  299.529889  609.638591        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 19 4 onwind               1                 0            NaN
DE0 16 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 19 4 onwind              NaN                  1.0                   1.0
DE0 16 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 19 4 onwind    1.0        0.0
DE0 16 4 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 16 4 onwind is name
DE0 16 4 onwind    308.952297
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 10 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 10 0 solar-hsat  0.137848  26995.289788
Remaining top solar-hsat capacity outside the cluster: 25995.28978843907 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 10 0 solar-hsat  DE0 10      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 10 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 10 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 10 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 10 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 10 0 solar-hsat is name
DE0 10 0 solar-hsat    25995.289788
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 10 0 solar      NaN       NaN
DE0 10 1 solar      NaN       NaN
DE0 10 2 solar      NaN       NaN
DE0 10 3 solar      NaN       NaN
DE0 10 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 10 2 solar  0.122134    260.905411
DE0 10 1 solar  0.116435  27954.327442
DE0 10 0 solar  0.110834   1982.071978
DE0 10 3 solar  0.000000      0.000000
DE0 10 4 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 27215.23285244789 MW
Capacity of the last solar generator adjusted to fit cluster size: 739.0945892118698 MW
                   bus control type        p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 10 2 solar  DE0 10      PQ         29.872419        0.0              True
DE0 10 1 solar  DE0 10      PQ       1628.511485        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 10 2 solar    29.872419  260.905411        NaN       0.0  ...
DE0 10 1 solar  1628.511485  739.094589        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 10 2 solar               1                 0            NaN
DE0 10 1 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 10 2 solar              NaN                  1.0                   1.0
DE0 10 1 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 10 2 solar    1.0        0.0
DE0 10 1 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 10 1 solar is name
DE0 10 1 solar    27215.232852
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 10 0 onwind      NaN       NaN
DE0 10 1 onwind      NaN       NaN
DE0 10 2 onwind      NaN       NaN
DE0 10 3 onwind      NaN       NaN
DE0 10 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 10 4 onwind  0.133797    165.729924
DE0 10 3 onwind  0.105948  11983.845342
DE0 10 2 onwind  0.076256   6605.968230
DE0 10 0 onwind  0.012583   1322.783035
DE0 10 1 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 11149.575266870452 MW
Capacity of the last onwind generator adjusted to fit cluster size: 834.2700755280814 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 10 4 onwind  DE0 10      PQ         3.226808        0.0              True
DE0 10 3 onwind  DE0 10      PQ       184.762479        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 10 4 onwind    3.226808  165.729924        NaN       0.0  ...
DE0 10 3 onwind  184.762479  834.270076        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 10 4 onwind               1                 0            NaN
DE0 10 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 10 4 onwind              NaN                  1.0                   1.0
DE0 10 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 10 4 onwind    1.0        0.0
DE0 10 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 10 3 onwind is name
DE0 10 3 onwind    11149.575267
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 11 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 11 0 solar-hsat    0.1431  11889.860628
Remaining top solar-hsat capacity outside the cluster: 10889.860627619768 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 11 0 solar-hsat  DE0 11      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 11 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 11 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 11 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 11 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 11 0 solar-hsat is name
DE0 11 0 solar-hsat    10889.860628
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 11 0 solar      NaN       NaN
DE0 11 1 solar      NaN       NaN
DE0 11 2 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 11 1 solar  0.122082  7348.458721
DE0 11 0 solar  0.117228  7371.678237
DE0 11 2 solar  0.000000     0.000000
Remaining top solar capacity outside the cluster: 6348.45872073678 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 11 1 solar  DE0 11      PQ       271.635116        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 11 1 solar  271.635116     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 11 1 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 11 1 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 11 1 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 11 1 solar is name
DE0 11 1 solar    6348.458721
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 11 0 onwind      NaN       NaN
DE0 11 1 onwind      NaN       NaN
DE0 11 2 onwind      NaN       NaN
DE0 11 3 onwind      NaN       NaN
DE0 11 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 11 4 onwind  0.137082  3495.312247
DE0 11 3 onwind  0.105826    99.704081
DE0 11 2 onwind  0.068589  1345.879657
DE0 11 1 onwind  0.051840  2538.669574
DE0 11 0 onwind  0.019025   959.941774
Remaining top onwind capacity outside the cluster: 2495.31224658286 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 11 4 onwind  DE0 11      PQ       98.725566        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 11 4 onwind  98.725566     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 11 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 11 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 11 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 11 4 onwind is name
DE0 11 4 onwind    2495.312247
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 12 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 12 0 solar-hsat  0.125876  18656.499958
Remaining top solar-hsat capacity outside the cluster: 17656.499957699758 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 12 0 solar-hsat  DE0 12      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 12 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 12 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 12 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 12 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 12 0 solar-hsat is name
DE0 12 0 solar-hsat    17656.499958
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 12 0 solar      NaN       NaN
DE0 12 1 solar      NaN       NaN
DE0 12 2 solar      NaN       NaN
DE0 12 3 solar      NaN       NaN
DE0 12 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 12 4 solar  0.111231   171.724616
DE0 12 3 solar  0.108370  5038.259707
DE0 12 2 solar  0.105782  6909.592102
DE0 12 1 solar  0.104462  8317.909924
DE0 12 0 solar  0.102281  1040.651300
Remaining top solar capacity outside the cluster: 4209.984323217395 MW
Capacity of the last solar generator adjusted to fit cluster size: 828.2753837426733 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 12 4 solar  DE0 12      PQ        11.579721        0.0              True
DE0 12 3 solar  DE0 12      PQ       194.708195        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 12 4 solar   11.579721  171.724616        NaN       0.0  ...
DE0 12 3 solar  194.708195  828.275384        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 12 4 solar               1                 0            NaN
DE0 12 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 12 4 solar              NaN                  1.0                   1.0
DE0 12 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 12 4 solar    1.0        0.0
DE0 12 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 12 3 solar is name
DE0 12 3 solar    4209.984323
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 12 0 onwind      NaN       NaN
DE0 12 1 onwind      NaN       NaN
DE0 12 2 onwind      NaN       NaN
DE0 12 3 onwind      NaN       NaN
DE0 12 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 12 4 onwind  0.202423  2249.109573
DE0 12 3 onwind  0.188755  4146.043820
DE0 12 2 onwind  0.174612  2211.043784
DE0 12 1 onwind  0.168063  2401.561548
DE0 12 0 onwind  0.152252   848.768875
Remaining top onwind capacity outside the cluster: 1249.1095729449426 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 12 4 onwind  DE0 12      PQ       289.251614        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 12 4 onwind  289.251614     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 12 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 12 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 12 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 12 4 onwind is name
DE0 12 4 onwind    1249.109573
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 13 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 13 0 solar-hsat  0.136175  26848.995653
Remaining top solar-hsat capacity outside the cluster: 25848.99565336346 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 13 0 solar-hsat  DE0 13      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 13 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 13 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 13 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 13 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 13 0 solar-hsat is name
DE0 13 0 solar-hsat    25848.995653
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 13 0 solar      NaN       NaN
DE0 13 1 solar      NaN       NaN
DE0 13 2 solar      NaN       NaN
DE0 13 3 solar      NaN       NaN
DE0 13 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 13 4 solar  0.119594    492.223815
DE0 13 3 solar  0.116061   8253.361525
DE0 13 2 solar  0.113930  17304.606160
DE0 13 1 solar  0.110976   3652.759478
DE0 13 0 solar  0.109055   1206.727990
Remaining top solar capacity outside the cluster: 7745.585340307383 MW
Capacity of the last solar generator adjusted to fit cluster size: 507.77618475736745 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 13 4 solar  DE0 13      PQ        14.115875        0.0              True
DE0 13 3 solar  DE0 13      PQ       324.788231        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 13 4 solar   14.115875  492.223815        NaN       0.0  ...
DE0 13 3 solar  324.788231  507.776185        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 13 4 solar               1                 0            NaN
DE0 13 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 13 4 solar              NaN                  1.0                   1.0
DE0 13 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 13 4 solar    1.0        0.0
DE0 13 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 13 3 solar is name
DE0 13 3 solar    7745.58534
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 13 0 onwind      NaN       NaN
DE0 13 1 onwind      NaN       NaN
DE0 13 2 onwind      NaN       NaN
DE0 13 3 onwind      NaN       NaN
DE0 13 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 13 4 onwind  0.153440  1194.051476
DE0 13 3 onwind  0.132740  3843.174861
DE0 13 2 onwind  0.120612  4432.518612
DE0 13 1 onwind  0.106326   882.280976
DE0 13 0 onwind  0.085311   853.320871
Remaining top onwind capacity outside the cluster: 194.05147560444811 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 13 4 onwind  DE0 13      PQ       38.661676        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 13 4 onwind  38.661676     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 13 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 13 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 13 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 13 4 onwind is name
DE0 13 4 onwind    194.051476
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 14 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 14 0 solar-hsat  0.125871  22458.717709
Remaining top solar-hsat capacity outside the cluster: 21458.717709037293 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 14 0 solar-hsat  DE0 14      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 14 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 14 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 14 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 14 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 14 0 solar-hsat is name
DE0 14 0 solar-hsat    21458.717709
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 14 0 solar      NaN       NaN
DE0 14 1 solar      NaN       NaN
DE0 14 2 solar      NaN       NaN
DE0 14 3 solar      NaN       NaN
DE0 14 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 14 4 solar  0.107847   6050.895048
DE0 14 3 solar  0.106972  11975.036381
DE0 14 2 solar  0.104952   3593.709600
DE0 14 1 solar  0.103156   2431.462574
DE0 14 0 solar  0.102071   1804.305046
Remaining top solar capacity outside the cluster: 5050.895048118135 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 14 4 solar  DE0 14      PQ       184.765327        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 14 4 solar  184.765327     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 14 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 14 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 14 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 14 4 solar is name
DE0 14 4 solar    5050.895048
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 14 0 onwind      NaN       NaN
DE0 14 1 onwind      NaN       NaN
DE0 14 2 onwind      NaN       NaN
DE0 14 3 onwind      NaN       NaN
DE0 14 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 14 4 onwind  0.237862  1316.258938
DE0 14 3 onwind  0.227191  4603.652840
DE0 14 2 onwind  0.214071  2442.756137
DE0 14 1 onwind  0.201629  1477.451872
DE0 14 0 onwind  0.190572   225.991830
Remaining top onwind capacity outside the cluster: 316.25893766367426 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 14 4 onwind  DE0 14      PQ       104.560767        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 14 4 onwind  104.560767     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 14 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 14 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 14 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 14 4 onwind is name
DE0 14 4 onwind    316.258938
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 15 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 15 0 solar-hsat  0.124896  20208.792144
Remaining top solar-hsat capacity outside the cluster: 19208.792143855266 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 15 0 solar-hsat  DE0 15      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 15 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 15 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 15 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 15 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 15 0 solar-hsat is name
DE0 15 0 solar-hsat    19208.792144
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 15 0 solar      NaN       NaN
DE0 15 1 solar      NaN       NaN
DE0 15 2 solar      NaN       NaN
DE0 15 3 solar      NaN       NaN
DE0 15 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 15 4 solar  0.108760  2460.205602
DE0 15 3 solar  0.106967  6419.313658
DE0 15 2 solar  0.105098  7901.275459
DE0 15 1 solar  0.103612  4087.171694
DE0 15 0 solar  0.101630  2397.234475
Remaining top solar capacity outside the cluster: 1460.2056024336193 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 15 4 solar  DE0 15      PQ       161.344121        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 15 4 solar  161.344121     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 15 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 15 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 15 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 15 4 solar is name
DE0 15 4 solar    1460.205602
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 15 0 onwind      NaN       NaN
DE0 15 1 onwind      NaN       NaN
DE0 15 2 onwind      NaN       NaN
DE0 15 3 onwind      NaN       NaN
DE0 15 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 15 4 onwind  0.190484  7006.093229
DE0 15 3 onwind  0.183222  1826.177617
DE0 15 2 onwind  0.166622  2619.459960
DE0 15 1 onwind  0.160181   775.186603
DE0 15 0 onwind  0.151272  1228.797404
Remaining top onwind capacity outside the cluster: 6006.093229022257 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 15 4 onwind  DE0 15      PQ       351.204152        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 15 4 onwind  351.204152     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 15 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 15 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 15 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 15 4 onwind is name
DE0 15 4 onwind    6006.093229
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 16 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 16 0 solar-hsat  0.125821  28698.720417
Remaining top solar-hsat capacity outside the cluster: 27698.720416819604 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 16 0 solar-hsat  DE0 16      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 16 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 16 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 16 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 16 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 16 0 solar-hsat is name
DE0 16 0 solar-hsat    27698.720417
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 16 0 solar      NaN       NaN
DE0 16 1 solar      NaN       NaN
DE0 16 2 solar      NaN       NaN
DE0 16 3 solar      NaN       NaN
DE0 16 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 16 4 solar  0.109084     39.799526
DE0 16 3 solar  0.107871   5353.839977
DE0 16 2 solar  0.106623   1580.999665
DE0 16 1 solar  0.105669  15773.002336
DE0 16 0 solar  0.104864  10291.517442
Remaining top solar capacity outside the cluster: 4393.639502045975 MW
Capacity of the last solar generator adjusted to fit cluster size: 960.2004744716706 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 16 4 solar  DE0 16      PQ         0.768179        0.0              True
DE0 16 3 solar  DE0 16      PQ       158.986893        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 16 4 solar    0.768179   39.799526        NaN       0.0  ...
DE0 16 3 solar  158.986893  960.200474        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 16 4 solar               1                 0            NaN
DE0 16 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 16 4 solar              NaN                  1.0                   1.0
DE0 16 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 16 4 solar    1.0        0.0
DE0 16 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 16 3 solar is name
DE0 16 3 solar    4393.639502
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 16 0 onwind      NaN       NaN
DE0 16 1 onwind      NaN       NaN
DE0 16 2 onwind      NaN       NaN
DE0 16 3 onwind      NaN       NaN
DE0 16 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 16 4 onwind  0.467779   308.952297
DE0 16 3 onwind  0.428759   176.632288
DE0 16 2 onwind  0.372320   567.247149
DE0 16 1 onwind  0.314337  2633.036872
DE0 16 0 onwind  0.257319  8627.365577
Remaining top onwind capacity outside the cluster: 52.83173434258788 MW
Capacity of the last onwind generator adjusted to fit cluster size: 514.4154149777668 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 16 4 onwind  DE0 16      PQ       299.529889        0.0              True
DE0 16 3 onwind  DE0 16      PQ        39.020677        0.0              True
DE0 16 2 onwind  DE0 16      PQ       217.733606        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 16 4 onwind  299.529889  308.952297        NaN       0.0  ...
DE0 16 3 onwind   39.020677  176.632288        NaN       0.0  ...
DE0 16 2 onwind  217.733606  514.415415        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 16 4 onwind               1                 0            NaN
DE0 16 3 onwind               1                 0            NaN
DE0 16 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 16 4 onwind              NaN                  1.0                   1.0
DE0 16 3 onwind              NaN                  1.0                   1.0
DE0 16 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 16 4 onwind    1.0        0.0
DE0 16 3 onwind    1.0        0.0
DE0 16 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 16 2 onwind is name
DE0 16 2 onwind    52.831734
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 17 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 17 0 solar-hsat  0.124404  29486.069605
Remaining top solar-hsat capacity outside the cluster: 28486.069605085275 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 17 0 solar-hsat  DE0 17      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 17 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 17 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 17 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 17 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 17 0 solar-hsat is name
DE0 17 0 solar-hsat    28486.069605
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 17 0 solar      NaN       NaN
DE0 17 1 solar      NaN       NaN
DE0 17 2 solar      NaN       NaN
DE0 17 3 solar      NaN       NaN
DE0 17 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 17 4 solar  0.106713   1175.655918
DE0 17 3 solar  0.105503  21166.069491
DE0 17 2 solar  0.104076   8882.037635
DE0 17 1 solar  0.102435   2166.597270
DE0 17 0 solar  0.100626    555.227719
Remaining top solar capacity outside the cluster: 175.6559175069192 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 17 4 solar  DE0 17      PQ       32.498351        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 17 4 solar  32.498351     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 17 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 17 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 17 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 17 4 solar is name
DE0 17 4 solar    175.655918
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 17 0 onwind      NaN       NaN
DE0 17 1 onwind      NaN       NaN
DE0 17 2 onwind      NaN       NaN
DE0 17 3 onwind      NaN       NaN
DE0 17 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 17 4 onwind  0.247599  3691.052757
DE0 17 3 onwind  0.239818  7081.535508
DE0 17 2 onwind  0.228141  1608.503179
DE0 17 1 onwind  0.210847    15.161904
DE0 17 0 onwind  0.198826    27.933882
Remaining top onwind capacity outside the cluster: 2691.0527572758397 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 17 4 onwind  DE0 17      PQ       483.991709        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 17 4 onwind  483.991709     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 17 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 17 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 17 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 17 4 onwind is name
DE0 17 4 onwind    2691.052757
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 18 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 18 0 solar-hsat  0.130217  16028.091319
Remaining top solar-hsat capacity outside the cluster: 15028.091318598039 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 18 0 solar-hsat  DE0 18      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 18 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 18 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 18 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 18 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 18 0 solar-hsat is name
DE0 18 0 solar-hsat    15028.091319
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 18 0 solar      NaN       NaN
DE0 18 1 solar      NaN       NaN
DE0 18 2 solar      NaN       NaN
DE0 18 3 solar      NaN       NaN
DE0 18 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 18 4 solar  0.112864   392.339907
DE0 18 3 solar  0.110720  4861.028928
DE0 18 2 solar  0.109009  5024.434830
DE0 18 1 solar  0.107168  7604.657905
DE0 18 0 solar  0.104641   569.742883
Remaining top solar capacity outside the cluster: 4253.36883474674 MW
Capacity of the last solar generator adjusted to fit cluster size: 607.6600927846498 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 18 4 solar  DE0 18      PQ        18.235050        0.0              True
DE0 18 3 solar  DE0 18      PQ       443.030715        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 18 4 solar   18.235050  392.339907        NaN       0.0  ...
DE0 18 3 solar  443.030715  607.660093        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 18 4 solar               1                 0            NaN
DE0 18 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 18 4 solar              NaN                  1.0                   1.0
DE0 18 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 18 4 solar    1.0        0.0
DE0 18 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 18 3 solar is name
DE0 18 3 solar    4253.368835
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 18 0 onwind      NaN       NaN
DE0 18 1 onwind      NaN       NaN
DE0 18 2 onwind      NaN       NaN
DE0 18 3 onwind      NaN       NaN
DE0 18 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 18 4 onwind  0.290020   437.412268
DE0 18 3 onwind  0.262023  1089.999749
DE0 18 2 onwind  0.241992  1572.573613
DE0 18 1 onwind  0.227705  1395.032396
DE0 18 0 onwind  0.197658  6223.029002
Remaining top onwind capacity outside the cluster: 527.4120168361349 MW
Capacity of the last onwind generator adjusted to fit cluster size: 562.5877322579624 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 18 4 onwind  DE0 18      PQ       111.460498        0.0              True
DE0 18 3 onwind  DE0 18      PQ       199.561454        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 18 4 onwind  111.460498  437.412268        NaN       0.0  ...
DE0 18 3 onwind  199.561454  562.587732        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 18 4 onwind               1                 0            NaN
DE0 18 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 18 4 onwind              NaN                  1.0                   1.0
DE0 18 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 18 4 onwind    1.0        0.0
DE0 18 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 18 3 onwind is name
DE0 18 3 onwind    527.412017
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 19 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 19 0 solar-hsat  0.134802  23758.812928
Remaining top solar-hsat capacity outside the cluster: 22758.81292812989 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 19 0 solar-hsat  DE0 19      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 19 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 19 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 19 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 19 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 19 0 solar-hsat is name
DE0 19 0 solar-hsat    22758.812928
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 19 0 solar      NaN       NaN
DE0 19 1 solar      NaN       NaN
DE0 19 2 solar      NaN       NaN
DE0 19 3 solar      NaN       NaN
DE0 19 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 19 4 solar  0.117007    503.672261
DE0 19 3 solar  0.114123   6723.233998
DE0 19 2 solar  0.112696  10036.209384
DE0 19 1 solar  0.110132   7863.573608
DE0 19 0 solar  0.108471   2225.443015
Remaining top solar capacity outside the cluster: 6226.906258498357 MW
Capacity of the last solar generator adjusted to fit cluster size: 496.3277392847619 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 19 4 solar  DE0 19      PQ        14.027563        0.0              True
DE0 19 3 solar  DE0 19      PQ       450.360950        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 19 4 solar   14.027563  503.672261        NaN       0.0  ...
DE0 19 3 solar  450.360950  496.327739        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 19 4 solar               1                 0            NaN
DE0 19 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 19 4 solar              NaN                  1.0                   1.0
DE0 19 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 19 4 solar    1.0        0.0
DE0 19 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 19 3 solar is name
DE0 19 3 solar    6226.906258
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 19 0 onwind      NaN       NaN
DE0 19 1 onwind      NaN       NaN
DE0 19 2 onwind      NaN       NaN
DE0 19 3 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 19 3 onwind  0.411390   475.170534
DE0 19 2 onwind  0.361437  2137.128663
DE0 19 1 onwind  0.311226  1765.309617
DE0 19 0 onwind  0.263189  7211.330754
Remaining top onwind capacity outside the cluster: 1612.2991961855914 MW
Capacity of the last onwind generator adjusted to fit cluster size: 524.8294663654699 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 19 3 onwind  DE0 19      PQ        39.446442        0.0              True
DE0 19 2 onwind  DE0 19      PQ       301.405560        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 19 3 onwind   39.446442  475.170534        NaN       0.0  ...
DE0 19 2 onwind  301.405560  524.829466        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 19 3 onwind               1                 0            NaN
DE0 19 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 19 3 onwind              NaN                  1.0                   1.0
DE0 19 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 19 3 onwind    1.0        0.0
DE0 19 2 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 19 2 onwind is name
DE0 19 2 onwind    1612.299196
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 2 0 solar-hsat       NaN       NaN
DE0 20 0 solar-hsat      NaN       NaN
DE0 21 0 solar-hsat      NaN       NaN
DE0 22 0 solar-hsat      NaN       NaN
DE0 23 0 solar-hsat      NaN       NaN
DE0 24 0 solar-hsat      NaN       NaN
DE0 25 0 solar-hsat      NaN       NaN
DE0 26 0 solar-hsat      NaN       NaN
DE0 27 0 solar-hsat      NaN       NaN
DE0 28 0 solar-hsat      NaN       NaN
DE0 29 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 23 0 solar-hsat  0.142116  15855.113630
DE0 27 0 solar-hsat  0.137464  13221.286547
DE0 20 0 solar-hsat  0.133115  15849.809050
DE0 22 0 solar-hsat  0.133072  26866.785220
DE0 26 0 solar-hsat  0.131494  16309.190930
DE0 2 0 solar-hsat   0.130135  27536.440826
DE0 25 0 solar-hsat  0.129753  34248.816034
DE0 29 0 solar-hsat  0.129102  23535.564557
DE0 24 0 solar-hsat  0.128614  30066.036432
DE0 28 0 solar-hsat  0.127956  19661.781979
DE0 21 0 solar-hsat  0.126794  18364.312285
Remaining top solar-hsat capacity outside the cluster: 14855.11363006901 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 23 0 solar-hsat  DE0 23      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 23 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 23 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 23 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 23 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 23 0 solar-hsat is name
DE0 23 0 solar-hsat    14855.11363
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 2 0 solar       NaN       NaN
DE0 2 1 solar       NaN       NaN
DE0 2 2 solar       NaN       NaN
DE0 2 3 solar       NaN       NaN
DE0 2 4 solar       NaN       NaN
DE0 20 0 solar      NaN       NaN
DE0 20 1 solar      NaN       NaN
DE0 20 2 solar      NaN       NaN
DE0 20 3 solar      NaN       NaN
DE0 20 4 solar      NaN       NaN
DE0 21 0 solar      NaN       NaN
DE0 21 1 solar      NaN       NaN
DE0 21 2 solar      NaN       NaN
DE0 21 3 solar      NaN       NaN
DE0 21 4 solar      NaN       NaN
DE0 22 0 solar      NaN       NaN
DE0 22 1 solar      NaN       NaN
DE0 22 2 solar      NaN       NaN
DE0 22 3 solar      NaN       NaN
DE0 22 4 solar      NaN       NaN
DE0 23 0 solar      NaN       NaN
DE0 23 1 solar      NaN       NaN
DE0 23 2 solar      NaN       NaN
DE0 23 3 solar      NaN       NaN
DE0 23 4 solar      NaN       NaN
DE0 24 0 solar      NaN       NaN
DE0 24 1 solar      NaN       NaN
DE0 24 2 solar      NaN       NaN
DE0 24 3 solar      NaN       NaN
DE0 24 4 solar      NaN       NaN
DE0 25 0 solar      NaN       NaN
DE0 25 1 solar      NaN       NaN
DE0 25 2 solar      NaN       NaN
DE0 25 3 solar      NaN       NaN
DE0 25 4 solar      NaN       NaN
DE0 26 0 solar      NaN       NaN
DE0 26 1 solar      NaN       NaN
DE0 26 2 solar      NaN       NaN
DE0 26 3 solar      NaN       NaN
DE0 26 4 solar      NaN       NaN
DE0 27 0 solar      NaN       NaN
DE0 27 1 solar      NaN       NaN
DE0 27 2 solar      NaN       NaN
DE0 27 3 solar      NaN       NaN
DE0 27 4 solar      NaN       NaN
DE0 28 0 solar      NaN       NaN
DE0 28 1 solar      NaN       NaN
DE0 28 2 solar      NaN       NaN
DE0 28 3 solar      NaN       NaN
DE0 28 4 solar      NaN       NaN
DE0 29 0 solar      NaN       NaN
DE0 29 1 solar      NaN       NaN
DE0 29 2 solar      NaN       NaN
DE0 29 3 solar      NaN       NaN
DE0 29 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 23 4 solar  0.126490     11.003142
DE0 23 3 solar  0.122227   5019.302690
DE0 27 4 solar  0.121861   1276.995404
DE0 23 2 solar  0.119034   7987.154193
DE0 27 3 solar  0.118035   1706.877716
DE0 23 1 solar  0.117452   4198.376370
DE0 20 4 solar  0.116802    682.671040
DE0 27 2 solar  0.115881   6389.166144
DE0 26 4 solar  0.115457   2231.701705
DE0 23 0 solar  0.114055   1037.228959
DE0 20 3 solar  0.113539   7530.997896
DE0 26 3 solar  0.113454   2491.187540
DE0 27 1 solar  0.112734   3966.805480
DE0 22 4 solar  0.112275   9247.058729
DE0 25 4 solar  0.111928    210.959989
DE0 29 4 solar  0.111577   4764.872651
DE0 2 4 solar   0.111563     21.744011
DE0 28 4 solar  0.111446   1298.094118
DE0 22 3 solar  0.111213  16055.334658
DE0 20 2 solar  0.110600   5334.460415
DE0 26 2 solar  0.110544   5792.944050
DE0 25 3 solar  0.110501   9380.741241
DE0 24 3 solar  0.110279   5251.712828
DE0 28 3 solar  0.110058   4315.992336
DE0 27 0 solar  0.109981   1881.049474
DE0 2 3 solar   0.109828   8505.099216
DE0 29 3 solar  0.109279  10756.596678
DE0 21 4 solar  0.109151   3878.408902
DE0 24 2 solar  0.108829   5514.904337
DE0 25 2 solar  0.108770  21408.164419
DE0 22 2 solar  0.108740   4099.728385
DE0 2 2 solar   0.108728  13770.877096
DE0 20 1 solar  0.108407   3607.584835
DE0 21 3 solar  0.107821   8350.828585
DE0 22 1 solar  0.107816   1355.605030
DE0 26 1 solar  0.107687   7678.499893
DE0 2 1 solar   0.107530   6977.623403
DE0 28 2 solar  0.107188   6257.609548
DE0 25 1 solar  0.107121   6397.304987
DE0 24 1 solar  0.107084  19241.511790
DE0 29 2 solar  0.107057   8666.557516
DE0 28 1 solar  0.106210  10710.236858
DE0 21 2 solar  0.106052   4246.025625
DE0 2 0 solar   0.106012   2425.750678
DE0 26 0 solar  0.105932    581.484813
DE0 25 0 solar  0.105837   2031.488906
DE0 24 0 solar  0.105745   4605.140978
DE0 20 0 solar  0.105341   1091.244314
DE0 22 0 solar  0.105338    172.432254
DE0 28 0 solar  0.103911     53.527206
DE0 29 1 solar  0.103887   2906.752922
DE0 21 1 solar  0.103885   3448.706492
DE0 29 0 solar  0.102157      0.339700
DE0 21 0 solar  0.101509   1217.789460
DE0 24 4 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 4030.3058314923246 MW
Capacity of the last solar generator adjusted to fit cluster size: 988.9968580619086 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 23 4 solar  DE0 23      PQ         0.246261        0.0              True
DE0 23 3 solar  DE0 23      PQ       127.250989        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 23 4 solar    0.246261   11.003142        NaN       0.0  ...
DE0 23 3 solar  127.250989  988.996858        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 23 4 solar               1                 0            NaN
DE0 23 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 23 4 solar              NaN                  1.0                   1.0
DE0 23 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 23 4 solar    1.0        0.0
DE0 23 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 23 3 solar is name
DE0 23 3 solar    4030.305831
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 2 0 onwind       NaN       NaN
DE0 2 1 onwind       NaN       NaN
DE0 2 2 onwind       NaN       NaN
DE0 2 3 onwind       NaN       NaN
DE0 2 4 onwind       NaN       NaN
DE0 20 0 onwind      NaN       NaN
DE0 20 1 onwind      NaN       NaN
DE0 20 2 onwind      NaN       NaN
DE0 20 3 onwind      NaN       NaN
DE0 20 4 onwind      NaN       NaN
DE0 21 0 onwind      NaN       NaN
DE0 21 1 onwind      NaN       NaN
DE0 21 2 onwind      NaN       NaN
DE0 21 3 onwind      NaN       NaN
DE0 21 4 onwind      NaN       NaN
DE0 22 0 onwind      NaN       NaN
DE0 22 1 onwind      NaN       NaN
DE0 22 2 onwind      NaN       NaN
DE0 22 3 onwind      NaN       NaN
DE0 22 4 onwind      NaN       NaN
DE0 23 0 onwind      NaN       NaN
DE0 23 1 onwind      NaN       NaN
DE0 23 2 onwind      NaN       NaN
DE0 23 3 onwind      NaN       NaN
DE0 23 4 onwind      NaN       NaN
DE0 24 0 onwind      NaN       NaN
DE0 24 1 onwind      NaN       NaN
DE0 24 2 onwind      NaN       NaN
DE0 24 3 onwind      NaN       NaN
DE0 24 4 onwind      NaN       NaN
DE0 25 0 onwind      NaN       NaN
DE0 25 1 onwind      NaN       NaN
DE0 25 2 onwind      NaN       NaN
DE0 25 3 onwind      NaN       NaN
DE0 25 4 onwind      NaN       NaN
DE0 26 0 onwind      NaN       NaN
DE0 26 1 onwind      NaN       NaN
DE0 26 2 onwind      NaN       NaN
DE0 26 3 onwind      NaN       NaN
DE0 26 4 onwind      NaN       NaN
DE0 27 0 onwind      NaN       NaN
DE0 27 1 onwind      NaN       NaN
DE0 27 2 onwind      NaN       NaN
DE0 27 3 onwind      NaN       NaN
DE0 27 4 onwind      NaN       NaN
DE0 28 0 onwind      NaN       NaN
DE0 28 1 onwind      NaN       NaN
DE0 28 2 onwind      NaN       NaN
DE0 28 3 onwind      NaN       NaN
DE0 28 4 onwind      NaN       NaN
DE0 29 0 onwind      NaN       NaN
DE0 29 1 onwind      NaN       NaN
DE0 29 2 onwind      NaN       NaN
DE0 29 3 onwind      NaN       NaN
DE0 29 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 24 4 onwind  0.530672     26.744796
DE0 24 3 onwind  0.455465   1020.101317
DE0 24 2 onwind  0.378414   2297.988641
DE0 24 1 onwind  0.341874   5514.256911
DE0 24 0 onwind  0.291461   5086.832636
DE0 29 4 onwind  0.276824    849.351232
DE0 29 3 onwind  0.262080     64.752590
DE0 25 4 onwind  0.253700    168.807652
DE0 25 3 onwind  0.239682    537.327973
DE0 29 2 onwind  0.237834   2576.682918
DE0 28 4 onwind  0.227537   2642.302139
DE0 25 2 onwind  0.227056   3965.526962
DE0 28 3 onwind  0.220167    991.262966
DE0 29 1 onwind  0.214614    979.091888
DE0 28 2 onwind  0.213003   4692.553783
DE0 25 1 onwind  0.212003   1526.132726
DE0 28 1 onwind  0.206148   3099.782261
DE0 25 0 onwind  0.202065  14104.819897
DE0 28 0 onwind  0.200590   2331.404738
DE0 21 4 onwind  0.197610   1520.972798
DE0 21 3 onwind  0.187118   4296.709305
DE0 20 4 onwind  0.186060     10.000000
DE0 29 0 onwind  0.185650     34.530328
DE0 20 3 onwind  0.173250    480.969706
DE0 21 2 onwind  0.169299   1095.951091
DE0 27 4 onwind  0.167264    275.607890
DE0 22 4 onwind  0.165348   5372.422090
DE0 20 2 onwind  0.163656    502.379020
DE0 2 4 onwind   0.160171   2493.928774
DE0 20 1 onwind  0.158144   3380.920522
DE0 26 4 onwind  0.157734   3528.990344
DE0 21 1 onwind  0.157542   1880.231568
DE0 22 3 onwind  0.156779   5627.972851
DE0 22 2 onwind  0.150142   4434.574024
DE0 2 3 onwind   0.149107   2869.620008
DE0 20 0 onwind  0.148203    964.684649
DE0 21 0 onwind  0.147249    888.097209
DE0 26 3 onwind  0.145616   5181.847005
DE0 2 2 onwind   0.144082  12728.159700
DE0 22 1 onwind  0.142822    616.035639
DE0 2 1 onwind   0.134131    374.457335
DE0 27 3 onwind  0.133959   1055.583778
DE0 22 0 onwind  0.131768    319.370828
DE0 2 0 onwind   0.128906    314.924401
DE0 23 4 onwind  0.128892   3993.490139
DE0 26 2 onwind  0.127910   1155.745199
DE0 23 3 onwind  0.113286   1316.318172
DE0 27 2 onwind  0.112919   1711.939864
DE0 26 1 onwind  0.111390   3656.012903
DE0 27 1 onwind  0.090221   2498.242025
DE0 26 0 onwind  0.089225    178.591926
DE0 23 2 onwind  0.070563   3733.797687
DE0 27 0 onwind  0.064747   2278.096968
DE0 23 1 onwind  0.061270    998.615695
DE0 23 0 onwind  0.012640    247.401545
Remaining top onwind capacity outside the cluster: 46.84611286951758 MW
Capacity of the last onwind generator adjusted to fit cluster size: 973.2552041163607 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 24 4 onwind  DE0 24      PQ         2.065335        0.0              True
DE0 24 3 onwind  DE0 24      PQ       290.612000        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 24 4 onwind    2.065335   26.744796        NaN       0.0  ...
DE0 24 3 onwind  290.612000  973.255204        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 24 4 onwind               1                 0            NaN
DE0 24 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 24 4 onwind              NaN                  1.0                   1.0
DE0 24 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 24 4 onwind    1.0        0.0
DE0 24 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 24 3 onwind is name
DE0 24 3 onwind    46.846113
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 20 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 20 0 solar-hsat  0.133115  15849.80905
Remaining top solar-hsat capacity outside the cluster: 14849.809050179601 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 20 0 solar-hsat  DE0 20      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 20 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 20 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 20 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 20 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 20 0 solar-hsat is name
DE0 20 0 solar-hsat    14849.80905
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 20 0 solar      NaN       NaN
DE0 20 1 solar      NaN       NaN
DE0 20 2 solar      NaN       NaN
DE0 20 3 solar      NaN       NaN
DE0 20 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 20 4 solar  0.116802   682.671040
DE0 20 3 solar  0.113539  7530.997896
DE0 20 2 solar  0.110600  5334.460415
DE0 20 1 solar  0.108407  3607.584835
DE0 20 0 solar  0.105341  1091.244314
Remaining top solar capacity outside the cluster: 7213.668936443693 MW
Capacity of the last solar generator adjusted to fit cluster size: 317.3289597852902 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 20 4 solar  DE0 20      PQ        18.408690        0.0              True
DE0 20 3 solar  DE0 20      PQ       201.293489        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 20 4 solar   18.408690  682.67104        NaN       0.0  ...
DE0 20 3 solar  201.293489  317.32896        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 20 4 solar               1                 0            NaN
DE0 20 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 20 4 solar              NaN                  1.0                   1.0
DE0 20 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 20 4 solar    1.0        0.0
DE0 20 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 20 3 solar is name
DE0 20 3 solar    7213.668936
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 20 0 onwind      NaN       NaN
DE0 20 1 onwind      NaN       NaN
DE0 20 2 onwind      NaN       NaN
DE0 20 3 onwind      NaN       NaN
DE0 20 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 20 4 onwind  0.186060    10.000000
DE0 20 3 onwind  0.173250   480.969706
DE0 20 2 onwind  0.163656   502.379020
DE0 20 1 onwind  0.158144  3380.920522
DE0 20 0 onwind  0.148203   964.684649
Remaining top onwind capacity outside the cluster: 3374.26924815263 MW
Capacity of the last onwind generator adjusted to fit cluster size: 6.651274195096221 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 20 4 onwind  DE0 20      PQ        10.000000        0.0              True
DE0 20 3 onwind  DE0 20      PQ        74.125943        0.0              True
DE0 20 2 onwind  DE0 20      PQ        43.964350        0.0              True
DE0 20 1 onwind  DE0 20      PQ       160.806106        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 20 4 onwind   10.000000   10.000000        NaN       0.0  ...
DE0 20 3 onwind   74.125943  480.969706        NaN       0.0  ...
DE0 20 2 onwind   43.964350  502.379020        NaN       0.0  ...
DE0 20 1 onwind  160.806106    6.651274        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 20 4 onwind               1                 0            NaN
DE0 20 3 onwind               1                 0            NaN
DE0 20 2 onwind               1                 0            NaN
DE0 20 1 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 20 4 onwind              NaN                  1.0                   1.0
DE0 20 3 onwind              NaN                  1.0                   1.0
DE0 20 2 onwind              NaN                  1.0                   1.0
DE0 20 1 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 20 4 onwind    1.0        0.0
DE0 20 3 onwind    1.0        0.0
DE0 20 2 onwind    1.0        0.0
DE0 20 1 onwind    1.0        0.0

[4 rows x 40 columns]
Residual capacity of generator DE0 20 1 onwind is name
DE0 20 1 onwind    3374.269248
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 21 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 21 0 solar-hsat  0.126794  18364.312285
Remaining top solar-hsat capacity outside the cluster: 17364.312284852716 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 21 0 solar-hsat  DE0 21      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 21 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 21 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 21 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 21 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 21 0 solar-hsat is name
DE0 21 0 solar-hsat    17364.312285
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 21 0 solar      NaN       NaN
DE0 21 1 solar      NaN       NaN
DE0 21 2 solar      NaN       NaN
DE0 21 3 solar      NaN       NaN
DE0 21 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 21 4 solar  0.109151  3878.408902
DE0 21 3 solar  0.107821  8350.828585
DE0 21 2 solar  0.106052  4246.025625
DE0 21 1 solar  0.103885  3448.706492
DE0 21 0 solar  0.101509  1217.789460
Remaining top solar capacity outside the cluster: 2878.408901671824 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 21 4 solar  DE0 21      PQ       167.403866        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 21 4 solar  167.403866     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 21 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 21 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 21 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 21 4 solar is name
DE0 21 4 solar    2878.408902
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 21 0 onwind      NaN       NaN
DE0 21 1 onwind      NaN       NaN
DE0 21 2 onwind      NaN       NaN
DE0 21 3 onwind      NaN       NaN
DE0 21 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 21 4 onwind  0.197610  1520.972798
DE0 21 3 onwind  0.187118  4296.709305
DE0 21 2 onwind  0.169299  1095.951091
DE0 21 1 onwind  0.157542  1880.231568
DE0 21 0 onwind  0.147249   888.097209
Remaining top onwind capacity outside the cluster: 520.972798101827 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 21 4 onwind  DE0 21      PQ       310.737567        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 21 4 onwind  310.737567     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 21 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 21 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 21 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 21 4 onwind is name
DE0 21 4 onwind    520.972798
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 22 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 22 0 solar-hsat  0.133072  26866.78522
Remaining top solar-hsat capacity outside the cluster: 25866.78521950407 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 22 0 solar-hsat  DE0 22      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 22 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 22 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 22 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 22 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 22 0 solar-hsat is name
DE0 22 0 solar-hsat    25866.78522
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 22 0 solar      NaN       NaN
DE0 22 1 solar      NaN       NaN
DE0 22 2 solar      NaN       NaN
DE0 22 3 solar      NaN       NaN
DE0 22 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 22 4 solar  0.112275   9247.058729
DE0 22 3 solar  0.111213  16055.334658
DE0 22 2 solar  0.108740   4099.728385
DE0 22 1 solar  0.107816   1355.605030
DE0 22 0 solar  0.105338    172.432254
Remaining top solar capacity outside the cluster: 8247.058729420474 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 22 4 solar  DE0 22      PQ       466.500264        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 22 4 solar  466.500264     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 22 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 22 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 22 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 22 4 solar is name
DE0 22 4 solar    8247.058729
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 22 0 onwind      NaN       NaN
DE0 22 1 onwind      NaN       NaN
DE0 22 2 onwind      NaN       NaN
DE0 22 3 onwind      NaN       NaN
DE0 22 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 22 4 onwind  0.165348  5372.422090
DE0 22 3 onwind  0.156779  5627.972851
DE0 22 2 onwind  0.150142  4434.574024
DE0 22 1 onwind  0.142822   616.035639
DE0 22 0 onwind  0.131768   319.370828
Remaining top onwind capacity outside the cluster: 4372.422090095031 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 22 4 onwind  DE0 22      PQ       405.268801        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 22 4 onwind  405.268801     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 22 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 22 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 22 4 onwind    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 22 4 onwind is name
DE0 22 4 onwind    4372.42209
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 23 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 23 0 solar-hsat  0.142116  14855.11363
Remaining top solar-hsat capacity outside the cluster: 13855.11363006901 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 23 0 solar-hsat  DE0 23      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 23 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 23 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 23 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 23 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 23 0 solar-hsat is name
DE0 23 0 solar-hsat    13855.11363
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 23 0 solar      NaN       NaN
DE0 23 1 solar      NaN       NaN
DE0 23 2 solar      NaN       NaN
DE0 23 3 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 23 3 solar  0.122227  4030.305831
DE0 23 2 solar  0.119034  7987.154193
DE0 23 1 solar  0.117452  4198.376370
DE0 23 0 solar  0.114055  1037.228959
Remaining top solar capacity outside the cluster: 3030.3058314923246 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 23 3 solar  DE0 23      PQ       127.250989        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 23 3 solar  127.250989     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 23 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 23 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 23 3 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 23 3 solar is name
DE0 23 3 solar    3030.305831
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 23 0 onwind      NaN       NaN
DE0 23 1 onwind      NaN       NaN
DE0 23 2 onwind      NaN       NaN
DE0 23 3 onwind      NaN       NaN
DE0 23 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 23 4 onwind  0.128892  3993.490139
DE0 23 3 onwind  0.113286  1316.318172
DE0 23 2 onwind  0.070563  3733.797687
DE0 23 1 onwind  0.061270   998.615695
DE0 23 0 onwind  0.012640   247.401545
Remaining top onwind capacity outside the cluster: 2993.490139004139 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 23 4 onwind  DE0 23      PQ       85.903844        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 23 4 onwind  85.903844     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 23 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 23 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 23 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 23 4 onwind is name
DE0 23 4 onwind    2993.490139
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 24 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 24 0 solar-hsat  0.128614  30066.036432
Remaining top solar-hsat capacity outside the cluster: 29066.036432247703 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 24 0 solar-hsat  DE0 24      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 24 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 24 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 24 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 24 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 24 0 solar-hsat is name
DE0 24 0 solar-hsat    29066.036432
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 24 0 solar      NaN       NaN
DE0 24 1 solar      NaN       NaN
DE0 24 2 solar      NaN       NaN
DE0 24 3 solar      NaN       NaN
DE0 24 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 24 3 solar  0.110279   5251.712828
DE0 24 2 solar  0.108829   5514.904337
DE0 24 1 solar  0.107084  19241.511790
DE0 24 0 solar  0.105745   4605.140978
DE0 24 4 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 4251.712827792889 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 24 3 solar  DE0 24      PQ       175.974561        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 24 3 solar  175.974561     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 24 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 24 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 24 3 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 24 3 solar is name
DE0 24 3 solar    4251.712828
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 24 0 onwind      NaN       NaN
DE0 24 1 onwind      NaN       NaN
DE0 24 2 onwind      NaN       NaN
DE0 24 3 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 24 3 onwind  0.455465    46.846113
DE0 24 2 onwind  0.378414  2297.988641
DE0 24 1 onwind  0.341874  5514.256911
DE0 24 0 onwind  0.291461  5086.832636
Remaining top onwind capacity outside the cluster: 1344.834754064137 MW
Capacity of the last onwind generator adjusted to fit cluster size: 953.1538871304824 MW
                    bus control type        p_nom  p_nom_mod  \
name
DE0 24 3 onwind  DE0 24      PQ        290.612000        0.0
DE0 24 2 onwind  DE0 24      PQ       1394.543612        0.0

                 p_nom_extendable    p_nom_min   p_nom_max  p_nom_set  \
name
DE0 24 3 onwind              True   290.612000   46.846113        NaN
DE0 24 2 onwind              True  1394.543612  953.153887        NaN

                 p_min_pu  ...  up_time_before  down_time_before  \
name                       ...
DE0 24 3 onwind       0.0  ...               1                 0
DE0 24 2 onwind       0.0  ...               1                 0

                 ramp_limit_up  ramp_limit_down  ramp_limit_start_up  \
name
DE0 24 3 onwind            NaN              NaN                  1.0
DE0 24 2 onwind            NaN              NaN                  1.0

                 ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 24 3 onwind                   1.0    1.0        0.0
DE0 24 2 onwind                   1.0    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 24 2 onwind is name
DE0 24 2 onwind    1344.834754
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 25 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 25 0 solar-hsat  0.129753  34248.816034
Remaining top solar-hsat capacity outside the cluster: 33248.8160337898 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 25 0 solar-hsat  DE0 25      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 25 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 25 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 25 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 25 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 25 0 solar-hsat is name
DE0 25 0 solar-hsat    33248.816034
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 25 0 solar      NaN       NaN
DE0 25 1 solar      NaN       NaN
DE0 25 2 solar      NaN       NaN
DE0 25 3 solar      NaN       NaN
DE0 25 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 25 4 solar  0.111928    210.959989
DE0 25 3 solar  0.110501   9380.741241
DE0 25 2 solar  0.108770  21408.164419
DE0 25 1 solar  0.107121   6397.304987
DE0 25 0 solar  0.105837   2031.488906
Remaining top solar capacity outside the cluster: 8591.70123025853 MW
Capacity of the last solar generator adjusted to fit cluster size: 789.0400110982346 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 25 4 solar  DE0 25      PQ         4.177961        0.0              True
DE0 25 3 solar  DE0 25      PQ       694.711245        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 25 4 solar    4.177961  210.959989        NaN       0.0  ...
DE0 25 3 solar  694.711245  789.040011        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 25 4 solar               1                 0            NaN
DE0 25 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 25 4 solar              NaN                  1.0                   1.0
DE0 25 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 25 4 solar    1.0        0.0
DE0 25 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 25 3 solar is name
DE0 25 3 solar    8591.70123
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 25 0 onwind      NaN       NaN
DE0 25 1 onwind      NaN       NaN
DE0 25 2 onwind      NaN       NaN
DE0 25 3 onwind      NaN       NaN
DE0 25 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 25 4 onwind  0.253700    168.807652
DE0 25 3 onwind  0.239682    537.327973
DE0 25 2 onwind  0.227056   3965.526962
DE0 25 1 onwind  0.212003   1526.132726
DE0 25 0 onwind  0.202065  14104.819897
Remaining top onwind capacity outside the cluster: 3671.662586376826 MW
Capacity of the last onwind generator adjusted to fit cluster size: 293.86437530111994 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 25 4 onwind  DE0 25      PQ         6.232152        0.0              True
DE0 25 3 onwind  DE0 25      PQ        37.741295        0.0              True
DE0 25 2 onwind  DE0 25      PQ       531.026371        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 25 4 onwind    6.232152  168.807652        NaN       0.0  ...
DE0 25 3 onwind   37.741295  537.327973        NaN       0.0  ...
DE0 25 2 onwind  531.026371  293.864375        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 25 4 onwind               1                 0            NaN
DE0 25 3 onwind               1                 0            NaN
DE0 25 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 25 4 onwind              NaN                  1.0                   1.0
DE0 25 3 onwind              NaN                  1.0                   1.0
DE0 25 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 25 4 onwind    1.0        0.0
DE0 25 3 onwind    1.0        0.0
DE0 25 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 25 2 onwind is name
DE0 25 2 onwind    3671.662586
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 26 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 26 0 solar-hsat  0.131494  16309.19093
Remaining top solar-hsat capacity outside the cluster: 15309.190929970566 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 26 0 solar-hsat  DE0 26      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 26 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 26 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 26 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 26 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 26 0 solar-hsat is name
DE0 26 0 solar-hsat    15309.19093
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 26 0 solar      NaN       NaN
DE0 26 1 solar      NaN       NaN
DE0 26 2 solar      NaN       NaN
DE0 26 3 solar      NaN       NaN
DE0 26 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 26 4 solar  0.115457  2231.701705
DE0 26 3 solar  0.113454  2491.187540
DE0 26 2 solar  0.110544  5792.944050
DE0 26 1 solar  0.107687  7678.499893
DE0 26 0 solar  0.105932   581.484813
Remaining top solar capacity outside the cluster: 1231.7017046863575 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 26 4 solar  DE0 26      PQ       152.89109        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 26 4 solar  152.89109     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 26 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 26 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 26 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 26 4 solar is name
DE0 26 4 solar    1231.701705
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 26 0 onwind      NaN       NaN
DE0 26 1 onwind      NaN       NaN
DE0 26 2 onwind      NaN       NaN
DE0 26 3 onwind      NaN       NaN
DE0 26 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 26 4 onwind  0.157734  3528.990344
DE0 26 3 onwind  0.145616  5181.847005
DE0 26 2 onwind  0.127910  1155.745199
DE0 26 1 onwind  0.111390  3656.012903
DE0 26 0 onwind  0.089225   178.591926
Remaining top onwind capacity outside the cluster: 2528.9903438127153 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 26 4 onwind  DE0 26      PQ       81.003188        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 26 4 onwind  81.003188     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 26 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 26 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 26 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 26 4 onwind is name
DE0 26 4 onwind    2528.990344
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 27 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 27 0 solar-hsat  0.137464  13221.286547
Remaining top solar-hsat capacity outside the cluster: 12221.286546913652 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 27 0 solar-hsat  DE0 27      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 27 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 27 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 27 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 27 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 27 0 solar-hsat is name
DE0 27 0 solar-hsat    12221.286547
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 27 0 solar      NaN       NaN
DE0 27 1 solar      NaN       NaN
DE0 27 2 solar      NaN       NaN
DE0 27 3 solar      NaN       NaN
DE0 27 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 27 4 solar  0.121861  1276.995404
DE0 27 3 solar  0.118035  1706.877716
DE0 27 2 solar  0.115881  6389.166144
DE0 27 1 solar  0.112734  3966.805480
DE0 27 0 solar  0.109981  1881.049474
Remaining top solar capacity outside the cluster: 276.99540381146016 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 27 4 solar  DE0 27      PQ       36.234474        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 27 4 solar  36.234474     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 27 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 27 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 27 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 27 4 solar is name
DE0 27 4 solar    276.995404
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 27 0 onwind      NaN       NaN
DE0 27 1 onwind      NaN       NaN
DE0 27 2 onwind      NaN       NaN
DE0 27 3 onwind      NaN       NaN
DE0 27 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 27 4 onwind  0.167264   275.607890
DE0 27 3 onwind  0.133959  1055.583778
DE0 27 2 onwind  0.112919  1711.939864
DE0 27 1 onwind  0.090221  2498.242025
DE0 27 0 onwind  0.064747  2278.096968
Remaining top onwind capacity outside the cluster: 331.19166844196843 MW
Capacity of the last onwind generator adjusted to fit cluster size: 724.39210957158 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 27 4 onwind  DE0 27      PQ       41.708396        0.0              True
DE0 27 3 onwind  DE0 27      PQ       53.577389        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 27 4 onwind  41.708396  275.60789        NaN       0.0  ...
DE0 27 3 onwind  53.577389  724.39211        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 27 4 onwind               1                 0            NaN
DE0 27 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 27 4 onwind              NaN                  1.0                   1.0
DE0 27 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 27 4 onwind    1.0        0.0
DE0 27 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 27 3 onwind is name
DE0 27 3 onwind    331.191668
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 28 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 28 0 solar-hsat  0.127956  19661.781979
Remaining top solar-hsat capacity outside the cluster: 18661.781978520434 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 28 0 solar-hsat  DE0 28      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 28 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 28 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 28 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 28 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 28 0 solar-hsat is name
DE0 28 0 solar-hsat    18661.781979
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 28 0 solar      NaN       NaN
DE0 28 1 solar      NaN       NaN
DE0 28 2 solar      NaN       NaN
DE0 28 3 solar      NaN       NaN
DE0 28 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 28 4 solar  0.111446   1298.094118
DE0 28 3 solar  0.110058   4315.992336
DE0 28 2 solar  0.107188   6257.609548
DE0 28 1 solar  0.106210  10710.236858
DE0 28 0 solar  0.103911     53.527206
Remaining top solar capacity outside the cluster: 298.0941180982313 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 28 4 solar  DE0 28      PQ       265.697429        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 28 4 solar  265.697429     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 28 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 28 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 28 4 solar    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 28 4 solar is name
DE0 28 4 solar    298.094118
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 28 0 onwind      NaN       NaN
DE0 28 1 onwind      NaN       NaN
DE0 28 2 onwind      NaN       NaN
DE0 28 3 onwind      NaN       NaN
DE0 28 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 28 4 onwind  0.227537  2642.302139
DE0 28 3 onwind  0.220167   991.262966
DE0 28 2 onwind  0.213003  4692.553783
DE0 28 1 onwind  0.206148  3099.782261
DE0 28 0 onwind  0.200590  2331.404738
Remaining top onwind capacity outside the cluster: 1642.3021391060315 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 28 4 onwind  DE0 28      PQ       492.490296        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 28 4 onwind  492.490296     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 28 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 28 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 28 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 28 4 onwind is name
DE0 28 4 onwind    1642.302139
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 29 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 29 0 solar-hsat  0.129102  23535.564557
Remaining top solar-hsat capacity outside the cluster: 22535.564556725763 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 29 0 solar-hsat  DE0 29      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 29 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 29 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 29 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 29 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 29 0 solar-hsat is name
DE0 29 0 solar-hsat    22535.564557
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 29 0 solar      NaN       NaN
DE0 29 1 solar      NaN       NaN
DE0 29 2 solar      NaN       NaN
DE0 29 3 solar      NaN       NaN
DE0 29 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 29 4 solar  0.111577   4764.872651
DE0 29 3 solar  0.109279  10756.596678
DE0 29 2 solar  0.107057   8666.557516
DE0 29 1 solar  0.103887   2906.752922
DE0 29 0 solar  0.102157      0.339700
Remaining top solar capacity outside the cluster: 3764.872650800733 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 29 4 solar  DE0 29      PQ       162.669482        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 29 4 solar  162.669482     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 29 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 29 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 29 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 29 4 solar is name
DE0 29 4 solar    3764.872651
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 29 0 onwind      NaN       NaN
DE0 29 1 onwind      NaN       NaN
DE0 29 2 onwind      NaN       NaN
DE0 29 3 onwind      NaN       NaN
DE0 29 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 29 4 onwind  0.276824   849.351232
DE0 29 3 onwind  0.262080    64.752590
DE0 29 2 onwind  0.237834  2576.682918
DE0 29 1 onwind  0.214614   979.091888
DE0 29 0 onwind  0.185650    34.530328
Remaining top onwind capacity outside the cluster: 2490.7867400070336 MW
Capacity of the last onwind generator adjusted to fit cluster size: 85.89617786451458 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 29 4 onwind  DE0 29      PQ       218.215022        0.0              True
DE0 29 3 onwind  DE0 29      PQ         2.469542        0.0              True
DE0 29 2 onwind  DE0 29      PQ       628.178607        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 29 4 onwind  218.215022  849.351232        NaN       0.0  ...
DE0 29 3 onwind    2.469542   64.752590        NaN       0.0  ...
DE0 29 2 onwind  628.178607   85.896178        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 29 4 onwind               1                 0            NaN
DE0 29 3 onwind               1                 0            NaN
DE0 29 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 29 4 onwind              NaN                  1.0                   1.0
DE0 29 3 onwind              NaN                  1.0                   1.0
DE0 29 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 29 4 onwind    1.0        0.0
DE0 29 3 onwind    1.0        0.0
DE0 29 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 29 2 onwind is name
DE0 29 2 onwind    2490.78674
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 3 0 solar-hsat       NaN       NaN
DE0 30 0 solar-hsat      NaN       NaN
DE0 31 0 solar-hsat      NaN       NaN
DE0 32 0 solar-hsat      NaN       NaN
DE0 33 0 solar-hsat      NaN       NaN
DE0 34 0 solar-hsat      NaN       NaN
DE0 35 0 solar-hsat      NaN       NaN
DE0 36 0 solar-hsat      NaN       NaN
DE0 37 0 solar-hsat      NaN       NaN
DE0 38 0 solar-hsat      NaN       NaN
DE0 39 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 35 0 solar-hsat  0.137188  34034.327527
DE0 32 0 solar-hsat  0.135070  22528.290920
DE0 37 0 solar-hsat  0.132704   9713.266757
DE0 36 0 solar-hsat  0.131633  19947.236621
DE0 34 0 solar-hsat  0.130735  25070.679000
DE0 30 0 solar-hsat  0.130131  14860.100070
DE0 39 0 solar-hsat  0.129064  23214.345235
DE0 3 0 solar-hsat   0.128637  18634.621889
DE0 38 0 solar-hsat  0.125511  18681.009611
DE0 31 0 solar-hsat  0.125350  28665.571604
DE0 33 0 solar-hsat  0.124543  25784.001683
Remaining top solar-hsat capacity outside the cluster: 33034.32752689003 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 35 0 solar-hsat  DE0 35      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 35 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 35 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 35 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 35 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 35 0 solar-hsat is name
DE0 35 0 solar-hsat    33034.327527
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 3 0 solar       NaN       NaN
DE0 3 1 solar       NaN       NaN
DE0 3 2 solar       NaN       NaN
DE0 3 3 solar       NaN       NaN
DE0 3 4 solar       NaN       NaN
DE0 30 0 solar      NaN       NaN
DE0 30 1 solar      NaN       NaN
DE0 30 2 solar      NaN       NaN
DE0 30 3 solar      NaN       NaN
DE0 30 4 solar      NaN       NaN
DE0 31 0 solar      NaN       NaN
DE0 31 1 solar      NaN       NaN
DE0 31 2 solar      NaN       NaN
DE0 31 3 solar      NaN       NaN
DE0 31 4 solar      NaN       NaN
DE0 32 0 solar      NaN       NaN
DE0 32 1 solar      NaN       NaN
DE0 32 2 solar      NaN       NaN
DE0 32 3 solar      NaN       NaN
DE0 32 4 solar      NaN       NaN
DE0 33 0 solar      NaN       NaN
DE0 33 1 solar      NaN       NaN
DE0 33 2 solar      NaN       NaN
DE0 33 3 solar      NaN       NaN
DE0 33 4 solar      NaN       NaN
DE0 34 0 solar      NaN       NaN
DE0 34 1 solar      NaN       NaN
DE0 34 2 solar      NaN       NaN
DE0 34 3 solar      NaN       NaN
DE0 34 4 solar      NaN       NaN
DE0 35 0 solar      NaN       NaN
DE0 35 1 solar      NaN       NaN
DE0 35 2 solar      NaN       NaN
DE0 35 3 solar      NaN       NaN
DE0 35 4 solar      NaN       NaN
DE0 36 0 solar      NaN       NaN
DE0 36 1 solar      NaN       NaN
DE0 36 2 solar      NaN       NaN
DE0 36 3 solar      NaN       NaN
DE0 36 4 solar      NaN       NaN
DE0 37 0 solar      NaN       NaN
DE0 37 1 solar      NaN       NaN
DE0 37 2 solar      NaN       NaN
DE0 37 3 solar      NaN       NaN
DE0 37 4 solar      NaN       NaN
DE0 38 0 solar      NaN       NaN
DE0 38 1 solar      NaN       NaN
DE0 38 2 solar      NaN       NaN
DE0 38 3 solar      NaN       NaN
DE0 38 4 solar      NaN       NaN
DE0 39 0 solar      NaN       NaN
DE0 39 1 solar      NaN       NaN
DE0 39 2 solar      NaN       NaN
DE0 39 3 solar      NaN       NaN
DE0 39 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 35 4 solar  0.124605   2647.623633
DE0 32 4 solar  0.118024   1555.460451
DE0 36 4 solar  0.116719    592.257046
DE0 35 2 solar  0.116192  10238.448129
DE0 37 4 solar  0.115908      1.574972
DE0 30 4 solar  0.115726    432.109155
DE0 32 3 solar  0.115482   4343.524583
DE0 32 2 solar  0.114870   4205.898832
DE0 35 1 solar  0.114319  22120.257530
DE0 37 3 solar  0.114057    136.032616
DE0 36 3 solar  0.113920   2769.099133
DE0 3 4 solar   0.113032   2145.376172
DE0 30 3 solar  0.112189   1121.725184
DE0 34 4 solar  0.112078   2141.816572
DE0 37 2 solar  0.111853    239.930802
DE0 32 1 solar  0.111566   7395.881486
DE0 36 2 solar  0.111342   1973.014070
DE0 35 0 solar  0.110900   4175.402173
DE0 34 3 solar  0.110674   5996.382460
DE0 37 1 solar  0.110637   6434.334523
DE0 3 3 solar   0.110229   8225.236620
DE0 32 0 solar  0.110005   8434.738867
DE0 30 2 solar  0.109975   7675.785012
DE0 39 4 solar  0.109936   2958.136487
DE0 37 0 solar  0.109835   4370.443219
DE0 34 2 solar  0.109068  10988.556029
DE0 38 4 solar  0.109023    641.810720
DE0 36 1 solar  0.108480  15557.236460
DE0 39 3 solar  0.108356  18869.485137
DE0 33 4 solar  0.108219    529.282507
DE0 38 3 solar  0.107785   2840.419248
DE0 34 1 solar  0.107781   9735.288397
DE0 31 4 solar  0.107341   4779.516814
DE0 3 2 solar   0.107244   4879.952620
DE0 39 2 solar  0.107047   3523.148937
DE0 36 0 solar  0.106819   2072.480597
DE0 33 3 solar  0.106698  13807.859926
DE0 30 1 solar  0.106674   6653.856381
DE0 31 3 solar  0.106157  16991.073076
DE0 38 2 solar  0.106100   3850.375560
DE0 34 0 solar  0.105611      0.363517
DE0 39 1 solar  0.105086   1374.261925
DE0 38 1 solar  0.105047   9918.938655
DE0 33 2 solar  0.105012   6683.855549
DE0 31 2 solar  0.104707   3911.605401
DE0 38 0 solar  0.104367   4254.809996
DE0 3 1 solar   0.103674   3131.774645
DE0 33 1 solar  0.103557   8661.007644
DE0 31 1 solar  0.103502   3975.674945
DE0 30 0 solar  0.103364   1224.088684
DE0 39 0 solar  0.102900      0.285956
DE0 33 0 solar  0.102071      1.608048
DE0 3 0 solar   0.101671   3070.610652
DE0 31 0 solar  0.101616   3343.126418
DE0 35 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 1647.623632516521 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 35 4 solar  DE0 35      PQ       59.473559        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 35 4 solar  59.473559     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 35 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 35 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 35 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 35 4 solar is name
DE0 35 4 solar    1647.623633
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 3 0 onwind       NaN       NaN
DE0 3 1 onwind       NaN       NaN
DE0 3 2 onwind       NaN       NaN
DE0 3 3 onwind       NaN       NaN
DE0 3 4 onwind       NaN       NaN
DE0 30 0 onwind      NaN       NaN
DE0 30 1 onwind      NaN       NaN
DE0 30 2 onwind      NaN       NaN
DE0 30 3 onwind      NaN       NaN
DE0 30 4 onwind      NaN       NaN
DE0 31 0 onwind      NaN       NaN
DE0 31 1 onwind      NaN       NaN
DE0 31 2 onwind      NaN       NaN
DE0 31 3 onwind      NaN       NaN
DE0 31 4 onwind      NaN       NaN
DE0 32 0 onwind      NaN       NaN
DE0 32 1 onwind      NaN       NaN
DE0 32 2 onwind      NaN       NaN
DE0 32 3 onwind      NaN       NaN
DE0 32 4 onwind      NaN       NaN
DE0 33 0 onwind      NaN       NaN
DE0 33 1 onwind      NaN       NaN
DE0 33 2 onwind      NaN       NaN
DE0 33 3 onwind      NaN       NaN
DE0 33 4 onwind      NaN       NaN
DE0 34 0 onwind      NaN       NaN
DE0 34 1 onwind      NaN       NaN
DE0 34 2 onwind      NaN       NaN
DE0 34 3 onwind      NaN       NaN
DE0 34 4 onwind      NaN       NaN
DE0 35 0 onwind      NaN       NaN
DE0 35 1 onwind      NaN       NaN
DE0 35 2 onwind      NaN       NaN
DE0 35 3 onwind      NaN       NaN
DE0 35 4 onwind      NaN       NaN
DE0 36 0 onwind      NaN       NaN
DE0 36 1 onwind      NaN       NaN
DE0 36 2 onwind      NaN       NaN
DE0 36 3 onwind      NaN       NaN
DE0 36 4 onwind      NaN       NaN
DE0 37 0 onwind      NaN       NaN
DE0 37 1 onwind      NaN       NaN
DE0 37 2 onwind      NaN       NaN
DE0 37 3 onwind      NaN       NaN
DE0 37 4 onwind      NaN       NaN
DE0 38 0 onwind      NaN       NaN
DE0 38 1 onwind      NaN       NaN
DE0 38 2 onwind      NaN       NaN
DE0 38 3 onwind      NaN       NaN
DE0 38 4 onwind      NaN       NaN
DE0 39 0 onwind      NaN       NaN
DE0 39 1 onwind      NaN       NaN
DE0 39 2 onwind      NaN       NaN
DE0 39 3 onwind      NaN       NaN
DE0 39 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 36 4 onwind  0.522943    247.914549
DE0 38 4 onwind  0.488161    560.395407
DE0 36 3 onwind  0.456766   1315.263232
DE0 38 3 onwind  0.422406     26.348205
DE0 36 2 onwind  0.383916   2141.799114
DE0 38 2 onwind  0.374493    515.341583
DE0 34 4 onwind  0.370175    738.423218
DE0 34 3 onwind  0.332121      0.155479
DE0 36 1 onwind  0.326594   3204.488595
DE0 38 1 onwind  0.319016   2038.571064
DE0 34 2 onwind  0.289837   2570.680598
DE0 31 4 onwind  0.279388    316.925303
DE0 38 0 onwind  0.279388   5437.286893
DE0 36 0 onwind  0.274365   2539.492764
DE0 31 3 onwind  0.265051    765.403698
DE0 34 1 onwind  0.256510   4884.972313
DE0 31 2 onwind  0.253386   3079.677549
DE0 30 4 onwind  0.250279    413.711153
DE0 31 1 onwind  0.245596   5089.733839
DE0 3 4 onwind   0.243671   2755.612521
DE0 33 4 onwind  0.240776    371.211954
DE0 31 0 onwind  0.239540   3667.470527
DE0 39 4 onwind  0.229010    923.285488
DE0 33 3 onwind  0.226956   1693.316402
DE0 30 3 onwind  0.223439    949.376975
DE0 39 3 onwind  0.222259   1989.145999
DE0 34 0 onwind  0.219629   6403.513332
DE0 3 3 onwind   0.216769   1804.290513
DE0 39 2 onwind  0.215506   3052.418066
DE0 33 2 onwind  0.213093   2465.822382
DE0 30 2 onwind  0.211128    336.819019
DE0 39 1 onwind  0.205182   6363.999223
DE0 37 4 onwind  0.198920   2071.036381
DE0 33 1 onwind  0.197481   3977.078940
DE0 39 0 onwind  0.195859    394.482233
DE0 3 2 onwind   0.191979    835.923540
DE0 37 3 onwind  0.188423   2056.862963
DE0 33 0 onwind  0.184020   5631.876329
DE0 30 1 onwind  0.182820   4211.798298
DE0 3 1 onwind   0.178238   2665.079451
DE0 37 2 onwind  0.176375    619.322488
DE0 32 4 onwind  0.164297   1785.147118
DE0 37 1 onwind  0.163033    383.778696
DE0 30 0 onwind  0.162146   2274.721159
DE0 3 0 onwind   0.155997   2749.767533
DE0 32 2 onwind  0.144543   5468.902986
DE0 37 0 onwind  0.139928      1.468006
DE0 32 1 onwind  0.138211   2398.662571
DE0 32 0 onwind  0.128685   2072.317675
DE0 35 4 onwind  0.125175  11947.163702
DE0 35 3 onwind  0.108537   4030.300185
DE0 35 2 onwind  0.083614   3064.605657
DE0 35 0 onwind  0.021992   2382.535460
DE0 32 3 onwind  0.000000      0.000000
DE0 35 1 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 1123.5731881447546 MW
Capacity of the last onwind generator adjusted to fit cluster size: 191.69004401187544 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 36 4 onwind  DE0 36      PQ       178.866065        0.0              True
DE0 38 4 onwind  DE0 38      PQ       560.395407        0.0              True
DE0 36 3 onwind  DE0 36      PQ       283.424198        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 36 4 onwind  178.866065  247.914549        NaN       0.0  ...
DE0 38 4 onwind  560.395407  560.395407        NaN       0.0  ...
DE0 36 3 onwind  283.424198  191.690044        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 36 4 onwind               1                 0            NaN
DE0 38 4 onwind               1                 0            NaN
DE0 36 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 36 4 onwind              NaN                  1.0                   1.0
DE0 38 4 onwind              NaN                  1.0                   1.0
DE0 36 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 36 4 onwind    1.0        0.0
DE0 38 4 onwind    1.0        0.0
DE0 36 3 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 36 3 onwind is name
DE0 36 3 onwind    1123.573188
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 30 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 30 0 solar-hsat  0.130131  14860.10007
Remaining top solar-hsat capacity outside the cluster: 13860.100070419467 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 30 0 solar-hsat  DE0 30      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 30 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 30 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 30 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 30 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 30 0 solar-hsat is name
DE0 30 0 solar-hsat    13860.10007
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 30 0 solar      NaN       NaN
DE0 30 1 solar      NaN       NaN
DE0 30 2 solar      NaN       NaN
DE0 30 3 solar      NaN       NaN
DE0 30 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 30 4 solar  0.115726   432.109155
DE0 30 3 solar  0.112189  1121.725184
DE0 30 2 solar  0.109975  7675.785012
DE0 30 1 solar  0.106674  6653.856381
DE0 30 0 solar  0.103364  1224.088684
Remaining top solar capacity outside the cluster: 553.8343384761374 MW
Capacity of the last solar generator adjusted to fit cluster size: 567.8908453907615 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 30 4 solar  DE0 30      PQ       15.148098        0.0              True
DE0 30 3 solar  DE0 30      PQ       26.866855        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 30 4 solar  15.148098  432.109155        NaN       0.0  ...
DE0 30 3 solar  26.866855  567.890845        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 30 4 solar               1                 0            NaN
DE0 30 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 30 4 solar              NaN                  1.0                   1.0
DE0 30 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 30 4 solar    1.0        0.0
DE0 30 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 30 3 solar is name
DE0 30 3 solar    553.834338
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 30 0 onwind      NaN       NaN
DE0 30 1 onwind      NaN       NaN
DE0 30 2 onwind      NaN       NaN
DE0 30 3 onwind      NaN       NaN
DE0 30 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 30 4 onwind  0.250279   413.711153
DE0 30 3 onwind  0.223439   949.376975
DE0 30 2 onwind  0.211128   336.819019
DE0 30 1 onwind  0.182820  4211.798298
DE0 30 0 onwind  0.162146  2274.721159
Remaining top onwind capacity outside the cluster: 363.0881279587227 MW
Capacity of the last onwind generator adjusted to fit cluster size: 586.2888469252925 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 30 4 onwind  DE0 30      PQ       15.067673        0.0              True
DE0 30 3 onwind  DE0 30      PQ       30.868977        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 30 4 onwind  15.067673  413.711153        NaN       0.0  ...
DE0 30 3 onwind  30.868977  586.288847        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 30 4 onwind               1                 0            NaN
DE0 30 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 30 4 onwind              NaN                  1.0                   1.0
DE0 30 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 30 4 onwind    1.0        0.0
DE0 30 3 onwind    1.0        0.0

[2 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DE0 30 3 onwind is name
DE0 30 3 onwind    363.088128
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 31 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 31 0 solar-hsat   0.12535  28665.571604
Remaining top solar-hsat capacity outside the cluster: 27665.57160443552 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 31 0 solar-hsat  DE0 31      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 31 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 31 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 31 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 31 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 31 0 solar-hsat is name
DE0 31 0 solar-hsat    27665.571604
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 31 0 solar      NaN       NaN
DE0 31 1 solar      NaN       NaN
DE0 31 2 solar      NaN       NaN
DE0 31 3 solar      NaN       NaN
DE0 31 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 31 4 solar  0.107341   4779.516814
DE0 31 3 solar  0.106157  16991.073076
DE0 31 2 solar  0.104707   3911.605401
DE0 31 1 solar  0.103502   3975.674945
DE0 31 0 solar  0.101616   3343.126418
Remaining top solar capacity outside the cluster: 3779.516814209138 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 31 4 solar  DE0 31      PQ       129.576128        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 31 4 solar  129.576128     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 31 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 31 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 31 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 31 4 solar is name
DE0 31 4 solar    3779.516814
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 31 0 onwind      NaN       NaN
DE0 31 1 onwind      NaN       NaN
DE0 31 2 onwind      NaN       NaN
DE0 31 3 onwind      NaN       NaN
DE0 31 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 31 4 onwind  0.279388   316.925303
DE0 31 3 onwind  0.265051   765.403698
DE0 31 2 onwind  0.253386  3079.677549
DE0 31 1 onwind  0.245596  5089.733839
DE0 31 0 onwind  0.239540  3667.470527
Remaining top onwind capacity outside the cluster: 82.32900056269978 MW
Capacity of the last onwind generator adjusted to fit cluster size: 683.0746974423325 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 31 4 onwind  DE0 31      PQ       12.885178        0.0              True
DE0 31 3 onwind  DE0 31      PQ       84.521950        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 31 4 onwind  12.885178  316.925303        NaN       0.0  ...
DE0 31 3 onwind  84.521950  683.074697        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 31 4 onwind               1                 0            NaN
DE0 31 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 31 4 onwind              NaN                  1.0                   1.0
DE0 31 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 31 4 onwind    1.0        0.0
DE0 31 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 31 3 onwind is name
DE0 31 3 onwind    82.329001
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 32 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 32 0 solar-hsat   0.13507  22528.29092
Remaining top solar-hsat capacity outside the cluster: 21528.290919933803 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 32 0 solar-hsat  DE0 32      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 32 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 32 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 32 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 32 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 32 0 solar-hsat is name
DE0 32 0 solar-hsat    21528.29092
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 32 0 solar      NaN       NaN
DE0 32 1 solar      NaN       NaN
DE0 32 2 solar      NaN       NaN
DE0 32 3 solar      NaN       NaN
DE0 32 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 32 4 solar  0.118024  1555.460451
DE0 32 3 solar  0.115482  4343.524583
DE0 32 2 solar  0.114870  4205.898832
DE0 32 1 solar  0.111566  7395.881486
DE0 32 0 solar  0.110005  8434.738867
Remaining top solar capacity outside the cluster: 555.4604512531323 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 32 4 solar  DE0 32      PQ       51.882901        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 32 4 solar  51.882901     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 32 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 32 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 32 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 32 4 solar is name
DE0 32 4 solar    555.460451
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 32 0 onwind      NaN       NaN
DE0 32 1 onwind      NaN       NaN
DE0 32 2 onwind      NaN       NaN
DE0 32 3 onwind      NaN       NaN
DE0 32 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 32 4 onwind  0.164297  1785.147118
DE0 32 2 onwind  0.144543  5468.902986
DE0 32 1 onwind  0.138211  2398.662571
DE0 32 0 onwind  0.128685  2072.317675
DE0 32 3 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 785.1471177997821 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 32 4 onwind  DE0 32      PQ       52.680342        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 32 4 onwind  52.680342     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 32 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 32 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 32 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 32 4 onwind is name
DE0 32 4 onwind    785.147118
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 33 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 33 0 solar-hsat  0.124543  25784.001683
Remaining top solar-hsat capacity outside the cluster: 24784.00168270036 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 33 0 solar-hsat  DE0 33      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 33 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 33 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 33 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 33 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 33 0 solar-hsat is name
DE0 33 0 solar-hsat    24784.001683
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 33 0 solar      NaN       NaN
DE0 33 1 solar      NaN       NaN
DE0 33 2 solar      NaN       NaN
DE0 33 3 solar      NaN       NaN
DE0 33 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 33 4 solar  0.108219    529.282507
DE0 33 3 solar  0.106698  13807.859926
DE0 33 2 solar  0.105012   6683.855549
DE0 33 1 solar  0.103557   8661.007644
DE0 33 0 solar  0.102071      1.608048
Remaining top solar capacity outside the cluster: 13337.142433648554 MW
Capacity of the last solar generator adjusted to fit cluster size: 470.71749250079347 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 33 4 solar  DE0 33      PQ        32.434777        0.0              True
DE0 33 3 solar  DE0 33      PQ       398.880356        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 33 4 solar   32.434777  529.282507        NaN       0.0  ...
DE0 33 3 solar  398.880356  470.717493        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 33 4 solar               1                 0            NaN
DE0 33 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 33 4 solar              NaN                  1.0                   1.0
DE0 33 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 33 4 solar    1.0        0.0
DE0 33 3 solar    1.0        0.0

[2 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 33 3 solar is name
DE0 33 3 solar    13337.142434
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 33 0 onwind      NaN       NaN
DE0 33 1 onwind      NaN       NaN
DE0 33 2 onwind      NaN       NaN
DE0 33 3 onwind      NaN       NaN
DE0 33 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 33 4 onwind  0.240776   371.211954
DE0 33 3 onwind  0.226956  1693.316402
DE0 33 2 onwind  0.213093  2465.822382
DE0 33 1 onwind  0.197481  3977.078940
DE0 33 0 onwind  0.184020  5631.876329
Remaining top onwind capacity outside the cluster: 1064.5283561597444 MW
Capacity of the last onwind generator adjusted to fit cluster size: 628.7880457765705 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 33 4 onwind  DE0 33      PQ       257.006479        0.0              True
DE0 33 3 onwind  DE0 33      PQ       137.924760        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 33 4 onwind  257.006479  371.211954        NaN       0.0  ...
DE0 33 3 onwind  137.924760  628.788046        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 33 4 onwind               1                 0            NaN
DE0 33 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 33 4 onwind              NaN                  1.0                   1.0
DE0 33 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 33 4 onwind    1.0        0.0
DE0 33 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 33 3 onwind is name
DE0 33 3 onwind    1064.528356
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 34 0 solar-hsat      NaN       NaN
                     p_max_pu  p_nom_max
name
DE0 34 0 solar-hsat  0.130735  25070.679
Remaining top solar-hsat capacity outside the cluster: 24070.67900031461 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 34 0 solar-hsat  DE0 34      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 34 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 34 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 34 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 34 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 34 0 solar-hsat is name
DE0 34 0 solar-hsat    24070.679
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 34 0 solar      NaN       NaN
DE0 34 1 solar      NaN       NaN
DE0 34 2 solar      NaN       NaN
DE0 34 3 solar      NaN       NaN
DE0 34 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 34 4 solar  0.112078   2141.816572
DE0 34 3 solar  0.110674   5996.382460
DE0 34 2 solar  0.109068  10988.556029
DE0 34 1 solar  0.107781   9735.288397
DE0 34 0 solar  0.105611      0.363517
Remaining top solar capacity outside the cluster: 1141.8165721071514 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 34 4 solar  DE0 34      PQ       92.474308        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 34 4 solar  92.474308     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 34 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 34 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 34 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 34 4 solar is name
DE0 34 4 solar    1141.816572
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 34 0 onwind      NaN       NaN
DE0 34 1 onwind      NaN       NaN
DE0 34 2 onwind      NaN       NaN
DE0 34 3 onwind      NaN       NaN
DE0 34 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 34 4 onwind  0.370175   738.423218
DE0 34 3 onwind  0.332121     0.155479
DE0 34 2 onwind  0.289837  2570.680598
DE0 34 1 onwind  0.256510  4884.972313
DE0 34 0 onwind  0.219629  6403.513332
Remaining top onwind capacity outside the cluster: 2309.2592945772 MW
Capacity of the last onwind generator adjusted to fit cluster size: 261.42130302962926 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 34 4 onwind  DE0 34      PQ        63.777498        0.0              True
DE0 34 3 onwind  DE0 34      PQ         0.000000        0.0              True
DE0 34 2 onwind  DE0 34      PQ       187.424287        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 34 4 onwind   63.777498  738.423218        NaN       0.0  ...
DE0 34 3 onwind    0.000000    0.155479        NaN       0.0  ...
DE0 34 2 onwind  187.424287  261.421303        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 34 4 onwind               1                 0            NaN
DE0 34 3 onwind               1                 0            NaN
DE0 34 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 34 4 onwind              NaN                  1.0                   1.0
DE0 34 3 onwind              NaN                  1.0                   1.0
DE0 34 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 34 4 onwind    1.0        0.0
DE0 34 3 onwind    1.0        0.0
DE0 34 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 34 2 onwind is name
DE0 34 2 onwind    2309.259295
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 35 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 35 0 solar-hsat  0.137188  33034.327527
Remaining top solar-hsat capacity outside the cluster: 32034.327526890032 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 35 0 solar-hsat  DE0 35      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 35 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 35 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 35 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 35 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 35 0 solar-hsat is name
DE0 35 0 solar-hsat    32034.327527
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 35 0 solar      NaN       NaN
DE0 35 1 solar      NaN       NaN
DE0 35 2 solar      NaN       NaN
DE0 35 3 solar      NaN       NaN
DE0 35 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 35 4 solar  0.124605   1647.623633
DE0 35 2 solar  0.116192  10238.448129
DE0 35 1 solar  0.114319  22120.257530
DE0 35 0 solar  0.110900   4175.402173
DE0 35 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 647.623632516521 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 35 4 solar  DE0 35      PQ       59.473559        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 35 4 solar  59.473559     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 35 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 35 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 35 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 35 4 solar is name
DE0 35 4 solar    647.623633
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 35 0 onwind      NaN       NaN
DE0 35 1 onwind      NaN       NaN
DE0 35 2 onwind      NaN       NaN
DE0 35 3 onwind      NaN       NaN
DE0 35 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 35 4 onwind  0.125175  11947.163702
DE0 35 3 onwind  0.108537   4030.300185
DE0 35 2 onwind  0.083614   3064.605657
DE0 35 0 onwind  0.021992   2382.535460
DE0 35 1 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 10947.163701766458 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 35 4 onwind  DE0 35      PQ       307.624388        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 35 4 onwind  307.624388     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 35 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 35 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 35 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 35 4 onwind is name
DE0 35 4 onwind    10947.163702
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 36 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 36 0 solar-hsat  0.131633  19947.236621
Remaining top solar-hsat capacity outside the cluster: 18947.23662081446 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 36 0 solar-hsat  DE0 36      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 36 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 36 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 36 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 36 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 36 0 solar-hsat is name
DE0 36 0 solar-hsat    18947.236621
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 36 0 solar      NaN       NaN
DE0 36 1 solar      NaN       NaN
DE0 36 2 solar      NaN       NaN
DE0 36 3 solar      NaN       NaN
DE0 36 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 36 4 solar  0.116719    592.257046
DE0 36 3 solar  0.113920   2769.099133
DE0 36 2 solar  0.111342   1973.014070
DE0 36 1 solar  0.108480  15557.236460
DE0 36 0 solar  0.106819   2072.480597
Remaining top solar capacity outside the cluster: 2361.356179290339 MW
Capacity of the last solar generator adjusted to fit cluster size: 407.74295350670434 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 36 4 solar  DE0 36      PQ       12.231413        0.0              True
DE0 36 3 solar  DE0 36      PQ       96.916349        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 36 4 solar  12.231413  592.257046        NaN       0.0  ...
DE0 36 3 solar  96.916349  407.742954        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 36 4 solar               1                 0            NaN
DE0 36 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 36 4 solar              NaN                  1.0                   1.0
DE0 36 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 36 4 solar    1.0        0.0
DE0 36 3 solar    1.0        0.0

[2 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 36 3 solar is name
DE0 36 3 solar    2361.356179
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 36 0 onwind      NaN       NaN
DE0 36 1 onwind      NaN       NaN
DE0 36 2 onwind      NaN       NaN
DE0 36 3 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 36 3 onwind  0.456766  1123.573188
DE0 36 2 onwind  0.383916  2141.799114
DE0 36 1 onwind  0.326594  3204.488595
DE0 36 0 onwind  0.274365  2539.492764
Remaining top onwind capacity outside the cluster: 123.57318814475457 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 36 3 onwind  DE0 36      PQ       283.424198        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 36 3 onwind  283.424198     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 36 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 36 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 36 3 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 36 3 onwind is name
DE0 36 3 onwind    123.573188
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 37 0 solar-hsat      NaN       NaN
                     p_max_pu    p_nom_max
name
DE0 37 0 solar-hsat  0.132704  9713.266757
Remaining top solar-hsat capacity outside the cluster: 8713.266756883077 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 37 0 solar-hsat  DE0 37      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 37 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 37 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 37 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 37 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 37 0 solar-hsat is name
DE0 37 0 solar-hsat    8713.266757
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 37 0 solar      NaN       NaN
DE0 37 1 solar      NaN       NaN
DE0 37 2 solar      NaN       NaN
DE0 37 3 solar      NaN       NaN
DE0 37 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 37 4 solar  0.115908     1.574972
DE0 37 3 solar  0.114057   136.032616
DE0 37 2 solar  0.111853   239.930802
DE0 37 1 solar  0.110637  6434.334523
DE0 37 0 solar  0.109835  4370.443219
Remaining top solar capacity outside the cluster: 5811.872912160105 MW
Capacity of the last solar generator adjusted to fit cluster size: 622.4616104740969 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 37 4 solar  DE0 37      PQ         0.000000        0.0              True
DE0 37 3 solar  DE0 37      PQ         2.745290        0.0              True
DE0 37 2 solar  DE0 37      PQ         4.748528        0.0              True
DE0 37 1 solar  DE0 37      PQ       375.758562        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 37 4 solar    0.000000    1.574972        NaN       0.0  ...
DE0 37 3 solar    2.745290  136.032616        NaN       0.0  ...
DE0 37 2 solar    4.748528  239.930802        NaN       0.0  ...
DE0 37 1 solar  375.758562  622.461610        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 37 4 solar               1                 0            NaN
DE0 37 3 solar               1                 0            NaN
DE0 37 2 solar               1                 0            NaN
DE0 37 1 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 37 4 solar              NaN                  1.0                   1.0
DE0 37 3 solar              NaN                  1.0                   1.0
DE0 37 2 solar              NaN                  1.0                   1.0
DE0 37 1 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 37 4 solar    1.0        0.0
DE0 37 3 solar    1.0        0.0
DE0 37 2 solar    1.0        0.0
DE0 37 1 solar    1.0        0.0

[4 rows x 40 columns]
Residual capacity of generator DE0 37 1 solar is name
DE0 37 1 solar    5811.872912
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 37 0 onwind      NaN       NaN
DE0 37 1 onwind      NaN       NaN
DE0 37 2 onwind      NaN       NaN
DE0 37 3 onwind      NaN       NaN
DE0 37 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 37 4 onwind  0.198920  2071.036381
DE0 37 3 onwind  0.188423  2056.862963
DE0 37 2 onwind  0.176375   619.322488
DE0 37 1 onwind  0.163033   383.778696
DE0 37 0 onwind  0.139928     1.468006
Remaining top onwind capacity outside the cluster: 1071.036380926103 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 37 4 onwind  DE0 37      PQ       302.950251        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 37 4 onwind  302.950251     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 37 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 37 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 37 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 37 4 onwind is name
DE0 37 4 onwind    1071.036381
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 38 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 38 0 solar-hsat  0.125511  18681.009611
Remaining top solar-hsat capacity outside the cluster: 17681.009611377383 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 38 0 solar-hsat  DE0 38      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 38 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 38 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 38 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 38 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DE0 38 0 solar-hsat is name
DE0 38 0 solar-hsat    17681.009611
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 38 0 solar      NaN       NaN
DE0 38 1 solar      NaN       NaN
DE0 38 2 solar      NaN       NaN
DE0 38 3 solar      NaN       NaN
DE0 38 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 38 4 solar  0.109023   641.810720
DE0 38 3 solar  0.107785  2840.419248
DE0 38 2 solar  0.106100  3850.375560
DE0 38 1 solar  0.105047  9918.938655
DE0 38 0 solar  0.104367  4254.809996
Remaining top solar capacity outside the cluster: 2482.229968899888 MW
Capacity of the last solar generator adjusted to fit cluster size: 358.1892795372545 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 38 4 solar  DE0 38      PQ       20.380769        0.0              True
DE0 38 3 solar  DE0 38      PQ       69.570581        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 38 4 solar  20.380769  641.81072        NaN       0.0  ...
DE0 38 3 solar  69.570581  358.18928        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 38 4 solar               1                 0            NaN
DE0 38 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 38 4 solar              NaN                  1.0                   1.0
DE0 38 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 38 4 solar    1.0        0.0
DE0 38 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 38 3 solar is name
DE0 38 3 solar    2482.229969
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 38 0 onwind      NaN       NaN
DE0 38 1 onwind      NaN       NaN
DE0 38 2 onwind      NaN       NaN
DE0 38 3 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 38 3 onwind  0.422406    26.348205
DE0 38 2 onwind  0.374493   515.341583
DE0 38 1 onwind  0.319016  2038.571064
DE0 38 0 onwind  0.279388  5437.286893
Remaining top onwind capacity outside the cluster: 1580.2608521396942 MW
Capacity of the last onwind generator adjusted to fit cluster size: 458.31021216400177 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 38 3 onwind  DE0 38      PQ        26.348205        0.0              True
DE0 38 2 onwind  DE0 38      PQ       210.084359        0.0              True
DE0 38 1 onwind  DE0 38      PQ       824.637601        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 38 3 onwind   26.348205   26.348205        NaN       0.0  ...
DE0 38 2 onwind  210.084359  515.341583        NaN       0.0  ...
DE0 38 1 onwind  824.637601  458.310212        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 38 3 onwind               1                 0            NaN
DE0 38 2 onwind               1                 0            NaN
DE0 38 1 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 38 3 onwind              NaN                  1.0                   1.0
DE0 38 2 onwind              NaN                  1.0                   1.0
DE0 38 1 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 38 3 onwind    1.0        0.0
DE0 38 2 onwind    1.0        0.0
DE0 38 1 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator DE0 38 1 onwind is name
DE0 38 1 onwind    1580.260852
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 39 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 39 0 solar-hsat  0.129064  23214.345235
Remaining top solar-hsat capacity outside the cluster: 22214.345234678964 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 39 0 solar-hsat  DE0 39      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 39 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 39 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 39 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 39 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DE0 39 0 solar-hsat is name
DE0 39 0 solar-hsat    22214.345235
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 39 0 solar      NaN       NaN
DE0 39 1 solar      NaN       NaN
DE0 39 2 solar      NaN       NaN
DE0 39 3 solar      NaN       NaN
DE0 39 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 39 4 solar  0.109936   2958.136487
DE0 39 3 solar  0.108356  18869.485137
DE0 39 2 solar  0.107047   3523.148937
DE0 39 1 solar  0.105086   1374.261925
DE0 39 0 solar  0.102900      0.285956
Remaining top solar capacity outside the cluster: 1958.1364873759903 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 39 4 solar  DE0 39      PQ       93.141533        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 39 4 solar  93.141533     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 39 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 39 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 39 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 39 4 solar is name
DE0 39 4 solar    1958.136487
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 39 0 onwind      NaN       NaN
DE0 39 1 onwind      NaN       NaN
DE0 39 2 onwind      NaN       NaN
DE0 39 3 onwind      NaN       NaN
DE0 39 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 39 4 onwind  0.229010   923.285488
DE0 39 3 onwind  0.222259  1989.145999
DE0 39 2 onwind  0.215506  3052.418066
DE0 39 1 onwind  0.205182  6363.999223
DE0 39 0 onwind  0.195859   394.482233
Remaining top onwind capacity outside the cluster: 1912.4314867246107 MW
Capacity of the last onwind generator adjusted to fit cluster size: 76.71451202558274 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 39 4 onwind  DE0 39      PQ        42.769211        0.0              True
DE0 39 3 onwind  DE0 39      PQ       251.335548        0.0              True

                  p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                          ...
DE0 39 4 onwind   42.769211  923.285488        NaN       0.0  ...
DE0 39 3 onwind  251.335548   76.714512        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 39 4 onwind               1                 0            NaN
DE0 39 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 39 4 onwind              NaN                  1.0                   1.0
DE0 39 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 39 4 onwind    1.0        0.0
DE0 39 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 39 3 onwind is name
DE0 39 3 onwind    1912.431487
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 4 0 solar-hsat       NaN       NaN
DE0 40 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 40 0 solar-hsat  0.126965  28509.943055
DE0 4 0 solar-hsat   0.126022  30727.611731
Remaining top solar-hsat capacity outside the cluster: 27509.943054908494 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 40 0 solar-hsat  DE0 40      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 40 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 40 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 40 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 40 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 40 0 solar-hsat is name
DE0 40 0 solar-hsat    27509.943055
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 4 0 solar       NaN       NaN
DE0 4 1 solar       NaN       NaN
DE0 4 2 solar       NaN       NaN
DE0 4 3 solar       NaN       NaN
DE0 4 4 solar       NaN       NaN
DE0 40 0 solar      NaN       NaN
DE0 40 1 solar      NaN       NaN
DE0 40 2 solar      NaN       NaN
DE0 40 3 solar      NaN       NaN
DE0 40 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 40 4 solar  0.109428  10897.559841
DE0 4 4 solar   0.107961   3070.088381
DE0 40 3 solar  0.107885   5947.668884
DE0 4 3 solar   0.106860   7147.037624
DE0 4 2 solar   0.106084  13969.007724
DE0 40 2 solar  0.105953  13814.324667
DE0 4 1 solar   0.104694  11136.792466
DE0 4 0 solar   0.103920     51.976702
DE0 40 0 solar  0.102493   2162.277213
DE0 40 1 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 9897.559840927068 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type        p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 40 4 solar  DE0 40      PQ       1058.500064        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 40 4 solar  1058.500064     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 40 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 40 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 40 4 solar    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 40 4 solar is name
DE0 40 4 solar    9897.559841
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 4 0 onwind       NaN       NaN
DE0 4 1 onwind       NaN       NaN
DE0 4 2 onwind       NaN       NaN
DE0 4 3 onwind       NaN       NaN
DE0 4 4 onwind       NaN       NaN
DE0 40 0 onwind      NaN       NaN
DE0 40 1 onwind      NaN       NaN
DE0 40 2 onwind      NaN       NaN
DE0 40 3 onwind      NaN       NaN
DE0 40 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
DE0 4 4 onwind   0.378937    307.112622
DE0 4 2 onwind   0.296694    814.814683
DE0 4 1 onwind   0.262338   1104.306168
DE0 4 0 onwind   0.241109  12221.764152
DE0 40 4 onwind  0.209295   1568.216247
DE0 40 3 onwind  0.197272   5109.163905
DE0 40 2 onwind  0.180013    967.634808
DE0 40 1 onwind  0.170142    298.703044
DE0 40 0 onwind  0.155028    409.338087
DE0 4 3 onwind   0.000000      0.000000
Remaining top onwind capacity outside the cluster: 121.92730494554235 MW
Capacity of the last onwind generator adjusted to fit cluster size: 692.8873781035729 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 4 4 onwind  DE0 4      PQ        77.935159        0.0              True
DE0 4 2 onwind  DE0 4      PQ       129.179733        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 4 4 onwind   77.935159  307.112622        NaN       0.0  ...
DE0 4 2 onwind  129.179733  692.887378        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 4 4 onwind               1                 0            NaN
DE0 4 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 4 4 onwind              NaN                  1.0                   1.0
DE0 4 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 4 4 onwind    1.0        0.0
DE0 4 2 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 4 2 onwind is name
DE0 4 2 onwind    121.927305
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
DE0 40 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
DE0 40 0 solar-hsat  0.126965  27509.943055
Remaining top solar-hsat capacity outside the cluster: 26509.943054908494 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 40 0 solar-hsat  DE0 40      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
DE0 40 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
DE0 40 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
DE0 40 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 40 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 40 0 solar-hsat is name
DE0 40 0 solar-hsat    26509.943055
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 40 0 solar      NaN       NaN
DE0 40 1 solar      NaN       NaN
DE0 40 2 solar      NaN       NaN
DE0 40 3 solar      NaN       NaN
DE0 40 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
DE0 40 4 solar  0.109428   9897.559841
DE0 40 3 solar  0.107885   5947.668884
DE0 40 2 solar  0.105953  13814.324667
DE0 40 0 solar  0.102493   2162.277213
DE0 40 1 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 8897.559840927068 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type        p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 40 4 solar  DE0 40      PQ       1058.500064        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 40 4 solar  1058.500064     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 40 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 40 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 40 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 40 4 solar is name
DE0 40 4 solar    8897.559841
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
DE0 40 0 onwind      NaN       NaN
DE0 40 1 onwind      NaN       NaN
DE0 40 2 onwind      NaN       NaN
DE0 40 3 onwind      NaN       NaN
DE0 40 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
DE0 40 4 onwind  0.209295  1568.216247
DE0 40 3 onwind  0.197272  5109.163905
DE0 40 2 onwind  0.180013   967.634808
DE0 40 1 onwind  0.170142   298.703044
DE0 40 0 onwind  0.155028   409.338087
Remaining top onwind capacity outside the cluster: 568.2162466129603 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 40 4 onwind  DE0 40      PQ       125.762859        0.0              True

                  p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 40 4 onwind  125.762859     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
DE0 40 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 40 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
DE0 40 4 onwind    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DE0 40 4 onwind is name
DE0 40 4 onwind    568.216247
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DE0 5 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 5 0 solar-hsat  0.138484  22184.985999
Remaining top solar-hsat capacity outside the cluster: 21184.985999113793 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 5 0 solar-hsat  DE0 5      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 5 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 5 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 5 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 5 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 5 0 solar-hsat is name
DE0 5 0 solar-hsat    21184.985999
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 5 0 solar      NaN       NaN
DE0 5 1 solar      NaN       NaN
DE0 5 2 solar      NaN       NaN
DE0 5 3 solar      NaN       NaN
DE0 5 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DE0 5 4 solar  0.135549    269.387441
DE0 5 2 solar  0.122617   2666.899188
DE0 5 1 solar  0.116355  14223.244145
DE0 5 0 solar  0.112528   8380.746561
DE0 5 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 1936.286629283804 MW
Capacity of the last solar generator adjusted to fit cluster size: 730.6125590899995 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 5 4 solar  DE0 5      PQ         7.660959        0.0              True
DE0 5 2 solar  DE0 5      PQ       102.760423        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 5 4 solar    7.660959  269.387441        NaN       0.0  ...
DE0 5 2 solar  102.760423  730.612559        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DE0 5 4 solar               1                 0            NaN
DE0 5 2 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 5 4 solar              NaN                  1.0                   1.0
DE0 5 2 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DE0 5 4 solar    1.0        0.0
DE0 5 2 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 5 2 solar is name
DE0 5 2 solar    1936.286629
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 5 0 onwind      NaN       NaN
DE0 5 1 onwind      NaN       NaN
DE0 5 2 onwind      NaN       NaN
DE0 5 3 onwind      NaN       NaN
DE0 5 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 5 4 onwind  0.129818  7912.309427
DE0 5 3 onwind  0.102898  1696.046894
DE0 5 0 onwind  0.027646  3205.352970
DE0 5 2 onwind  0.000000     0.000000
DE0 5 1 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 6912.309427341088 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 5 4 onwind  DE0 5      PQ       175.473543        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 5 4 onwind  175.473543     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 5 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 5 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 5 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 5 4 onwind is name
DE0 5 4 onwind    6912.309427
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DE0 6 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 6 0 solar-hsat  0.126544  19745.484371
Remaining top solar-hsat capacity outside the cluster: 18745.484371387513 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 6 0 solar-hsat  DE0 6      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 6 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 6 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 6 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 6 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 6 0 solar-hsat is name
DE0 6 0 solar-hsat    18745.484371
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 6 0 solar      NaN       NaN
DE0 6 1 solar      NaN       NaN
DE0 6 2 solar      NaN       NaN
DE0 6 3 solar      NaN       NaN
DE0 6 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
DE0 6 4 solar  0.109637  2904.590771
DE0 6 3 solar  0.108033  5655.269271
DE0 6 2 solar  0.106831  6296.445255
DE0 6 1 solar  0.105330  4909.841626
DE0 6 0 solar  0.103820  2965.674815
Remaining top solar capacity outside the cluster: 1904.590770522917 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 6 4 solar  DE0 6      PQ       209.046156        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 6 4 solar  209.046156     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DE0 6 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 6 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DE0 6 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 6 4 solar is name
DE0 6 4 solar    1904.590771
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 6 0 onwind      NaN       NaN
DE0 6 1 onwind      NaN       NaN
DE0 6 2 onwind      NaN       NaN
DE0 6 3 onwind      NaN       NaN
DE0 6 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 6 4 onwind  0.214753  2572.692383
DE0 6 3 onwind  0.197631  4244.247590
DE0 6 1 onwind  0.155218   114.717894
DE0 6 0 onwind  0.125703   273.454764
DE0 6 2 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 1572.6923828119552 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 6 4 onwind  DE0 6      PQ       199.399292        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 6 4 onwind  199.399292     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 6 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 6 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 6 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 6 4 onwind is name
DE0 6 4 onwind    1572.692383
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DE0 7 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 7 0 solar-hsat  0.125376  22106.098238
Remaining top solar-hsat capacity outside the cluster: 21106.098238384402 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 7 0 solar-hsat  DE0 7      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 7 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 7 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 7 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 7 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 7 0 solar-hsat is name
DE0 7 0 solar-hsat    21106.098238
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 7 0 solar      NaN       NaN
DE0 7 1 solar      NaN       NaN
DE0 7 2 solar      NaN       NaN
DE0 7 3 solar      NaN       NaN
DE0 7 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
DE0 7 4 solar  0.108368  2915.988785
DE0 7 3 solar  0.106522  9994.095968
DE0 7 2 solar  0.104988  7550.381308
DE0 7 1 solar  0.103599  2433.633583
DE0 7 0 solar  0.102103  2555.358825
Remaining top solar capacity outside the cluster: 1915.9887846152042 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 7 4 solar  DE0 7      PQ       88.312908        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
DE0 7 4 solar  88.312908     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
DE0 7 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
DE0 7 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
DE0 7 4 solar

[1 rows x 40 columns]
Residual capacity of generator DE0 7 4 solar is name
DE0 7 4 solar    1915.988785
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 7 0 onwind      NaN       NaN
DE0 7 1 onwind      NaN       NaN
DE0 7 2 onwind      NaN       NaN
DE0 7 3 onwind      NaN       NaN
DE0 7 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 7 4 onwind  0.284846   483.733610
DE0 7 3 onwind  0.264048   277.378571
DE0 7 2 onwind  0.254691  1753.440865
DE0 7 1 onwind  0.242386  5227.845326
DE0 7 0 onwind  0.220866   352.068646
Remaining top onwind capacity outside the cluster: 1514.5530459973415 MW
Capacity of the last onwind generator adjusted to fit cluster size: 238.8878188327368 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 7 4 onwind  DE0 7      PQ        20.051239        0.0              True
DE0 7 3 onwind  DE0 7      PQ        10.658127        0.0              True
DE0 7 2 onwind  DE0 7      PQ       149.987414        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
DE0 7 4 onwind   20.051239  483.733610        NaN       0.0  ...
DE0 7 3 onwind   10.658127  277.378571        NaN       0.0  ...
DE0 7 2 onwind  149.987414  238.887819        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 7 4 onwind               1                 0            NaN
DE0 7 3 onwind               1                 0            NaN
DE0 7 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 7 4 onwind              NaN                  1.0                   1.0
DE0 7 3 onwind              NaN                  1.0                   1.0
DE0 7 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 7 4 onwind    1.0        0.0
DE0 7 3 onwind    1.0        0.0
DE0 7 2 onwind    1.0        0.0

[3 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DE0 7 2 onwind is name
DE0 7 2 onwind    1514.553046
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DE0 8 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 8 0 solar-hsat  0.135369  21715.310239
Remaining top solar-hsat capacity outside the cluster: 20715.310238688777 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 8 0 solar-hsat  DE0 8      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 8 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 8 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 8 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 8 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 8 0 solar-hsat is name
DE0 8 0 solar-hsat    20715.310239
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 8 0 solar      NaN       NaN
DE0 8 1 solar      NaN       NaN
DE0 8 2 solar      NaN       NaN
DE0 8 3 solar      NaN       NaN
DE0 8 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DE0 8 4 solar  0.116603      6.828806
DE0 8 3 solar  0.114015  10273.903544
DE0 8 2 solar  0.112791  10619.232237
DE0 8 1 solar  0.111124   1991.457504
DE0 8 0 solar  0.109657   2108.145001
Remaining top solar capacity outside the cluster: 9280.732350640053 MW
Capacity of the last solar generator adjusted to fit cluster size: 993.1711937287791 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 8 4 solar  DE0 8      PQ         0.14089        0.0              True
DE0 8 3 solar  DE0 8      PQ       781.06209        0.0              True

               p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DE0 8 4 solar    0.14089    6.828806        NaN       0.0  ...
DE0 8 3 solar  781.06209  993.171194        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DE0 8 4 solar               1                 0            NaN
DE0 8 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 8 4 solar              NaN                  1.0                   1.0
DE0 8 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DE0 8 4 solar    1.0        0.0
DE0 8 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 8 3 solar is name
DE0 8 3 solar    9280.732351
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 8 0 onwind      NaN       NaN
DE0 8 1 onwind      NaN       NaN
DE0 8 2 onwind      NaN       NaN
DE0 8 3 onwind      NaN       NaN
DE0 8 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 8 4 onwind  0.518976   100.173806
DE0 8 3 onwind  0.413123   203.198240
DE0 8 2 onwind  0.408112   155.363021
DE0 8 1 onwind  0.328128  1185.453775
DE0 8 0 onwind  0.257909  9365.544245
Remaining top onwind capacity outside the cluster: 644.1888416128268 MW
Capacity of the last onwind generator adjusted to fit cluster size: 541.2649330472924 MW
                  bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 8 4 onwind  DE0 8      PQ        7.565311        0.0              True
DE0 8 3 onwind  DE0 8      PQ       12.215871        0.0              True
DE0 8 2 onwind  DE0 8      PQ        9.226832        0.0              True
DE0 8 1 onwind  DE0 8      PQ       56.604763        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 8 4 onwind   7.565311  100.173806        NaN       0.0  ...
DE0 8 3 onwind  12.215871  203.198240        NaN       0.0  ...
DE0 8 2 onwind   9.226832  155.363021        NaN       0.0  ...
DE0 8 1 onwind  56.604763  541.264933        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 8 4 onwind               1                 0            NaN
DE0 8 3 onwind               1                 0            NaN
DE0 8 2 onwind               1                 0            NaN
DE0 8 1 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 8 4 onwind              NaN                  1.0                   1.0
DE0 8 3 onwind              NaN                  1.0                   1.0
DE0 8 2 onwind              NaN                  1.0                   1.0
DE0 8 1 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 8 4 onwind    1.0        0.0
DE0 8 3 onwind    1.0        0.0
DE0 8 2 onwind    1.0        0.0
DE0 8 1 onwind    1.0        0.0

[4 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DE0 8 1 onwind is name
DE0 8 1 onwind    644.188842
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DE0 9 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DE0 9 0 solar-hsat  0.127164  28632.128099
Remaining top solar-hsat capacity outside the cluster: 27632.12809928508 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 9 0 solar-hsat  DE0 9      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DE0 9 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DE0 9 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DE0 9 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 9 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 9 0 solar-hsat is name
DE0 9 0 solar-hsat    27632.128099
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DE0 9 0 solar      NaN       NaN
DE0 9 1 solar      NaN       NaN
DE0 9 2 solar      NaN       NaN
DE0 9 3 solar      NaN       NaN
DE0 9 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DE0 9 4 solar  0.108675     95.737377
DE0 9 3 solar  0.107508   5039.828413
DE0 9 2 solar  0.106309  12257.244891
DE0 9 1 solar  0.105385  13550.953846
DE0 9 0 solar  0.104054   2018.730576
Remaining top solar capacity outside the cluster: 4135.565790788996 MW
Capacity of the last solar generator adjusted to fit cluster size: 904.262622541814 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 9 4 solar  DE0 9      PQ         1.840913        0.0              True
DE0 9 3 solar  DE0 9      PQ       104.969360        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 9 4 solar    1.840913   95.737377        NaN       0.0  ...
DE0 9 3 solar  104.969360  904.262623        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DE0 9 4 solar               1                 0            NaN
DE0 9 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 9 4 solar              NaN                  1.0                   1.0
DE0 9 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DE0 9 4 solar    1.0        0.0
DE0 9 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator DE0 9 3 solar is name
DE0 9 3 solar    4135.565791
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DE0 9 0 onwind      NaN       NaN
DE0 9 1 onwind      NaN       NaN
DE0 9 2 onwind      NaN       NaN
DE0 9 3 onwind      NaN       NaN
DE0 9 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DE0 9 4 onwind  0.276434  1182.255776
DE0 9 3 onwind  0.263294  2114.261791
DE0 9 2 onwind  0.249580  5748.889031
DE0 9 1 onwind  0.235493  4851.006329
DE0 9 0 onwind  0.225648   925.593289
Remaining top onwind capacity outside the cluster: 182.25577576614955 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DE0 9 4 onwind  DE0 9      PQ       245.558473        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DE0 9 4 onwind  245.558473     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DE0 9 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DE0 9 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DE0 9 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DE0 9 4 onwind is name
DE0 9 4 onwind    182.255776
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DK0 0 0 solar-hsat      NaN       NaN
                    p_max_pu      p_nom_max
name
DK0 0 0 solar-hsat  0.132802  105728.626454
Remaining top solar-hsat capacity outside the cluster: 104728.62645358976 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DK0 0 0 solar-hsat  DK0 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DK0 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DK0 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DK0 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DK0 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator DK0 0 0 solar-hsat is name
DK0 0 0 solar-hsat    104728.626454
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DK0 0 0 solar      NaN       NaN
DK0 0 1 solar      NaN       NaN
DK0 0 2 solar      NaN       NaN
DK0 0 3 solar      NaN       NaN
DK0 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DK0 0 4 solar  0.120608    165.931050
DK0 0 3 solar  0.116260  13641.644792
DK0 0 2 solar  0.113135  31517.012111
DK0 0 1 solar  0.109636  44305.424993
DK0 0 0 solar  0.106464  32089.173266
Remaining top solar capacity outside the cluster: 12807.575841255106 MW
Capacity of the last solar generator adjusted to fit cluster size: 834.0689504498442 MW
                 bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DK0 0 4 solar  DK0 0      PQ         7.0        0.0              True
DK0 0 3 solar  DK0 0      PQ        73.5        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
DK0 0 4 solar        7.0  165.93105        NaN       0.0  ...               1
DK0 0 3 solar       73.5  834.06895        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
DK0 0 4 solar                 0            NaN              NaN
DK0 0 3 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
DK0 0 4 solar                  1.0                   1.0    1.0        0.0
DK0 0 3 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
DK0 0 4 solar
DK0 0 3 solar

[2 rows x 40 columns]
Residual capacity of generator DK0 0 3 solar is name
DK0 0 3 solar    12807.575841
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DK0 0 0 onwind      NaN       NaN
DK0 0 1 onwind      NaN       NaN
DK0 0 2 onwind      NaN       NaN
DK0 0 3 onwind      NaN       NaN
DK0 0 4 onwind      NaN       NaN
                p_max_pu     p_nom_max
name
DK0 0 4 onwind  0.544274   1229.646254
DK0 0 3 onwind  0.501268   5834.156139
DK0 0 2 onwind  0.460665   7662.128878
DK0 0 1 onwind  0.404136  20952.059145
DK0 0 0 onwind  0.353729  28851.047789
Remaining top onwind capacity outside the cluster: 229.6462538374194 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DK0 0 4 onwind  DK0 0      PQ       145.033288        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DK0 0 4 onwind  145.033288     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DK0 0 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DK0 0 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DK0 0 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DK0 0 4 onwind is name
DK0 0 4 onwind    229.646254
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
DK1 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
DK1 0 0 solar-hsat  0.140695  32991.910938
Remaining top solar-hsat capacity outside the cluster: 31991.910937692788 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DK1 0 0 solar-hsat  DK1 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
DK1 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
DK1 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
DK1 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DK1 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DK1 0 0 solar-hsat is name
DK1 0 0 solar-hsat    31991.910938
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
DK1 0 0 solar      NaN       NaN
DK1 0 1 solar      NaN       NaN
DK1 0 2 solar      NaN       NaN
DK1 0 3 solar      NaN       NaN
DK1 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
DK1 0 4 solar  0.119480    971.684185
DK1 0 3 solar  0.118694   2552.206004
DK1 0 2 solar  0.117057  11338.337567
DK1 0 1 solar  0.115724  18413.622436
DK1 0 0 solar  0.114822   4705.807999
Remaining top solar capacity outside the cluster: 2523.8901881084403 MW
Capacity of the last solar generator adjusted to fit cluster size: 28.315815469943686 MW
                 bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
DK1 0 4 solar  DK1 0      PQ         0.0        0.0              True
DK1 0 3 solar  DK1 0      PQ        15.0        0.0              True

               p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
DK1 0 4 solar        0.0  971.684185        NaN       0.0  ...
DK1 0 3 solar       15.0   28.315815        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
DK1 0 4 solar               1                 0            NaN
DK1 0 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DK1 0 4 solar              NaN                  1.0                   1.0
DK1 0 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
DK1 0 4 solar    1.0        0.0
DK1 0 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator DK1 0 3 solar is name
DK1 0 3 solar    2523.890188
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
DK1 0 0 onwind      NaN       NaN
DK1 0 1 onwind      NaN       NaN
DK1 0 2 onwind      NaN       NaN
DK1 0 3 onwind      NaN       NaN
DK1 0 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
DK1 0 4 onwind  0.554239  1955.587625
DK1 0 3 onwind  0.506822  3824.336717
DK1 0 2 onwind  0.448945  4037.588071
DK1 0 1 onwind  0.410101  2538.477588
DK1 0 0 onwind  0.369557  3679.787961
Remaining top onwind capacity outside the cluster: 955.5876248208028 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
DK1 0 4 onwind  DK1 0      PQ       169.691698        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
DK1 0 4 onwind  169.691698     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
DK1 0 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
DK1 0 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
DK1 0 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator DK1 0 4 onwind is name
DK1 0 4 onwind    955.587625
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 0 0 solar-hsat   0.13111  28697.540482
Remaining top solar-hsat capacity outside the cluster: 27697.54048231693 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 0 0 solar-hsat  GB2 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 0 0 solar-hsat is name
GB2 0 0 solar-hsat    27697.540482
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 0 0 solar      NaN       NaN
GB2 0 1 solar      NaN       NaN
GB2 0 2 solar      NaN       NaN
GB2 0 3 solar      NaN       NaN
GB2 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB2 0 4 solar  0.119843   1497.156762
GB2 0 2 solar  0.113409   7903.795022
GB2 0 1 solar  0.110629   4054.361134
GB2 0 0 solar  0.107931  19582.487637
GB2 0 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 497.156762444082 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 0 4 solar  GB2 0      PQ       17.264794        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
GB2 0 4 solar  17.264794     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
GB2 0 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
GB2 0 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
GB2 0 4 solar

[1 rows x 40 columns]
Residual capacity of generator GB2 0 4 solar is name
GB2 0 4 solar    497.156762
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 0 0 onwind      NaN       NaN
GB2 0 1 onwind      NaN       NaN
GB2 0 2 onwind      NaN       NaN
GB2 0 3 onwind      NaN       NaN
GB2 0 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 0 4 onwind  0.527000   253.473132
GB2 0 1 onwind  0.370976  2338.763985
GB2 0 0 onwind  0.346069  5240.350347
GB2 0 2 onwind  0.000000     0.000000
GB2 0 3 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 1592.2371177770146 MW
Capacity of the last onwind generator adjusted to fit cluster size: 746.5268676804837 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 0 4 onwind  GB2 0      PQ         0.0        0.0              True
GB2 0 1 onwind  GB2 0      PQ         0.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 0 4 onwind        0.0  253.473132        NaN       0.0  ...
GB2 0 1 onwind        0.0  746.526868        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 0 4 onwind               1                 0            NaN
GB2 0 1 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 0 4 onwind              NaN                  1.0                   1.0
GB2 0 1 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 0 4 onwind    1.0        0.0
GB2 0 1 onwind    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 0 1 onwind is name
GB2 0 1 onwind    1592.237118
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 1 0 solar-hsat       NaN       NaN
GB2 10 0 solar-hsat      NaN       NaN
GB2 11 0 solar-hsat      NaN       NaN
GB2 12 0 solar-hsat      NaN       NaN
GB2 13 0 solar-hsat      NaN       NaN
GB2 14 0 solar-hsat      NaN       NaN
GB2 15 0 solar-hsat      NaN       NaN
GB2 16 0 solar-hsat      NaN       NaN
GB2 17 0 solar-hsat      NaN       NaN
GB2 18 0 solar-hsat      NaN       NaN
GB2 19 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 17 0 solar-hsat  0.138065  25909.910793
GB2 16 0 solar-hsat  0.135116  26207.165464
GB2 10 0 solar-hsat  0.134123  32029.811833
GB2 12 0 solar-hsat  0.131899  23314.075205
GB2 18 0 solar-hsat  0.126922  35831.873707
GB2 15 0 solar-hsat  0.123461  33668.340029
GB2 13 0 solar-hsat  0.120837  22894.344829
GB2 19 0 solar-hsat  0.119388  20654.905274
GB2 1 0 solar-hsat   0.114139  33536.499734
GB2 11 0 solar-hsat  0.110857  41865.183052
GB2 14 0 solar-hsat  0.101303  15676.538262
Remaining top solar-hsat capacity outside the cluster: 24909.91079322189 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 17 0 solar-hsat  GB2 17      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 17 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 17 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 17 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 17 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 17 0 solar-hsat is name
GB2 17 0 solar-hsat    24909.910793
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 1 0 solar       NaN       NaN
GB2 1 1 solar       NaN       NaN
GB2 1 2 solar       NaN       NaN
GB2 1 3 solar       NaN       NaN
GB2 1 4 solar       NaN       NaN
GB2 10 0 solar      NaN       NaN
GB2 10 1 solar      NaN       NaN
GB2 10 2 solar      NaN       NaN
GB2 10 3 solar      NaN       NaN
GB2 10 4 solar      NaN       NaN
GB2 11 0 solar      NaN       NaN
GB2 11 1 solar      NaN       NaN
GB2 11 2 solar      NaN       NaN
GB2 11 3 solar      NaN       NaN
GB2 11 4 solar      NaN       NaN
GB2 12 0 solar      NaN       NaN
GB2 12 1 solar      NaN       NaN
GB2 12 2 solar      NaN       NaN
GB2 12 3 solar      NaN       NaN
GB2 12 4 solar      NaN       NaN
GB2 13 0 solar      NaN       NaN
GB2 13 1 solar      NaN       NaN
GB2 13 2 solar      NaN       NaN
GB2 13 3 solar      NaN       NaN
GB2 13 4 solar      NaN       NaN
GB2 14 0 solar      NaN       NaN
GB2 14 1 solar      NaN       NaN
GB2 14 2 solar      NaN       NaN
GB2 14 3 solar      NaN       NaN
GB2 14 4 solar      NaN       NaN
GB2 15 0 solar      NaN       NaN
GB2 15 1 solar      NaN       NaN
GB2 15 2 solar      NaN       NaN
GB2 15 3 solar      NaN       NaN
GB2 15 4 solar      NaN       NaN
GB2 16 0 solar      NaN       NaN
GB2 16 1 solar      NaN       NaN
GB2 16 2 solar      NaN       NaN
GB2 16 3 solar      NaN       NaN
GB2 16 4 solar      NaN       NaN
GB2 17 0 solar      NaN       NaN
GB2 17 1 solar      NaN       NaN
GB2 17 2 solar      NaN       NaN
GB2 17 3 solar      NaN       NaN
GB2 17 4 solar      NaN       NaN
GB2 18 0 solar      NaN       NaN
GB2 18 1 solar      NaN       NaN
GB2 18 2 solar      NaN       NaN
GB2 18 3 solar      NaN       NaN
GB2 18 4 solar      NaN       NaN
GB2 19 0 solar      NaN       NaN
GB2 19 1 solar      NaN       NaN
GB2 19 2 solar      NaN       NaN
GB2 19 3 solar      NaN       NaN
GB2 19 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 17 4 solar  0.122000     44.079338
GB2 12 4 solar  0.120705    970.545572
GB2 17 3 solar  0.119712   6163.757472
GB2 10 4 solar  0.118738    831.916872
GB2 10 3 solar  0.116199   8188.173177
GB2 16 4 solar  0.116119   2204.126280
GB2 17 2 solar  0.115643  10921.676011
GB2 16 3 solar  0.115284   6516.865551
GB2 18 4 solar  0.115169   2126.189119
GB2 16 2 solar  0.113757   3297.339793
GB2 10 2 solar  0.113428   8577.535755
GB2 12 2 solar  0.113341   4605.568405
GB2 17 1 solar  0.113271   7703.030910
GB2 16 1 solar  0.112797  15852.701975
GB2 18 3 solar  0.112026   5431.780168
GB2 16 0 solar  0.111817   2299.743797
GB2 17 0 solar  0.111241   4996.021743
GB2 10 1 solar  0.111219  19172.674936
GB2 12 1 solar  0.110479  10838.763146
GB2 15 4 solar  0.109913   1997.273159
GB2 12 0 solar  0.108854  10425.254603
GB2 18 2 solar  0.108098  15803.817084
GB2 10 0 solar  0.107847    103.748999
GB2 11 4 solar  0.106860   5924.433756
GB2 15 3 solar  0.106308  19025.471015
GB2 19 4 solar  0.105077   5352.202575
GB2 1 4 solar   0.104467   1134.762168
GB2 15 2 solar  0.104388   7551.322553
GB2 13 4 solar  0.104243   2520.477083
GB2 18 1 solar  0.103506  12316.366611
GB2 19 3 solar  0.102721   6777.189305
GB2 13 3 solar  0.102310  19718.947954
GB2 11 3 solar  0.102182   2902.707711
GB2 15 1 solar  0.101325   9929.087014
GB2 18 0 solar  0.101085   5572.988306
GB2 1 3 solar   0.100744  11951.196910
GB2 13 2 solar  0.099799   3718.269103
GB2 19 2 solar  0.098283   9315.200406
GB2 15 0 solar  0.096861    257.237714
GB2 13 1 solar  0.096739    180.841435
GB2 1 2 solar   0.096645  17338.410433
GB2 19 1 solar  0.096071   1976.800565
GB2 11 2 solar  0.095283  27307.412599
GB2 14 4 solar  0.094757   2577.300915
GB2 1 1 solar   0.094281   6712.313750
GB2 13 0 solar  0.094037    218.385108
GB2 19 0 solar  0.092795    357.392002
GB2 14 3 solar  0.091078   4420.675961
GB2 1 0 solar   0.088477   1471.928171
GB2 11 1 solar  0.087917   8973.021950
GB2 14 2 solar  0.087475   3883.346044
GB2 14 1 solar  0.083695   6083.534905
GB2 11 0 solar  0.081827   3089.361584
GB2 14 0 solar  0.078977   1082.624147
GB2 12 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 14.624909897786438 MW
Capacity of the last solar generator adjusted to fit cluster size: 955.9206621777168 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 17 4 solar  GB2 17      PQ        0.109841        0.0              True
GB2 12 4 solar  GB2 12      PQ       83.392822        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 17 4 solar   0.109841   44.079338        NaN       0.0  ...
GB2 12 4 solar  83.392822  955.920662        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 17 4 solar               1                 0            NaN
GB2 12 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 17 4 solar              NaN                  1.0                   1.0
GB2 12 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 17 4 solar    1.0        0.0
GB2 12 4 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 12 4 solar is name
GB2 12 4 solar    14.62491
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 1 0 onwind       NaN       NaN
GB2 1 1 onwind       NaN       NaN
GB2 1 2 onwind       NaN       NaN
GB2 1 3 onwind       NaN       NaN
GB2 1 4 onwind       NaN       NaN
GB2 10 0 onwind      NaN       NaN
GB2 10 1 onwind      NaN       NaN
GB2 10 2 onwind      NaN       NaN
GB2 10 3 onwind      NaN       NaN
GB2 10 4 onwind      NaN       NaN
GB2 11 0 onwind      NaN       NaN
GB2 11 1 onwind      NaN       NaN
GB2 11 2 onwind      NaN       NaN
GB2 11 3 onwind      NaN       NaN
GB2 11 4 onwind      NaN       NaN
GB2 12 0 onwind      NaN       NaN
GB2 12 1 onwind      NaN       NaN
GB2 12 2 onwind      NaN       NaN
GB2 12 3 onwind      NaN       NaN
GB2 12 4 onwind      NaN       NaN
GB2 13 0 onwind      NaN       NaN
GB2 13 1 onwind      NaN       NaN
GB2 13 2 onwind      NaN       NaN
GB2 13 3 onwind      NaN       NaN
GB2 13 4 onwind      NaN       NaN
GB2 14 0 onwind      NaN       NaN
GB2 14 1 onwind      NaN       NaN
GB2 14 2 onwind      NaN       NaN
GB2 14 3 onwind      NaN       NaN
GB2 14 4 onwind      NaN       NaN
GB2 15 0 onwind      NaN       NaN
GB2 15 1 onwind      NaN       NaN
GB2 15 2 onwind      NaN       NaN
GB2 15 3 onwind      NaN       NaN
GB2 15 4 onwind      NaN       NaN
GB2 16 0 onwind      NaN       NaN
GB2 16 1 onwind      NaN       NaN
GB2 16 2 onwind      NaN       NaN
GB2 16 3 onwind      NaN       NaN
GB2 16 4 onwind      NaN       NaN
GB2 17 0 onwind      NaN       NaN
GB2 17 1 onwind      NaN       NaN
GB2 17 2 onwind      NaN       NaN
GB2 17 3 onwind      NaN       NaN
GB2 17 4 onwind      NaN       NaN
GB2 18 0 onwind      NaN       NaN
GB2 18 1 onwind      NaN       NaN
GB2 18 2 onwind      NaN       NaN
GB2 18 3 onwind      NaN       NaN
GB2 18 4 onwind      NaN       NaN
GB2 19 0 onwind      NaN       NaN
GB2 19 1 onwind      NaN       NaN
GB2 19 2 onwind      NaN       NaN
GB2 19 3 onwind      NaN       NaN
GB2 19 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 11 4 onwind  0.601017   3260.220136
GB2 16 4 onwind  0.545752     85.220055
GB2 13 4 onwind  0.538682    118.509917
GB2 14 4 onwind  0.532409   2119.880809
GB2 17 4 onwind  0.524222      0.454863
GB2 10 4 onwind  0.519286    430.604117
GB2 11 3 onwind  0.508406   4902.621801
GB2 16 3 onwind  0.497737    263.110374
GB2 12 4 onwind  0.494372    176.198266
GB2 13 3 onwind  0.488570    674.478835
GB2 1 4 onwind   0.485655    898.571166
GB2 14 3 onwind  0.468339    906.527665
GB2 18 4 onwind  0.468245   1073.133778
GB2 15 4 onwind  0.464883    621.331961
GB2 16 2 onwind  0.438585   5417.650963
GB2 13 2 onwind  0.434151   1985.324706
GB2 1 3 onwind   0.431381   3597.402900
GB2 18 3 onwind  0.428074    660.107154
GB2 10 2 onwind  0.427053   2976.365606
GB2 11 2 onwind  0.425468  10456.969223
GB2 17 2 onwind  0.422835    381.276093
GB2 16 1 onwind  0.420398   1730.569846
GB2 15 3 onwind  0.418078    276.576422
GB2 13 1 onwind  0.407555   2321.222428
GB2 18 2 onwind  0.395268   2453.682213
GB2 17 1 onwind  0.386154   8140.010058
GB2 15 2 onwind  0.385205    367.478483
GB2 14 2 onwind  0.381910   2187.984305
GB2 10 1 onwind  0.381379   5311.007143
GB2 19 4 onwind  0.376486   1604.868258
GB2 12 1 onwind  0.368930     47.010373
GB2 13 0 onwind  0.368866   6038.904403
GB2 1 2 onwind   0.368198   9704.082283
GB2 18 1 onwind  0.367225   3705.421999
GB2 19 3 onwind  0.363366   3961.314398
GB2 16 0 onwind  0.360152   5267.847100
GB2 19 2 onwind  0.355307     50.550060
GB2 11 1 onwind  0.350664  12889.372281
GB2 10 0 onwind  0.348948   4535.209653
GB2 15 1 onwind  0.346559    626.358309
GB2 17 0 onwind  0.343942   4787.124764
GB2 12 0 onwind  0.343222  10271.940522
GB2 19 1 onwind  0.337872   1852.593529
GB2 19 0 onwind  0.318774     98.500222
GB2 18 0 onwind  0.318079  14959.093288
GB2 1 1 onwind   0.313890   6299.310532
GB2 15 0 onwind  0.309198  15554.925419
GB2 14 1 onwind  0.304428   7291.688765
GB2 1 0 onwind   0.268517   4635.637293
GB2 11 0 onwind  0.258605  12626.919830
GB2 14 0 onwind  0.245802  13574.214460
GB2 12 2 onwind  0.000000      0.000000
GB2 12 3 onwind  0.000000      0.000000
GB2 10 3 onwind  0.000000      0.000000
GB2 17 3 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 2260.220136432643 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 11 4 onwind  GB2 11      PQ       261.3        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 11 4 onwind      261.3     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 11 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 11 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 11 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 11 4 onwind is name
GB2 11 4 onwind    2260.220136
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 10 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 10 0 solar-hsat  0.134123  32029.811833
Remaining top solar-hsat capacity outside the cluster: 31029.811833015054 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 10 0 solar-hsat  GB2 10      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 10 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 10 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 10 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 10 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 10 0 solar-hsat is name
GB2 10 0 solar-hsat    31029.811833
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 10 0 solar      NaN       NaN
GB2 10 1 solar      NaN       NaN
GB2 10 2 solar      NaN       NaN
GB2 10 3 solar      NaN       NaN
GB2 10 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 10 4 solar  0.118738    831.916872
GB2 10 3 solar  0.116199   8188.173177
GB2 10 2 solar  0.113428   8577.535755
GB2 10 1 solar  0.111219  19172.674936
GB2 10 0 solar  0.107847    103.748999
Remaining top solar capacity outside the cluster: 8020.090049330416 MW
Capacity of the last solar generator adjusted to fit cluster size: 168.08312765626317 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 10 4 solar  GB2 10      PQ        15.917613        0.0              True
GB2 10 3 solar  GB2 10      PQ       236.633851        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 10 4 solar   15.917613  831.916872        NaN       0.0  ...
GB2 10 3 solar  236.633851  168.083128        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 10 4 solar               1                 0            NaN
GB2 10 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 10 4 solar              NaN                  1.0                   1.0
GB2 10 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 10 4 solar    1.0        0.0
GB2 10 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 10 3 solar is name
GB2 10 3 solar    8020.090049
Name: p_nom_max, dtype: float64 MW

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

                p_max_pu p_nom_max
name
GB2 10 0 onwind      NaN       NaN
GB2 10 1 onwind      NaN       NaN
GB2 10 2 onwind      NaN       NaN
GB2 10 3 onwind      NaN       NaN
GB2 10 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 10 4 onwind  0.519286   430.604117
GB2 10 2 onwind  0.427053  2976.365606
GB2 10 1 onwind  0.381379  5311.007143
GB2 10 0 onwind  0.348948  4535.209653
GB2 10 3 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 2406.969723878904 MW
Capacity of the last onwind generator adjusted to fit cluster size: 569.3958825084991 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 10 4 onwind  GB2 10      PQ         0.0        0.0              True
GB2 10 2 onwind  GB2 10      PQ        58.2        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 10 4 onwind        0.0  430.604117        NaN       0.0  ...
GB2 10 2 onwind       58.2  569.395883        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 10 4 onwind               1                 0            NaN
GB2 10 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 10 4 onwind              NaN                  1.0                   1.0
GB2 10 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 10 4 onwind    1.0        0.0
GB2 10 2 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 10 2 onwind is name
GB2 10 2 onwind    2406.969724
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 11 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 11 0 solar-hsat  0.110857  41865.183052
Remaining top solar-hsat capacity outside the cluster: 40865.18305215307 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 11 0 solar-hsat  GB2 11      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 11 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 11 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 11 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 11 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 11 0 solar-hsat is name
GB2 11 0 solar-hsat    40865.183052
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 11 0 solar      NaN       NaN
GB2 11 1 solar      NaN       NaN
GB2 11 2 solar      NaN       NaN
GB2 11 3 solar      NaN       NaN
GB2 11 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 11 4 solar  0.106860   5924.433756
GB2 11 3 solar  0.102182   2902.707711
GB2 11 2 solar  0.095283  27307.412599
GB2 11 1 solar  0.087917   8973.021950
GB2 11 0 solar  0.081827   3089.361584
Remaining top solar capacity outside the cluster: 4924.433755651963 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 11 4 solar  GB2 11      PQ       12.930943        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 11 4 solar  12.930943     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 11 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 11 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 11 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 11 4 solar is name
GB2 11 4 solar    4924.433756
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 11 0 onwind      NaN       NaN
GB2 11 1 onwind      NaN       NaN
GB2 11 2 onwind      NaN       NaN
GB2 11 3 onwind      NaN       NaN
GB2 11 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 11 4 onwind  0.601017   2260.220136
GB2 11 3 onwind  0.508406   4902.621801
GB2 11 2 onwind  0.425468  10456.969223
GB2 11 1 onwind  0.350664  12889.372281
GB2 11 0 onwind  0.258605  12626.919830
Remaining top onwind capacity outside the cluster: 1260.220136432643 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 11 4 onwind  GB2 11      PQ       261.3        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 11 4 onwind      261.3     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 11 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 11 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 11 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 11 4 onwind is name
GB2 11 4 onwind    1260.220136
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 12 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 12 0 solar-hsat  0.131899  23314.075205
Remaining top solar-hsat capacity outside the cluster: 22314.07520473689 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 12 0 solar-hsat  GB2 12      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 12 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 12 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 12 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 12 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 12 0 solar-hsat is name
GB2 12 0 solar-hsat    22314.075205
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 12 0 solar      NaN       NaN
GB2 12 1 solar      NaN       NaN
GB2 12 2 solar      NaN       NaN
GB2 12 3 solar      NaN       NaN
GB2 12 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 12 4 solar  0.120705     14.624910
GB2 12 2 solar  0.113341   4605.568405
GB2 12 1 solar  0.110479  10838.763146
GB2 12 0 solar  0.108854  10425.254603
GB2 12 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 3620.193314765911 MW
Capacity of the last solar generator adjusted to fit cluster size: 985.3750901022136 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 12 4 solar  GB2 12      PQ        83.392822        0.0              True
GB2 12 2 solar  GB2 12      PQ       117.862060        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 12 4 solar   83.392822   14.62491        NaN       0.0  ...
GB2 12 2 solar  117.862060  985.37509        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 12 4 solar               1                 0            NaN
GB2 12 2 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 12 4 solar              NaN                  1.0                   1.0
GB2 12 2 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 12 4 solar    1.0        0.0
GB2 12 2 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 12 2 solar is name
GB2 12 2 solar    3620.193315
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 12 0 onwind      NaN       NaN
GB2 12 1 onwind      NaN       NaN
GB2 12 2 onwind      NaN       NaN
GB2 12 3 onwind      NaN       NaN
GB2 12 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 12 4 onwind  0.494372    176.198266
GB2 12 1 onwind  0.368930     47.010373
GB2 12 0 onwind  0.343222  10271.940522
GB2 12 2 onwind  0.000000      0.000000
GB2 12 3 onwind  0.000000      0.000000
Remaining top onwind capacity outside the cluster: 9495.149162153 MW
Capacity of the last onwind generator adjusted to fit cluster size: 776.791360315314 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 12 4 onwind  GB2 12      PQ         0.0        0.0              True
GB2 12 1 onwind  GB2 12      PQ         0.0        0.0              True
GB2 12 0 onwind  GB2 12      PQ         2.0        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 12 4 onwind        0.0  176.198266        NaN       0.0  ...
GB2 12 1 onwind        0.0   47.010373        NaN       0.0  ...
GB2 12 0 onwind        2.0  776.791360        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 12 4 onwind               1                 0            NaN
GB2 12 1 onwind               1                 0            NaN
GB2 12 0 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 12 4 onwind              NaN                  1.0                   1.0
GB2 12 1 onwind              NaN                  1.0                   1.0
GB2 12 0 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 12 4 onwind    1.0        0.0
GB2 12 1 onwind    1.0        0.0
GB2 12 0 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator GB2 12 0 onwind is name
GB2 12 0 onwind    9495.149162
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 13 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 13 0 solar-hsat  0.120837  22894.344829
Remaining top solar-hsat capacity outside the cluster: 21894.34482875781 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 13 0 solar-hsat  GB2 13      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 13 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 13 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 13 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 13 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator GB2 13 0 solar-hsat is name
GB2 13 0 solar-hsat    21894.344829
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 13 0 solar      NaN       NaN
GB2 13 1 solar      NaN       NaN
GB2 13 2 solar      NaN       NaN
GB2 13 3 solar      NaN       NaN
GB2 13 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 13 4 solar  0.104243   2520.477083
GB2 13 3 solar  0.102310  19718.947954
GB2 13 2 solar  0.099799   3718.269103
GB2 13 1 solar  0.096739    180.841435
GB2 13 0 solar  0.094037    218.385108
Remaining top solar capacity outside the cluster: 1520.477082779813 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 13 4 solar  GB2 13      PQ       5.366573        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 13 4 solar   5.366573     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 13 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 13 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 13 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 13 4 solar is name
GB2 13 4 solar    1520.477083
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 13 0 onwind      NaN       NaN
GB2 13 1 onwind      NaN       NaN
GB2 13 2 onwind      NaN       NaN
GB2 13 3 onwind      NaN       NaN
GB2 13 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 13 4 onwind  0.538682   118.509917
GB2 13 3 onwind  0.488570   674.478835
GB2 13 2 onwind  0.434151  1985.324706
GB2 13 1 onwind  0.407555  2321.222428
GB2 13 0 onwind  0.368866  6038.904403
Remaining top onwind capacity outside the cluster: 1778.3134585639264 MW
Capacity of the last onwind generator adjusted to fit cluster size: 207.01124766182068 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 13 4 onwind  GB2 13      PQ         0.0        0.0              True
GB2 13 3 onwind  GB2 13      PQ         2.6        0.0              True
GB2 13 2 onwind  GB2 13      PQ       179.4        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 13 4 onwind        0.0  118.509917        NaN       0.0  ...
GB2 13 3 onwind        2.6  674.478835        NaN       0.0  ...
GB2 13 2 onwind      179.4  207.011248        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 13 4 onwind               1                 0            NaN
GB2 13 3 onwind               1                 0            NaN
GB2 13 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 13 4 onwind              NaN                  1.0                   1.0
GB2 13 3 onwind              NaN                  1.0                   1.0
GB2 13 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 13 4 onwind    1.0        0.0
GB2 13 3 onwind    1.0        0.0
GB2 13 2 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator GB2 13 2 onwind is name
GB2 13 2 onwind    1778.313459
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 14 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 14 0 solar-hsat  0.101303  15676.538262
Remaining top solar-hsat capacity outside the cluster: 14676.538261676127 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 14 0 solar-hsat  GB2 14      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 14 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 14 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 14 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 14 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator GB2 14 0 solar-hsat is name
GB2 14 0 solar-hsat    14676.538262
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 14 0 solar      NaN       NaN
GB2 14 1 solar      NaN       NaN
GB2 14 2 solar      NaN       NaN
GB2 14 3 solar      NaN       NaN
GB2 14 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 14 4 solar  0.094757  2577.300915
GB2 14 3 solar  0.091078  4420.675961
GB2 14 2 solar  0.087475  3883.346044
GB2 14 1 solar  0.083695  6083.534905
GB2 14 0 solar  0.078977  1082.624147
Remaining top solar capacity outside the cluster: 1577.300914871077 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 14 4 solar  GB2 14      PQ       4.988202        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 14 4 solar   4.988202     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 14 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 14 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 14 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 14 4 solar is name
GB2 14 4 solar    1577.300915
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 14 0 onwind      NaN       NaN
GB2 14 1 onwind      NaN       NaN
GB2 14 2 onwind      NaN       NaN
GB2 14 3 onwind      NaN       NaN
GB2 14 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 14 4 onwind  0.532409   2119.880809
GB2 14 3 onwind  0.468339    906.527665
GB2 14 2 onwind  0.381910   2187.984305
GB2 14 1 onwind  0.304428   7291.688765
GB2 14 0 onwind  0.245802  13574.214460
Remaining top onwind capacity outside the cluster: 1119.8808086404433 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 14 4 onwind  GB2 14      PQ        69.0        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 14 4 onwind       69.0     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 14 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 14 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 14 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 14 4 onwind is name
GB2 14 4 onwind    1119.880809
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 15 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 15 0 solar-hsat  0.123461  33668.340029
Remaining top solar-hsat capacity outside the cluster: 32668.340029293686 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 15 0 solar-hsat  GB2 15      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 15 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 15 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 15 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 15 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 15 0 solar-hsat is name
GB2 15 0 solar-hsat    32668.340029
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 15 0 solar      NaN       NaN
GB2 15 1 solar      NaN       NaN
GB2 15 2 solar      NaN       NaN
GB2 15 3 solar      NaN       NaN
GB2 15 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 15 4 solar  0.109913   1997.273159
GB2 15 3 solar  0.106308  19025.471015
GB2 15 2 solar  0.104388   7551.322553
GB2 15 1 solar  0.101325   9929.087014
GB2 15 0 solar  0.096861    257.237714
Remaining top solar capacity outside the cluster: 997.2731592839418 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 15 4 solar  GB2 15      PQ       33.783881        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 15 4 solar  33.783881     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 15 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 15 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 15 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 15 4 solar is name
GB2 15 4 solar    997.273159
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 15 0 onwind      NaN       NaN
GB2 15 1 onwind      NaN       NaN
GB2 15 2 onwind      NaN       NaN
GB2 15 3 onwind      NaN       NaN
GB2 15 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 15 4 onwind  0.464883    621.331961
GB2 15 3 onwind  0.418078    276.576422
GB2 15 2 onwind  0.385205    367.478483
GB2 15 1 onwind  0.346559    626.358309
GB2 15 0 onwind  0.309198  15554.925419
Remaining top onwind capacity outside the cluster: 265.38686577721137 MW
Capacity of the last onwind generator adjusted to fit cluster size: 102.09161682088654 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 15 4 onwind  GB2 15      PQ         0.0        0.0              True
GB2 15 3 onwind  GB2 15      PQ         1.8        0.0              True
GB2 15 2 onwind  GB2 15      PQ         2.3        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 15 4 onwind        0.0  621.331961        NaN       0.0  ...
GB2 15 3 onwind        1.8  276.576422        NaN       0.0  ...
GB2 15 2 onwind        2.3  102.091617        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 15 4 onwind               1                 0            NaN
GB2 15 3 onwind               1                 0            NaN
GB2 15 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 15 4 onwind              NaN                  1.0                   1.0
GB2 15 3 onwind              NaN                  1.0                   1.0
GB2 15 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 15 4 onwind    1.0        0.0
GB2 15 3 onwind    1.0        0.0
GB2 15 2 onwind    1.0        0.0

[3 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 15 2 onwind is name
GB2 15 2 onwind    265.386866
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 16 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 16 0 solar-hsat  0.135116  26207.165464
Remaining top solar-hsat capacity outside the cluster: 25207.16546360976 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 16 0 solar-hsat  GB2 16      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 16 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 16 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 16 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 16 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 16 0 solar-hsat is name
GB2 16 0 solar-hsat    25207.165464
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 16 0 solar      NaN       NaN
GB2 16 1 solar      NaN       NaN
GB2 16 2 solar      NaN       NaN
GB2 16 3 solar      NaN       NaN
GB2 16 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 16 4 solar  0.116119   2204.126280
GB2 16 3 solar  0.115284   6516.865551
GB2 16 2 solar  0.113757   3297.339793
GB2 16 1 solar  0.112797  15852.701975
GB2 16 0 solar  0.111817   2299.743797
Remaining top solar capacity outside the cluster: 1204.1262797061054 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 16 4 solar  GB2 16      PQ       75.727676        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 16 4 solar  75.727676     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 16 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 16 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 16 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 16 4 solar is name
GB2 16 4 solar    1204.12628
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 16 0 onwind      NaN       NaN
GB2 16 1 onwind      NaN       NaN
GB2 16 2 onwind      NaN       NaN
GB2 16 3 onwind      NaN       NaN
GB2 16 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 16 4 onwind  0.545752    85.220055
GB2 16 3 onwind  0.497737   263.110374
GB2 16 2 onwind  0.438585  5417.650963
GB2 16 1 onwind  0.420398  1730.569846
GB2 16 0 onwind  0.360152  5267.847100
Remaining top onwind capacity outside the cluster: 4765.981392681055 MW
Capacity of the last onwind generator adjusted to fit cluster size: 651.6695703435335 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 16 4 onwind  GB2 16      PQ         0.0        0.0              True
GB2 16 3 onwind  GB2 16      PQ         6.4        0.0              True
GB2 16 2 onwind  GB2 16      PQ        10.3        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 16 4 onwind        0.0   85.220055        NaN       0.0  ...
GB2 16 3 onwind        6.4  263.110374        NaN       0.0  ...
GB2 16 2 onwind       10.3  651.669570        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 16 4 onwind               1                 0            NaN
GB2 16 3 onwind               1                 0            NaN
GB2 16 2 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 16 4 onwind              NaN                  1.0                   1.0
GB2 16 3 onwind              NaN                  1.0                   1.0
GB2 16 2 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 16 4 onwind    1.0        0.0
GB2 16 3 onwind    1.0        0.0
GB2 16 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 16 2 onwind is name
GB2 16 2 onwind    4765.981393
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 17 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 17 0 solar-hsat  0.138065  24909.910793
Remaining top solar-hsat capacity outside the cluster: 23909.91079322189 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 17 0 solar-hsat  GB2 17      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 17 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 17 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 17 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 17 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 17 0 solar-hsat is name
GB2 17 0 solar-hsat    23909.910793
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 17 0 solar      NaN       NaN
GB2 17 1 solar      NaN       NaN
GB2 17 2 solar      NaN       NaN
GB2 17 3 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 17 3 solar  0.119712   6163.757472
GB2 17 2 solar  0.115643  10921.676011
GB2 17 1 solar  0.113271   7703.030910
GB2 17 0 solar  0.111241   4996.021743
Remaining top solar capacity outside the cluster: 5163.757472262127 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 17 3 solar  GB2 17      PQ       130.371357        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 17 3 solar  130.371357     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 17 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 17 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 17 3 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 17 3 solar is name
GB2 17 3 solar    5163.757472
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 17 0 onwind      NaN       NaN
GB2 17 1 onwind      NaN       NaN
GB2 17 2 onwind      NaN       NaN
GB2 17 3 onwind      NaN       NaN
GB2 17 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 17 4 onwind  0.524222     0.454863
GB2 17 2 onwind  0.422835   381.276093
GB2 17 1 onwind  0.386154  8140.010058
GB2 17 0 onwind  0.343942  4787.124764
GB2 17 3 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 7521.741013978639 MW
Capacity of the last onwind generator adjusted to fit cluster size: 618.2690439579026 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 17 4 onwind  GB2 17      PQ         0.0        0.0              True
GB2 17 2 onwind  GB2 17      PQ         0.0        0.0              True
GB2 17 1 onwind  GB2 17      PQ        18.0        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 17 4 onwind        0.0    0.454863        NaN       0.0  ...
GB2 17 2 onwind        0.0  381.276093        NaN       0.0  ...
GB2 17 1 onwind       18.0  618.269044        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 17 4 onwind               1                 0            NaN
GB2 17 2 onwind               1                 0            NaN
GB2 17 1 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 17 4 onwind              NaN                  1.0                   1.0
GB2 17 2 onwind              NaN                  1.0                   1.0
GB2 17 1 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 17 4 onwind    1.0        0.0
GB2 17 2 onwind    1.0        0.0
GB2 17 1 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator GB2 17 1 onwind is name
GB2 17 1 onwind    7521.741014
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 18 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 18 0 solar-hsat  0.126922  35831.873707
Remaining top solar-hsat capacity outside the cluster: 34831.87370652234 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 18 0 solar-hsat  GB2 18      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 18 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 18 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 18 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 18 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator GB2 18 0 solar-hsat is name
GB2 18 0 solar-hsat    34831.873707
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 18 0 solar      NaN       NaN
GB2 18 1 solar      NaN       NaN
GB2 18 2 solar      NaN       NaN
GB2 18 3 solar      NaN       NaN
GB2 18 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 18 4 solar  0.115169   2126.189119
GB2 18 3 solar  0.112026   5431.780168
GB2 18 2 solar  0.108098  15803.817084
GB2 18 1 solar  0.103506  12316.366611
GB2 18 0 solar  0.101085   5572.988306
Remaining top solar capacity outside the cluster: 1126.1891188117233 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 18 4 solar  GB2 18      PQ       91.301583        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 18 4 solar  91.301583     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 18 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 18 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 18 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 18 4 solar is name
GB2 18 4 solar    1126.189119
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 18 0 onwind      NaN       NaN
GB2 18 1 onwind      NaN       NaN
GB2 18 2 onwind      NaN       NaN
GB2 18 3 onwind      NaN       NaN
GB2 18 4 onwind      NaN       NaN
                 p_max_pu     p_nom_max
name
GB2 18 4 onwind  0.468245   1073.133778
GB2 18 3 onwind  0.428074    660.107154
GB2 18 2 onwind  0.395268   2453.682213
GB2 18 1 onwind  0.367225   3705.421999
GB2 18 0 onwind  0.318079  14959.093288
Remaining top onwind capacity outside the cluster: 73.13377756515797 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 18 4 onwind  GB2 18      PQ         0.0        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 18 4 onwind        0.0     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 18 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 18 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 18 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 18 4 onwind is name
GB2 18 4 onwind    73.133778
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 19 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 19 0 solar-hsat  0.119388  20654.905274
Remaining top solar-hsat capacity outside the cluster: 19654.90527435052 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 19 0 solar-hsat  GB2 19      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 19 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 19 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 19 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 19 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 19 0 solar-hsat is name
GB2 19 0 solar-hsat    19654.905274
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 19 0 solar      NaN       NaN
GB2 19 1 solar      NaN       NaN
GB2 19 2 solar      NaN       NaN
GB2 19 3 solar      NaN       NaN
GB2 19 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 19 4 solar  0.105077  5352.202575
GB2 19 3 solar  0.102721  6777.189305
GB2 19 2 solar  0.098283  9315.200406
GB2 19 1 solar  0.096071  1976.800565
GB2 19 0 solar  0.092795   357.392002
Remaining top solar capacity outside the cluster: 4352.2025751023675 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 19 4 solar  GB2 19      PQ       37.387031        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 19 4 solar  37.387031     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 19 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 19 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 19 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 19 4 solar is name
GB2 19 4 solar    4352.202575
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 19 0 onwind      NaN       NaN
GB2 19 1 onwind      NaN       NaN
GB2 19 2 onwind      NaN       NaN
GB2 19 3 onwind      NaN       NaN
GB2 19 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 19 4 onwind  0.376486  1604.868258
GB2 19 3 onwind  0.363366  3961.314398
GB2 19 2 onwind  0.355307    50.550060
GB2 19 1 onwind  0.337872  1852.593529
GB2 19 0 onwind  0.318774    98.500222
Remaining top onwind capacity outside the cluster: 604.8682582807676 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 19 4 onwind  GB2 19      PQ         0.0        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 19 4 onwind        0.0     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 19 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 19 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 19 4 onwind    1.0        0.0

[1 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 19 4 onwind is name
GB2 19 4 onwind    604.868258
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 2 0 solar-hsat       NaN       NaN
GB2 20 0 solar-hsat      NaN       NaN
GB2 21 0 solar-hsat      NaN       NaN
GB2 22 0 solar-hsat      NaN       NaN
GB2 23 0 solar-hsat      NaN       NaN
GB2 24 0 solar-hsat      NaN       NaN
GB2 25 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 22 0 solar-hsat  0.131306  29860.677952
GB2 21 0 solar-hsat  0.129836  29277.631501
GB2 24 0 solar-hsat  0.129018  34293.886698
GB2 20 0 solar-hsat  0.127987  26134.603481
GB2 2 0 solar-hsat   0.126577  31371.115302
GB2 23 0 solar-hsat  0.122419  13328.605766
GB2 25 0 solar-hsat  0.113965  19437.934427
Remaining top solar-hsat capacity outside the cluster: 28860.6779522692 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 22 0 solar-hsat  GB2 22      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 22 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 22 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 22 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 22 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 22 0 solar-hsat is name
GB2 22 0 solar-hsat    28860.677952
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 2 0 solar       NaN       NaN
GB2 2 1 solar       NaN       NaN
GB2 2 2 solar       NaN       NaN
GB2 2 3 solar       NaN       NaN
GB2 2 4 solar       NaN       NaN
GB2 20 0 solar      NaN       NaN
GB2 20 1 solar      NaN       NaN
GB2 20 2 solar      NaN       NaN
GB2 20 3 solar      NaN       NaN
GB2 20 4 solar      NaN       NaN
GB2 21 0 solar      NaN       NaN
GB2 21 1 solar      NaN       NaN
GB2 21 2 solar      NaN       NaN
GB2 21 3 solar      NaN       NaN
GB2 21 4 solar      NaN       NaN
GB2 22 0 solar      NaN       NaN
GB2 22 1 solar      NaN       NaN
GB2 22 2 solar      NaN       NaN
GB2 22 3 solar      NaN       NaN
GB2 22 4 solar      NaN       NaN
GB2 23 0 solar      NaN       NaN
GB2 23 1 solar      NaN       NaN
GB2 23 2 solar      NaN       NaN
GB2 23 3 solar      NaN       NaN
GB2 23 4 solar      NaN       NaN
GB2 24 0 solar      NaN       NaN
GB2 24 1 solar      NaN       NaN
GB2 24 2 solar      NaN       NaN
GB2 24 3 solar      NaN       NaN
GB2 24 4 solar      NaN       NaN
GB2 25 0 solar      NaN       NaN
GB2 25 1 solar      NaN       NaN
GB2 25 2 solar      NaN       NaN
GB2 25 3 solar      NaN       NaN
GB2 25 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 23 4 solar  0.115939   2697.756506
GB2 22 4 solar  0.113814    856.344763
GB2 24 4 solar  0.112815   3870.240870
GB2 22 3 solar  0.112194   6530.157583
GB2 21 4 solar  0.111741   2023.022382
GB2 21 3 solar  0.110940   4750.882538
GB2 24 3 solar  0.110799   9745.338151
GB2 22 2 solar  0.110749   8414.158317
GB2 23 3 solar  0.110493   1507.101907
GB2 20 4 solar  0.110034   4215.711866
GB2 21 2 solar  0.110003  13861.915489
GB2 22 1 solar  0.109529  14784.149928
GB2 2 4 solar   0.109296   2329.086160
GB2 20 3 solar  0.108964  11777.785646
GB2 24 2 solar  0.108510  18825.838174
GB2 21 1 solar  0.108340   9910.084814
GB2 2 3 solar   0.108215  14805.057497
GB2 21 0 solar  0.107909   3159.720207
GB2 22 0 solar  0.107784   3792.042131
GB2 20 2 solar  0.107229  11878.610785
GB2 23 2 solar  0.106819    919.600659
GB2 2 2 solar   0.106693   2399.402078
GB2 24 1 solar  0.106215   5555.902713
GB2 2 1 solar   0.105765  12982.749564
GB2 20 1 solar  0.105218   1200.306866
GB2 20 0 solar  0.104428   1014.825865
GB2 2 0 solar   0.104420   3599.435636
GB2 24 0 solar  0.103537   1483.226855
GB2 25 4 solar  0.101091   4969.101137
GB2 23 1 solar  0.101057   2622.332810
GB2 25 3 solar  0.098567   8738.554644
GB2 23 0 solar  0.097280   7597.652679
GB2 25 2 solar  0.096083   4205.038375
GB2 25 1 solar  0.091923   4274.121659
GB2 25 0 solar  0.088205    190.941652
Remaining top solar capacity outside the cluster: 1697.7565057214115 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 23 4 solar  GB2 23      PQ       64.988539        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 23 4 solar  64.988539     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 23 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 23 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 23 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 23 4 solar is name
GB2 23 4 solar    1697.756506
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 2 0 onwind       NaN       NaN
GB2 2 1 onwind       NaN       NaN
GB2 2 2 onwind       NaN       NaN
GB2 2 3 onwind       NaN       NaN
GB2 2 4 onwind       NaN       NaN
GB2 20 0 onwind      NaN       NaN
GB2 20 1 onwind      NaN       NaN
GB2 20 2 onwind      NaN       NaN
GB2 20 3 onwind      NaN       NaN
GB2 20 4 onwind      NaN       NaN
GB2 21 0 onwind      NaN       NaN
GB2 21 1 onwind      NaN       NaN
GB2 21 2 onwind      NaN       NaN
GB2 21 3 onwind      NaN       NaN
GB2 21 4 onwind      NaN       NaN
GB2 22 0 onwind      NaN       NaN
GB2 22 1 onwind      NaN       NaN
GB2 22 2 onwind      NaN       NaN
GB2 22 3 onwind      NaN       NaN
GB2 22 4 onwind      NaN       NaN
GB2 23 0 onwind      NaN       NaN
GB2 23 1 onwind      NaN       NaN
GB2 23 2 onwind      NaN       NaN
GB2 23 3 onwind      NaN       NaN
GB2 23 4 onwind      NaN       NaN
GB2 24 0 onwind      NaN       NaN
GB2 24 1 onwind      NaN       NaN
GB2 24 2 onwind      NaN       NaN
GB2 24 3 onwind      NaN       NaN
GB2 24 4 onwind      NaN       NaN
GB2 25 0 onwind      NaN       NaN
GB2 25 1 onwind      NaN       NaN
GB2 25 2 onwind      NaN       NaN
GB2 25 3 onwind      NaN       NaN
GB2 25 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 23 4 onwind  0.518929  1419.805909
GB2 24 4 onwind  0.513824   248.486134
GB2 25 4 onwind  0.495570   560.877892
GB2 24 3 onwind  0.484287  2127.576880
GB2 23 3 onwind  0.475369   730.786146
GB2 24 2 onwind  0.451469  2997.596965
GB2 23 2 onwind  0.447224   126.862869
GB2 25 3 onwind  0.443527  6358.479466
GB2 24 1 onwind  0.408685  5056.551854
GB2 25 2 onwind  0.403304    46.418020
GB2 23 1 onwind  0.391889  1906.554928
GB2 20 4 onwind  0.385048  3596.369182
GB2 21 4 onwind  0.381542  2155.706930
GB2 20 3 onwind  0.378464  3920.708463
GB2 24 0 onwind  0.371270  7374.276796
GB2 20 2 onwind  0.368927   637.499860
GB2 2 4 onwind   0.368445   301.967047
GB2 21 3 onwind  0.366112  3384.268617
GB2 20 1 onwind  0.363403   582.547456
GB2 25 1 onwind  0.361751  3453.075002
GB2 20 0 onwind  0.357795   739.660824
GB2 2 3 onwind   0.356347  2888.098548
GB2 21 2 onwind  0.355186  2023.920051
GB2 22 4 onwind  0.346001  6513.799961
GB2 21 1 onwind  0.344733  3020.294417
GB2 2 2 onwind   0.341283  2295.734325
GB2 22 3 onwind  0.339992  2489.459125
GB2 21 0 onwind  0.327327  1071.446852
GB2 22 2 onwind  0.326701  1290.801965
GB2 25 0 onwind  0.324930  5590.844968
GB2 2 1 onwind   0.322342  6279.090401
GB2 23 0 onwind  0.321114  7530.156515
GB2 22 1 onwind  0.321031  2336.612651
GB2 2 0 onwind   0.310583  1116.952480
GB2 22 0 onwind  0.307155  1391.980743
Remaining top onwind capacity outside the cluster: 419.8059087438087 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 23 4 onwind  GB2 23      PQ        45.0        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 23 4 onwind       45.0     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 23 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 23 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 23 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 23 4 onwind is name
GB2 23 4 onwind    419.805909
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 20 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 20 0 solar-hsat  0.127987  26134.603481
Remaining top solar-hsat capacity outside the cluster: 25134.603480953803 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 20 0 solar-hsat  GB2 20      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 20 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 20 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 20 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 20 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator GB2 20 0 solar-hsat is name
GB2 20 0 solar-hsat    25134.603481
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 20 0 solar      NaN       NaN
GB2 20 1 solar      NaN       NaN
GB2 20 2 solar      NaN       NaN
GB2 20 3 solar      NaN       NaN
GB2 20 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 20 4 solar  0.110034   4215.711866
GB2 20 3 solar  0.108964  11777.785646
GB2 20 2 solar  0.107229  11878.610785
GB2 20 1 solar  0.105218   1200.306866
GB2 20 0 solar  0.104428   1014.825865
Remaining top solar capacity outside the cluster: 3215.7118657099218 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 20 4 solar  GB2 20      PQ       60.474769        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 20 4 solar  60.474769     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 20 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 20 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 20 4 solar    1.0        0.0

[1 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 20 4 solar is name
GB2 20 4 solar    3215.711866
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 20 0 onwind      NaN       NaN
GB2 20 1 onwind      NaN       NaN
GB2 20 2 onwind      NaN       NaN
GB2 20 3 onwind      NaN       NaN
GB2 20 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 20 4 onwind  0.385048  3596.369182
GB2 20 3 onwind  0.378464  3920.708463
GB2 20 2 onwind  0.368927   637.499860
GB2 20 1 onwind  0.363403   582.547456
GB2 20 0 onwind  0.357795   739.660824
Remaining top onwind capacity outside the cluster: 2596.3691817562994 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 20 4 onwind  GB2 20      PQ        26.0        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 20 4 onwind       26.0     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 20 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 20 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 20 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 20 4 onwind is name
GB2 20 4 onwind    2596.369182
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 21 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 21 0 solar-hsat  0.129836  29277.631501
Remaining top solar-hsat capacity outside the cluster: 28277.631500813917 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 21 0 solar-hsat  GB2 21      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 21 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 21 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 21 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 21 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 21 0 solar-hsat is name
GB2 21 0 solar-hsat    28277.631501
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 21 0 solar      NaN       NaN
GB2 21 1 solar      NaN       NaN
GB2 21 2 solar      NaN       NaN
GB2 21 3 solar      NaN       NaN
GB2 21 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 21 4 solar  0.111741   2023.022382
GB2 21 3 solar  0.110940   4750.882538
GB2 21 2 solar  0.110003  13861.915489
GB2 21 1 solar  0.108340   9910.084814
GB2 21 0 solar  0.107909   3159.720207
Remaining top solar capacity outside the cluster: 1023.0223819904552 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 21 4 solar  GB2 21      PQ       42.217259        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 21 4 solar  42.217259     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 21 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 21 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 21 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 21 4 solar is name
GB2 21 4 solar    1023.022382
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 21 0 onwind      NaN       NaN
GB2 21 1 onwind      NaN       NaN
GB2 21 2 onwind      NaN       NaN
GB2 21 3 onwind      NaN       NaN
GB2 21 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 21 4 onwind  0.381542  2155.706930
GB2 21 3 onwind  0.366112  3384.268617
GB2 21 2 onwind  0.355186  2023.920051
GB2 21 1 onwind  0.344733  3020.294417
GB2 21 0 onwind  0.327327  1071.446852
Remaining top onwind capacity outside the cluster: 1155.7069300803241 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 21 4 onwind  GB2 21      PQ        68.8        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 21 4 onwind       68.8     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 21 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 21 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 21 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 21 4 onwind is name
GB2 21 4 onwind    1155.70693
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 22 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 22 0 solar-hsat  0.131306  28860.677952
Remaining top solar-hsat capacity outside the cluster: 27860.6779522692 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 22 0 solar-hsat  GB2 22      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 22 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 22 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 22 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 22 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

Residual capacity of generator GB2 22 0 solar-hsat is name
GB2 22 0 solar-hsat    27860.677952
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 22 0 solar      NaN       NaN
GB2 22 1 solar      NaN       NaN
GB2 22 2 solar      NaN       NaN
GB2 22 3 solar      NaN       NaN
GB2 22 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 22 4 solar  0.113814    856.344763
GB2 22 3 solar  0.112194   6530.157583
GB2 22 2 solar  0.110749   8414.158317
GB2 22 1 solar  0.109529  14784.149928
GB2 22 0 solar  0.107784   3792.042131
Remaining top solar capacity outside the cluster: 6386.502345836387 MW
Capacity of the last solar generator adjusted to fit cluster size: 143.65523728546907 MW
                   bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 22 4 solar  GB2 22      PQ         1.990743        0.0              True
GB2 22 3 solar  GB2 22      PQ       242.764478        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 22 4 solar    1.990743  856.344763        NaN       0.0  ...
GB2 22 3 solar  242.764478  143.655237        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 22 4 solar               1                 0            NaN
GB2 22 3 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 22 4 solar              NaN                  1.0                   1.0
GB2 22 3 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 22 4 solar    1.0        0.0
GB2 22 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 22 3 solar is name
GB2 22 3 solar    6386.502346
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 22 0 onwind      NaN       NaN
GB2 22 1 onwind      NaN       NaN
GB2 22 2 onwind      NaN       NaN
GB2 22 3 onwind      NaN       NaN
GB2 22 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 22 4 onwind  0.346001  6513.799961
GB2 22 3 onwind  0.339992  2489.459125
GB2 22 2 onwind  0.326701  1290.801965
GB2 22 1 onwind  0.321031  2336.612651
GB2 22 0 onwind  0.307155  1391.980743
Remaining top onwind capacity outside the cluster: 5513.799960618414 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 22 4 onwind  GB2 22      PQ         6.5        0.0              True

                 p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 22 4 onwind        6.5     1000.0        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 22 4 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 22 4 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 22 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 22 4 onwind is name
GB2 22 4 onwind    5513.799961
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 23 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 23 0 solar-hsat  0.122419  13328.605766
Remaining top solar-hsat capacity outside the cluster: 12328.60576579965 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 23 0 solar-hsat  GB2 23      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 23 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 23 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 23 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 23 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 23 0 solar-hsat is name
GB2 23 0 solar-hsat    12328.605766
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 23 0 solar      NaN       NaN
GB2 23 1 solar      NaN       NaN
GB2 23 2 solar      NaN       NaN
GB2 23 3 solar      NaN       NaN
GB2 23 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 23 4 solar  0.115939  1697.756506
GB2 23 3 solar  0.110493  1507.101907
GB2 23 2 solar  0.106819   919.600659
GB2 23 1 solar  0.101057  2622.332810
GB2 23 0 solar  0.097280  7597.652679
Remaining top solar capacity outside the cluster: 697.7565057214115 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 23 4 solar  GB2 23      PQ       64.988539        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 23 4 solar  64.988539     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 23 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 23 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 23 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 23 4 solar is name
GB2 23 4 solar    697.756506
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 23 0 onwind      NaN       NaN
GB2 23 1 onwind      NaN       NaN
GB2 23 2 onwind      NaN       NaN
GB2 23 3 onwind      NaN       NaN
GB2 23 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 23 4 onwind  0.518929   419.805909
GB2 23 3 onwind  0.475369   730.786146
GB2 23 2 onwind  0.447224   126.862869
GB2 23 1 onwind  0.391889  1906.554928
GB2 23 0 onwind  0.321114  7530.156515
Remaining top onwind capacity outside the cluster: 150.59205482823654 MW
Capacity of the last onwind generator adjusted to fit cluster size: 580.1940912561913 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 23 4 onwind  GB2 23      PQ        45.0        0.0              True
GB2 23 3 onwind  GB2 23      PQ         5.6        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 23 4 onwind       45.0  419.805909        NaN       0.0  ...
GB2 23 3 onwind        5.6  580.194091        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 23 4 onwind               1                 0            NaN
GB2 23 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 23 4 onwind              NaN                  1.0                   1.0
GB2 23 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 23 4 onwind    1.0        0.0
GB2 23 3 onwind    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 23 3 onwind is name
GB2 23 3 onwind    150.592055
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 24 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 24 0 solar-hsat  0.129018  34293.886698
Remaining top solar-hsat capacity outside the cluster: 33293.88669800088 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 24 0 solar-hsat  GB2 24      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 24 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 24 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 24 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 24 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 24 0 solar-hsat is name
GB2 24 0 solar-hsat    33293.886698
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 24 0 solar      NaN       NaN
GB2 24 1 solar      NaN       NaN
GB2 24 2 solar      NaN       NaN
GB2 24 3 solar      NaN       NaN
GB2 24 4 solar      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 24 4 solar  0.112815   3870.240870
GB2 24 3 solar  0.110799   9745.338151
GB2 24 2 solar  0.108510  18825.838174
GB2 24 1 solar  0.106215   5555.902713
GB2 24 0 solar  0.103537   1483.226855
Remaining top solar capacity outside the cluster: 2870.240870013883 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 24 4 solar  GB2 24      PQ       71.618172        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 24 4 solar  71.618172     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 24 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 24 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 24 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 24 4 solar is name
GB2 24 4 solar    2870.24087
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 24 0 onwind      NaN       NaN
GB2 24 1 onwind      NaN       NaN
GB2 24 2 onwind      NaN       NaN
GB2 24 3 onwind      NaN       NaN
GB2 24 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 24 4 onwind  0.513824   248.486134
GB2 24 3 onwind  0.484287  2127.576880
GB2 24 2 onwind  0.451469  2997.596965
GB2 24 1 onwind  0.408685  5056.551854
GB2 24 0 onwind  0.371270  7374.276796
Remaining top onwind capacity outside the cluster: 1376.0630139946525 MW
Capacity of the last onwind generator adjusted to fit cluster size: 751.5138663568393 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 24 4 onwind  GB2 24      PQ         0.0        0.0              True
GB2 24 3 onwind  GB2 24      PQ        98.9        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 24 4 onwind        0.0  248.486134        NaN       0.0  ...
GB2 24 3 onwind       98.9  751.513866        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 24 4 onwind               1                 0            NaN
GB2 24 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 24 4 onwind              NaN                  1.0                   1.0
GB2 24 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 24 4 onwind    1.0        0.0
GB2 24 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 24 3 onwind is name
GB2 24 3 onwind    1376.063014
Name: p_nom_max, dtype: float64 MW
                    p_max_pu p_nom_max
name
GB2 25 0 solar-hsat      NaN       NaN
                     p_max_pu     p_nom_max
name
GB2 25 0 solar-hsat  0.113965  19437.934427
Remaining top solar-hsat capacity outside the cluster: 18437.934427431188 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                        bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 25 0 solar-hsat  GB2 25      PQ         0.0        0.0              True

                     p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                            ...
GB2 25 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                     up_time_before  down_time_before  ramp_limit_up  \
name
GB2 25 0 solar-hsat               1                 0            NaN

                     ramp_limit_down  ramp_limit_start_up  \
name
GB2 25 0 solar-hsat              NaN                  1.0

                     ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 25 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 25 0 solar-hsat is name
GB2 25 0 solar-hsat    18437.934427
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 25 0 solar      NaN       NaN
GB2 25 1 solar      NaN       NaN
GB2 25 2 solar      NaN       NaN
GB2 25 3 solar      NaN       NaN
GB2 25 4 solar      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 25 4 solar  0.101091  4969.101137
GB2 25 3 solar  0.098567  8738.554644
GB2 25 2 solar  0.096083  4205.038375
GB2 25 1 solar  0.091923  4274.121659
GB2 25 0 solar  0.088205   190.941652
Remaining top solar capacity outside the cluster: 3969.101137011925 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                   bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 25 4 solar  GB2 25      PQ       10.260248        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 25 4 solar  10.260248     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 25 4 solar               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 25 4 solar              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 25 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 25 4 solar is name
GB2 25 4 solar    3969.101137
Name: p_nom_max, dtype: float64 MW
                p_max_pu p_nom_max
name
GB2 25 0 onwind      NaN       NaN
GB2 25 1 onwind      NaN       NaN
GB2 25 2 onwind      NaN       NaN
GB2 25 3 onwind      NaN       NaN
GB2 25 4 onwind      NaN       NaN
                 p_max_pu    p_nom_max
name
GB2 25 4 onwind  0.495570   560.877892
GB2 25 3 onwind  0.443527  6358.479466
GB2 25 2 onwind  0.403304    46.418020
GB2 25 1 onwind  0.361751  3453.075002
GB2 25 0 onwind  0.324930  5590.844968
Remaining top onwind capacity outside the cluster: 5919.357357726633 MW
Capacity of the last onwind generator adjusted to fit cluster size: 439.1221083714927 MW
                    bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 25 4 onwind  GB2 25      PQ        27.7        0.0              True
GB2 25 3 onwind  GB2 25      PQ       204.9        0.0              True

                 p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                         ...
GB2 25 4 onwind       27.7  560.877892        NaN       0.0  ...
GB2 25 3 onwind      204.9  439.122108        NaN       0.0  ...

                 up_time_before  down_time_before  ramp_limit_up  \
name
GB2 25 4 onwind               1                 0            NaN
GB2 25 3 onwind               1                 0            NaN

                 ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 25 4 onwind              NaN                  1.0                   1.0
GB2 25 3 onwind              NaN                  1.0                   1.0

                weight  p_nom_opt  location  unit
name
GB2 25 4 onwind    1.0        0.0
GB2 25 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 25 3 onwind is name
GB2 25 3 onwind    5919.357358
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 3 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 3 0 solar-hsat  0.136629  39853.725051
Remaining top solar-hsat capacity outside the cluster: 38853.72505145341 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 3 0 solar-hsat  GB2 3      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 3 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 3 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 3 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 3 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 3 0 solar-hsat is name
GB2 3 0 solar-hsat    38853.725051
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 3 0 solar      NaN       NaN
GB2 3 1 solar      NaN       NaN
GB2 3 2 solar      NaN       NaN
GB2 3 3 solar      NaN       NaN
GB2 3 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB2 3 4 solar  0.120802    899.333424
GB2 3 3 solar  0.118223  11694.073153
GB2 3 2 solar  0.115678   9480.374491
GB2 3 1 solar  0.112780  12154.132275
GB2 3 0 solar  0.110164  11653.350260
Remaining top solar capacity outside the cluster: 11593.406577117368 MW
Capacity of the last solar generator adjusted to fit cluster size: 100.66657634737192 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 3 4 solar  GB2 3      PQ        56.419028        0.0              True
GB2 3 3 solar  GB2 3      PQ       297.938245        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 3 4 solar   56.419028  899.333424        NaN       0.0  ...
GB2 3 3 solar  297.938245  100.666576        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
GB2 3 4 solar               1                 0            NaN
GB2 3 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 3 4 solar              NaN                  1.0                   1.0
GB2 3 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
GB2 3 4 solar    1.0        0.0
GB2 3 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 3 3 solar is name
GB2 3 3 solar    11593.406577
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 3 0 onwind      NaN       NaN
GB2 3 1 onwind      NaN       NaN
GB2 3 2 onwind      NaN       NaN
GB2 3 3 onwind      NaN       NaN
GB2 3 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 3 4 onwind  0.540059  1587.044956
GB2 3 3 onwind  0.508648  3862.064393
GB2 3 2 onwind  0.460203  5902.589550
GB2 3 1 onwind  0.424624  7148.809452
GB2 3 0 onwind  0.373047  5245.123250
Remaining top onwind capacity outside the cluster: 587.044955886472 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 3 4 onwind  GB2 3      PQ        77.4        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 3 4 onwind       77.4     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 3 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 3 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 3 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 3 4 onwind is name
GB2 3 4 onwind    587.044956
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 4 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 4 0 solar-hsat  0.122832  30773.172217
Remaining top solar-hsat capacity outside the cluster: 29773.17221741735 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 4 0 solar-hsat  GB2 4      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 4 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 4 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 4 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 4 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 4 0 solar-hsat is name
GB2 4 0 solar-hsat    29773.172217
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 4 0 solar      NaN       NaN
GB2 4 1 solar      NaN       NaN
GB2 4 2 solar      NaN       NaN
GB2 4 3 solar      NaN       NaN
GB2 4 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB2 4 4 solar  0.106678  11631.909129
GB2 4 3 solar  0.104667  13475.177541
GB2 4 2 solar  0.100878   7074.709356
GB2 4 1 solar  0.098024   2529.535586
GB2 4 0 solar  0.093105    716.022409
Remaining top solar capacity outside the cluster: 10631.90912857972 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 4 4 solar  GB2 4      PQ       224.24528        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
GB2 4 4 solar  224.24528     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
GB2 4 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
GB2 4 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
GB2 4 4 solar

[1 rows x 40 columns]
Residual capacity of generator GB2 4 4 solar is name
GB2 4 4 solar    10631.909129
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 4 0 onwind      NaN       NaN
GB2 4 1 onwind      NaN       NaN
GB2 4 2 onwind      NaN       NaN
GB2 4 3 onwind      NaN       NaN
GB2 4 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 4 4 onwind  0.380990  3940.058271
GB2 4 3 onwind  0.371773  1310.394220
GB2 4 2 onwind  0.368120  1636.540353
GB2 4 1 onwind  0.357320  3082.706436
GB2 4 0 onwind  0.349793  1281.485489
Remaining top onwind capacity outside the cluster: 2940.0582710544363 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 4 4 onwind  GB2 4      PQ        56.0        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 4 4 onwind       56.0     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 4 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 4 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 4 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 4 4 onwind is name
GB2 4 4 onwind    2940.058271
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 5 0 solar-hsat      NaN       NaN
                    p_max_pu    p_nom_max
name
GB2 5 0 solar-hsat  0.114449  28218.18719
Remaining top solar-hsat capacity outside the cluster: 27218.18718955689 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 5 0 solar-hsat  GB2 5      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 5 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 5 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 5 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 5 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 5 0 solar-hsat is name
GB2 5 0 solar-hsat    27218.18719
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 5 0 solar      NaN       NaN
GB2 5 1 solar      NaN       NaN
GB2 5 2 solar      NaN       NaN
GB2 5 3 solar      NaN       NaN
GB2 5 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB2 5 4 solar  0.108778     14.784753
GB2 5 3 solar  0.103022   8481.177646
GB2 5 2 solar  0.098436   3451.561182
GB2 5 1 solar  0.095019  16295.508316
GB2 5 0 solar  0.089833   4242.917238
Remaining top solar capacity outside the cluster: 7495.962398568412 MW
Capacity of the last solar generator adjusted to fit cluster size: 985.2152469335416 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 5 4 solar  GB2 5      PQ        0.000000        0.0              True
GB2 5 3 solar  GB2 5      PQ       73.246574        0.0              True

               p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 5 4 solar   0.000000   14.784753        NaN       0.0  ...
GB2 5 3 solar  73.246574  985.215247        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
GB2 5 4 solar               1                 0            NaN
GB2 5 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 5 4 solar              NaN                  1.0                   1.0
GB2 5 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
GB2 5 4 solar    1.0        0.0
GB2 5 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 5 3 solar is name
GB2 5 3 solar    7495.962399
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 5 0 onwind      NaN       NaN
GB2 5 1 onwind      NaN       NaN
GB2 5 2 onwind      NaN       NaN
GB2 5 3 onwind      NaN       NaN
GB2 5 4 onwind      NaN       NaN
                p_max_pu     p_nom_max
name
GB2 5 4 onwind  0.495068   1098.651251
GB2 5 3 onwind  0.455261   1025.937830
GB2 5 2 onwind  0.430394    395.165603
GB2 5 1 onwind  0.369585  12543.396609
GB2 5 0 onwind  0.325673   8282.429931
Remaining top onwind capacity outside the cluster: 98.65125129008516 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 5 4 onwind  GB2 5      PQ         0.0        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 5 4 onwind        0.0     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 5 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 5 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 5 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 5 4 onwind is name
GB2 5 4 onwind    98.651251
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 6 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 6 0 solar-hsat  0.137465  15900.422175
Remaining top solar-hsat capacity outside the cluster: 14900.422174840869 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 6 0 solar-hsat  GB2 6      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 6 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 6 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 6 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 6 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 6 0 solar-hsat is name
GB2 6 0 solar-hsat    14900.422175
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 6 0 solar      NaN       NaN
GB2 6 1 solar      NaN       NaN
GB2 6 2 solar      NaN       NaN
GB2 6 3 solar      NaN       NaN
GB2 6 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
GB2 6 4 solar  0.119089  5551.225677
GB2 6 2 solar  0.114329  2238.553769
GB2 6 1 solar  0.113106  8620.465223
GB2 6 0 solar  0.111392  1894.981762
GB2 6 3 solar  0.000000     0.000000
Remaining top solar capacity outside the cluster: 4551.225676838698 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 6 4 solar  GB2 6      PQ       421.302967        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 6 4 solar  421.302967     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
GB2 6 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 6 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
GB2 6 4 solar    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 6 4 solar is name
GB2 6 4 solar    4551.225677
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 6 0 onwind      NaN       NaN
GB2 6 1 onwind      NaN       NaN
GB2 6 2 onwind      NaN       NaN
GB2 6 3 onwind      NaN       NaN
GB2 6 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 6 4 onwind  0.446509   873.177067
GB2 6 3 onwind  0.408875   953.551168
GB2 6 0 onwind  0.341587  5507.703141
GB2 6 2 onwind  0.000000     0.000000
GB2 6 1 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 826.7282350049468 MW
Capacity of the last onwind generator adjusted to fit cluster size: 126.8229331605296 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 6 4 onwind  GB2 6      PQ         0.0        0.0              True
GB2 6 3 onwind  GB2 6      PQ         0.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 6 4 onwind        0.0  873.177067        NaN       0.0  ...
GB2 6 3 onwind        0.0  126.822933        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 6 4 onwind               1                 0            NaN
GB2 6 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 6 4 onwind              NaN                  1.0                   1.0
GB2 6 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 6 4 onwind    1.0        0.0
GB2 6 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 6 3 onwind is name
GB2 6 3 onwind    826.728235
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 7 0 solar-hsat      NaN       NaN
                    p_max_pu    p_nom_max
name
GB2 7 0 solar-hsat    0.1071  7658.345432
Remaining top solar-hsat capacity outside the cluster: 6658.345432348759 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 7 0 solar-hsat  GB2 7      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 7 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 7 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 7 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 7 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 7 0 solar-hsat is name
GB2 7 0 solar-hsat    6658.345432
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 7 0 solar      NaN       NaN
GB2 7 1 solar      NaN       NaN
GB2 7 2 solar      NaN       NaN
GB2 7 3 solar      NaN       NaN
GB2 7 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
GB2 7 4 solar  0.098315   404.584015
GB2 7 3 solar  0.095104  4735.246929
GB2 7 2 solar  0.091016  2079.695456
GB2 7 1 solar  0.087284  1025.499058
GB2 7 0 solar  0.083579   571.579892
Remaining top solar capacity outside the cluster: 4139.830944630651 MW
Capacity of the last solar generator adjusted to fit cluster size: 595.4159846667055 MW
                 bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 7 4 solar  GB2 7      PQ       0.812450        0.0              True
GB2 7 3 solar  GB2 7      PQ       9.198375        0.0              True

               p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB2 7 4 solar   0.812450  404.584015        NaN       0.0  ...
GB2 7 3 solar   9.198375  595.415985        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
GB2 7 4 solar               1                 0            NaN
GB2 7 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 7 4 solar              NaN                  1.0                   1.0
GB2 7 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
GB2 7 4 solar    1.0        0.0
GB2 7 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 7 3 solar is name
GB2 7 3 solar    4139.830945
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 7 0 onwind      NaN       NaN
GB2 7 1 onwind      NaN       NaN
GB2 7 2 onwind      NaN       NaN
GB2 7 3 onwind      NaN       NaN
GB2 7 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 7 4 onwind  0.604997   987.342063
GB2 7 3 onwind  0.505681  2432.718114
GB2 7 2 onwind  0.431313   116.246236
GB2 7 1 onwind  0.389978  3197.655311
GB2 7 0 onwind  0.324913  3386.767478
Remaining top onwind capacity outside the cluster: 2420.0601760635413 MW
Capacity of the last onwind generator adjusted to fit cluster size: 12.657937490407221 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 7 4 onwind  GB2 7      PQ       526.5        0.0              True
GB2 7 3 onwind  GB2 7      PQ       418.5        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 7 4 onwind      526.5  987.342063        NaN       0.0  ...
GB2 7 3 onwind      418.5   12.657937        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 7 4 onwind               1                 0            NaN
GB2 7 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 7 4 onwind              NaN                  1.0                   1.0
GB2 7 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 7 4 onwind    1.0        0.0
GB2 7 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator GB2 7 3 onwind is name
GB2 7 3 onwind    2420.060176
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 8 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 8 0 solar-hsat  0.132183  31565.994189
Remaining top solar-hsat capacity outside the cluster: 30565.994188788784 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 8 0 solar-hsat  GB2 8      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 8 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 8 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 8 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 8 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 8 0 solar-hsat is name
GB2 8 0 solar-hsat    30565.994189
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 8 0 solar      NaN       NaN
GB2 8 1 solar      NaN       NaN
GB2 8 2 solar      NaN       NaN
GB2 8 3 solar      NaN       NaN
GB2 8 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB2 8 4 solar  0.114416    258.167699
GB2 8 3 solar  0.113139   7804.305042
GB2 8 2 solar  0.111679  12605.138747
GB2 8 1 solar  0.110773  15479.552114
GB2 8 0 solar  0.109251    192.920002
Remaining top solar capacity outside the cluster: 7062.472740951834 MW
Capacity of the last solar generator adjusted to fit cluster size: 741.8323006685869 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 8 4 solar  GB2 8      PQ         0.603334        0.0              True
GB2 8 3 solar  GB2 8      PQ       221.234931        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 8 4 solar    0.603334  258.167699        NaN       0.0  ...
GB2 8 3 solar  221.234931  741.832301        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
GB2 8 4 solar               1                 0            NaN
GB2 8 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 8 4 solar              NaN                  1.0                   1.0
GB2 8 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
GB2 8 4 solar    1.0        0.0
GB2 8 3 solar    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 8 3 solar is name
GB2 8 3 solar    7062.472741
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 8 0 onwind      NaN       NaN
GB2 8 1 onwind      NaN       NaN
GB2 8 2 onwind      NaN       NaN
GB2 8 3 onwind      NaN       NaN
GB2 8 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 8 4 onwind  0.517031   171.999946
GB2 8 3 onwind  0.480053   647.908777
GB2 8 2 onwind  0.425193  1531.488768
GB2 8 1 onwind  0.394066  6175.248376
GB2 8 0 onwind  0.356602  7419.282429
Remaining top onwind capacity outside the cluster: 1351.3974905658638 MW
Capacity of the last onwind generator adjusted to fit cluster size: 180.0912771555552 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 8 4 onwind  GB2 8      PQ         0.0        0.0              True
GB2 8 3 onwind  GB2 8      PQ         2.6        0.0              True
GB2 8 2 onwind  GB2 8      PQ        25.3        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 8 4 onwind        0.0  171.999946        NaN       0.0  ...
GB2 8 3 onwind        2.6  647.908777        NaN       0.0  ...
GB2 8 2 onwind       25.3  180.091277        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 8 4 onwind               1                 0            NaN
GB2 8 3 onwind               1                 0            NaN
GB2 8 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 8 4 onwind              NaN                  1.0                   1.0
GB2 8 3 onwind              NaN                  1.0                   1.0
GB2 8 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 8 4 onwind    1.0        0.0
GB2 8 3 onwind    1.0        0.0
GB2 8 2 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator GB2 8 2 onwind is name
GB2 8 2 onwind    1351.397491
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB2 9 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB2 9 0 solar-hsat  0.117254  16111.703802
Remaining top solar-hsat capacity outside the cluster: 15111.703802070733 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 9 0 solar-hsat  GB2 9      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB2 9 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB2 9 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB2 9 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB2 9 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB2 9 0 solar-hsat is name
GB2 9 0 solar-hsat    15111.703802
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB2 9 0 solar      NaN       NaN
GB2 9 1 solar      NaN       NaN
GB2 9 2 solar      NaN       NaN
GB2 9 3 solar      NaN       NaN
GB2 9 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
GB2 9 4 solar  0.109267  1778.282852
GB2 9 3 solar  0.103650  4374.645961
GB2 9 2 solar  0.099620  4053.392083
GB2 9 1 solar  0.096287  4728.977675
GB2 9 0 solar  0.090693  3613.164045
Remaining top solar capacity outside the cluster: 778.2828523740636 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 9 4 solar  GB2 9      PQ       34.66881        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
GB2 9 4 solar   34.66881     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
GB2 9 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
GB2 9 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
GB2 9 4 solar

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB2 9 4 solar is name
GB2 9 4 solar    778.282852
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB2 9 0 onwind      NaN       NaN
GB2 9 1 onwind      NaN       NaN
GB2 9 2 onwind      NaN       NaN
GB2 9 3 onwind      NaN       NaN
GB2 9 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
GB2 9 4 onwind  0.516355     2.397036
GB2 9 3 onwind  0.465890   403.695695
GB2 9 2 onwind  0.424340  1356.787657
GB2 9 1 onwind  0.370053  4881.148047
GB2 9 0 onwind  0.321630  3831.057741
Remaining top onwind capacity outside the cluster: 762.8803877338582 MW
Capacity of the last onwind generator adjusted to fit cluster size: 593.9072693755082 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB2 9 4 onwind  GB2 9      PQ         0.0        0.0              True
GB2 9 3 onwind  GB2 9      PQ        13.0        0.0              True
GB2 9 2 onwind  GB2 9      PQ         8.2        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
GB2 9 4 onwind        0.0    2.397036        NaN       0.0  ...
GB2 9 3 onwind       13.0  403.695695        NaN       0.0  ...
GB2 9 2 onwind        8.2  593.907269        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB2 9 4 onwind               1                 0            NaN
GB2 9 3 onwind               1                 0            NaN
GB2 9 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB2 9 4 onwind              NaN                  1.0                   1.0
GB2 9 3 onwind              NaN                  1.0                   1.0
GB2 9 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB2 9 4 onwind    1.0        0.0
GB2 9 3 onwind    1.0        0.0
GB2 9 2 onwind    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator GB2 9 2 onwind is name
GB2 9 2 onwind    762.880388
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
GB3 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
GB3 0 0 solar-hsat  0.114458  49548.354206
Remaining top solar-hsat capacity outside the cluster: 48548.35420580111 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB3 0 0 solar-hsat  GB3 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
GB3 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
GB3 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
GB3 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
GB3 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB3 0 0 solar-hsat is name
GB3 0 0 solar-hsat    48548.354206
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
GB3 0 0 solar      NaN       NaN
GB3 0 1 solar      NaN       NaN
GB3 0 2 solar      NaN       NaN
GB3 0 3 solar      NaN       NaN
GB3 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
GB3 0 4 solar  0.107306   3068.670964
GB3 0 3 solar  0.104096   3252.307104
GB3 0 2 solar  0.099628  23243.004440
GB3 0 1 solar  0.095937  18308.318266
GB3 0 0 solar  0.092701   9169.822578
Remaining top solar capacity outside the cluster: 2068.670963937123 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
GB3 0 4 solar  GB3 0      PQ       6.725776        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
GB3 0 4 solar   6.725776     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
GB3 0 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
GB3 0 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
GB3 0 4 solar

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator GB3 0 4 solar is name
GB3 0 4 solar    2068.670964
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
GB3 0 0 onwind      NaN       NaN
GB3 0 1 onwind      NaN       NaN
GB3 0 2 onwind      NaN       NaN
GB3 0 3 onwind      NaN       NaN
GB3 0 4 onwind      NaN       NaN
                p_max_pu     p_nom_max
name
GB3 0 4 onwind  0.559213   1549.378237
GB3 0 3 onwind  0.531037    991.113520
GB3 0 2 onwind  0.459872   3271.133703
GB3 0 1 onwind  0.385275   8848.604480
GB3 0 0 onwind  0.323116  16176.029543
Remaining top onwind capacity outside the cluster: 549.3782366219839 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
GB3 0 4 onwind  GB3 0      PQ        29.9        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
GB3 0 4 onwind       29.9     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
GB3 0 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
GB3 0 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
GB3 0 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator GB3 0 4 onwind is name
GB3 0 4 onwind    549.378237
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 0 0 solar-hsat  0.131137  19486.653111
Remaining top solar-hsat capacity outside the cluster: 18486.653110563377 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 0 0 solar-hsat  NL0 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 0 0 solar-hsat is name
NL0 0 0 solar-hsat    18486.653111
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 0 0 solar      NaN       NaN
NL0 0 1 solar      NaN       NaN
NL0 0 2 solar      NaN       NaN
NL0 0 3 solar      NaN       NaN
NL0 0 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 0 4 solar  0.114947  4455.210444
NL0 0 3 solar  0.112925  4557.916796
NL0 0 2 solar  0.109930  7876.841105
NL0 0 1 solar  0.107694  5220.311373
NL0 0 0 solar  0.103506   323.564721
Remaining top solar capacity outside the cluster: 3455.210443545635 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 0 4 solar  NL0 0      PQ       397.836932        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
NL0 0 4 solar  397.836932     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 0 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 0 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 0 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 0 4 solar is name
NL0 0 4 solar    3455.210444
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 0 0 onwind      NaN       NaN
NL0 0 1 onwind      NaN       NaN
NL0 0 2 onwind      NaN       NaN
NL0 0 3 onwind      NaN       NaN
NL0 0 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 0 4 onwind  0.514459   941.784324
NL0 0 3 onwind  0.473862  1043.302181
NL0 0 2 onwind  0.418217  2296.520921
NL0 0 1 onwind  0.351811  4146.820571
NL0 0 0 onwind  0.306130  1016.080840
Remaining top onwind capacity outside the cluster: 985.0865051097073 MW
Capacity of the last onwind generator adjusted to fit cluster size: 58.21567626498768 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 0 4 onwind  NL0 0      PQ        86.0        0.0              True
NL0 0 3 onwind  NL0 0      PQ         0.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 0 4 onwind       86.0  941.784324        NaN       0.0  ...
NL0 0 3 onwind        0.0   58.215676        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 0 4 onwind               1                 0            NaN
NL0 0 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 0 4 onwind              NaN                  1.0                   1.0
NL0 0 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 0 4 onwind    1.0        0.0
NL0 0 3 onwind    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 0 3 onwind is name
NL0 0 3 onwind    985.086505
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 1 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 1 0 solar-hsat  0.132251  15302.075907
Remaining top solar-hsat capacity outside the cluster: 14302.075906723641 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 1 0 solar-hsat  NL0 1      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 1 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 1 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 1 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 1 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 1 0 solar-hsat is name
NL0 1 0 solar-hsat    14302.075907
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 1 0 solar      NaN       NaN
NL0 1 1 solar      NaN       NaN
NL0 1 2 solar      NaN       NaN
NL0 1 3 solar      NaN       NaN
NL0 1 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 1 4 solar  0.116834  2990.373512
NL0 1 3 solar  0.114113  4706.653796
NL0 1 2 solar  0.111025  4391.451277
NL0 1 1 solar  0.108907  2367.999479
NL0 1 0 solar  0.107238  3159.907290
Remaining top solar capacity outside the cluster: 1990.3735123901624 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 1 4 solar  NL0 1      PQ       201.216751        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
NL0 1 4 solar  201.216751     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 1 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 1 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 1 4 solar    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 1 4 solar is name
NL0 1 4 solar    1990.373512
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 1 0 onwind      NaN       NaN
NL0 1 1 onwind      NaN       NaN
NL0 1 2 onwind      NaN       NaN
NL0 1 3 onwind      NaN       NaN
NL0 1 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 1 4 onwind  0.547755     1.329715
NL0 1 3 onwind  0.479284  1337.859852
NL0 1 2 onwind  0.410165   602.737174
NL0 1 1 onwind  0.357126   875.381279
NL0 1 0 onwind  0.299735  1099.793428
Remaining top onwind capacity outside the cluster: 339.1895675465273 MW
Capacity of the last onwind generator adjusted to fit cluster size: 998.670284790841 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 1 4 onwind  NL0 1      PQ         0.0        0.0              True
NL0 1 3 onwind  NL0 1      PQ       470.8        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 1 4 onwind        0.0    1.329715        NaN       0.0  ...
NL0 1 3 onwind      470.8  998.670285        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 1 4 onwind               1                 0            NaN
NL0 1 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 1 4 onwind              NaN                  1.0                   1.0
NL0 1 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 1 4 onwind    1.0        0.0
NL0 1 3 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NL0 1 3 onwind is name
NL0 1 3 onwind    339.189568
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 2 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 2 0 solar-hsat  0.129076  12276.647382
Remaining top solar-hsat capacity outside the cluster: 11276.647381861902 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 2 0 solar-hsat  NL0 2      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 2 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 2 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 2 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 2 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 2 0 solar-hsat is name
NL0 2 0 solar-hsat    11276.647382
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 2 0 solar      NaN       NaN
NL0 2 1 solar      NaN       NaN
NL0 2 2 solar      NaN       NaN
NL0 2 3 solar      NaN       NaN
NL0 2 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 2 4 solar  0.111144  1598.386648
NL0 2 3 solar  0.109454  5199.223165
NL0 2 2 solar  0.107806  5036.074199
NL0 2 1 solar  0.106676  1776.135405
NL0 2 0 solar  0.104146   523.566959
Remaining top solar capacity outside the cluster: 598.3866481520924 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 2 4 solar  NL0 2      PQ       125.44518        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
NL0 2 4 solar  125.44518     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
NL0 2 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
NL0 2 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
NL0 2 4 solar

[1 rows x 40 columns]
Residual capacity of generator NL0 2 4 solar is name
NL0 2 4 solar    598.386648
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 2 0 onwind      NaN       NaN
NL0 2 1 onwind      NaN       NaN
NL0 2 2 onwind      NaN       NaN
NL0 2 3 onwind      NaN       NaN
NL0 2 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 2 3 onwind  0.272933   414.572318
NL0 2 2 onwind  0.258424   693.966644
NL0 2 1 onwind  0.247305   918.543284
NL0 2 0 onwind  0.235159  1612.142972
NL0 2 4 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 108.53896167429593 MW
Capacity of the last onwind generator adjusted to fit cluster size: 585.4276822444613 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 2 3 onwind  NL0 2      PQ         0.0        0.0              True
NL0 2 2 onwind  NL0 2      PQ        11.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 2 3 onwind        0.0  414.572318        NaN       0.0  ...
NL0 2 2 onwind       11.0  585.427682        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 2 3 onwind               1                 0            NaN
NL0 2 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 2 3 onwind              NaN                  1.0                   1.0
NL0 2 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 2 3 onwind    1.0        0.0
NL0 2 2 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NL0 2 2 onwind is name
NL0 2 2 onwind    108.538962
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 3 0 solar-hsat      NaN       NaN
                    p_max_pu    p_nom_max
name
NL0 3 0 solar-hsat  0.133348  8447.932044
Remaining top solar-hsat capacity outside the cluster: 7447.932044064508 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 3 0 solar-hsat  NL0 3      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 3 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 3 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 3 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 3 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 3 0 solar-hsat is name
NL0 3 0 solar-hsat    7447.932044
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 3 0 solar      NaN       NaN
NL0 3 1 solar      NaN       NaN
NL0 3 2 solar      NaN       NaN
NL0 3 3 solar      NaN       NaN
NL0 3 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 3 4 solar  0.115773  1288.937570
NL0 3 3 solar  0.113791  2213.366274
NL0 3 2 solar  0.112606  1313.986016
NL0 3 1 solar  0.111171  4802.214165
NL0 3 0 solar  0.109074   107.106230
Remaining top solar capacity outside the cluster: 288.93757022615273 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 3 4 solar  NL0 3      PQ       178.780761        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
NL0 3 4 solar  178.780761     1000.0        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 3 4 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 3 4 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 3 4 solar    1.0        0.0

[1 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 3 4 solar is name
NL0 3 4 solar    288.93757
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 3 0 onwind      NaN       NaN
NL0 3 1 onwind      NaN       NaN
NL0 3 2 onwind      NaN       NaN
NL0 3 3 onwind      NaN       NaN
NL0 3 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 3 3 onwind  0.432322   299.640604
NL0 3 2 onwind  0.371095   776.048428
NL0 3 1 onwind  0.334775   984.223205
NL0 3 0 onwind  0.301593  1477.715971
NL0 3 4 onwind  0.000000     0.000000
Remaining top onwind capacity outside the cluster: 75.68903211354746 MW
Capacity of the last onwind generator adjusted to fit cluster size: 700.3593955782254 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 3 3 onwind  NL0 3      PQ        60.0        0.0              True
NL0 3 2 onwind  NL0 3      PQ       112.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 3 3 onwind       60.0  299.640604        NaN       0.0  ...
NL0 3 2 onwind      112.0  700.359396        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 3 3 onwind               1                 0            NaN
NL0 3 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 3 3 onwind              NaN                  1.0                   1.0
NL0 3 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 3 3 onwind    1.0        0.0
NL0 3 2 onwind    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NL0 3 2 onwind is name
NL0 3 2 onwind    75.689032
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 4 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 4 0 solar-hsat  0.127066  18376.341479
Remaining top solar-hsat capacity outside the cluster: 17376.341478548253 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 4 0 solar-hsat  NL0 4      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 4 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 4 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 4 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 4 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 4 0 solar-hsat is name
NL0 4 0 solar-hsat    17376.341479
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 4 0 solar      NaN       NaN
NL0 4 1 solar      NaN       NaN
NL0 4 2 solar      NaN       NaN
NL0 4 3 solar      NaN       NaN
NL0 4 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
NL0 4 4 solar  0.109666   1170.336528
NL0 4 3 solar  0.108837   2153.082957
NL0 4 2 solar  0.106969  10349.582036
NL0 4 1 solar  0.106108   7134.100369
NL0 4 0 solar  0.104849    348.505682
Remaining top solar capacity outside the cluster: 170.33652757955792 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 4 4 solar  NL0 4      PQ       53.566956        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
NL0 4 4 solar  53.566956     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
NL0 4 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
NL0 4 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
NL0 4 4 solar

[1 rows x 40 columns]
Residual capacity of generator NL0 4 4 solar is name
NL0 4 4 solar    170.336528
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 4 0 onwind      NaN       NaN
NL0 4 1 onwind      NaN       NaN
NL0 4 2 onwind      NaN       NaN
NL0 4 3 onwind      NaN       NaN
NL0 4 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 4 4 onwind  0.454455  1355.967081
NL0 4 3 onwind  0.422406   847.000000
NL0 4 2 onwind  0.374493    15.446329
NL0 4 1 onwind  0.336707  3470.503008
NL0 4 0 onwind  0.309797  2982.922697
Remaining top onwind capacity outside the cluster: 355.96708119027744 MW
Capacity of the last onwind generator adjusted to fit cluster size: 1000.0 MW

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.

                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 4 4 onwind  NL0 4      PQ         0.0        0.0              True

                p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
NL0 4 4 onwind        0.0     1000.0        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 4 4 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 4 4 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 4 4 onwind    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 4 4 onwind is name
NL0 4 4 onwind    355.967081
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 5 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 5 0 solar-hsat  0.127151  11293.161213
Remaining top solar-hsat capacity outside the cluster: 10293.161212875784 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 5 0 solar-hsat  NL0 5      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 5 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 5 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 5 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 5 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 5 0 solar-hsat is name
NL0 5 0 solar-hsat    10293.161213
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 5 0 solar      NaN       NaN
NL0 5 1 solar      NaN       NaN
NL0 5 2 solar      NaN       NaN
NL0 5 3 solar      NaN       NaN
NL0 5 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 5 4 solar  0.109493   181.507901
NL0 5 3 solar  0.108003  5571.216809
NL0 5 2 solar  0.106894  6168.189304
NL0 5 1 solar  0.105552    60.147300
NL0 5 0 solar  0.103506  1020.094935
Remaining top solar capacity outside the cluster: 4752.724709855242 MW
Capacity of the last solar generator adjusted to fit cluster size: 818.4920994617934 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 5 4 solar  NL0 5      PQ         8.294613        0.0              True
NL0 5 3 solar  NL0 5      PQ       400.929966        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 5 4 solar    8.294613  181.507901        NaN       0.0  ...
NL0 5 3 solar  400.929966  818.492099        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 5 4 solar               1                 0            NaN
NL0 5 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 5 4 solar              NaN                  1.0                   1.0
NL0 5 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 5 4 solar    1.0        0.0
NL0 5 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NL0 5 3 solar is name
NL0 5 3 solar    4752.72471
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 5 0 onwind      NaN       NaN
NL0 5 1 onwind      NaN       NaN
NL0 5 2 onwind      NaN       NaN
NL0 5 3 onwind      NaN       NaN
NL0 5 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 5 4 onwind  0.298019   724.585626
NL0 5 3 onwind  0.278552   835.584443
NL0 5 2 onwind  0.268643   681.409970
NL0 5 1 onwind  0.248040  1387.287532
NL0 5 0 onwind  0.232209   255.413100
Remaining top onwind capacity outside the cluster: 560.1700685688561 MW
Capacity of the last onwind generator adjusted to fit cluster size: 275.4143740578072 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 5 4 onwind  NL0 5      PQ         0.0        0.0              True
NL0 5 3 onwind  NL0 5      PQ         0.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 5 4 onwind        0.0  724.585626        NaN       0.0  ...
NL0 5 3 onwind        0.0  275.414374        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 5 4 onwind               1                 0            NaN
NL0 5 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 5 4 onwind              NaN                  1.0                   1.0
NL0 5 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 5 4 onwind    1.0        0.0
NL0 5 3 onwind    1.0        0.0

[2 rows x 40 columns]

/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 5 3 onwind is name
NL0 5 3 onwind    560.170069
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 6 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NL0 6 0 solar-hsat  0.125853  18682.885646
Remaining top solar-hsat capacity outside the cluster: 17682.885645719543 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 6 0 solar-hsat  NL0 6      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 6 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 6 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 6 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 6 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 6 0 solar-hsat is name
NL0 6 0 solar-hsat    17682.885646
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 6 0 solar      NaN       NaN
NL0 6 1 solar      NaN       NaN
NL0 6 2 solar      NaN       NaN
NL0 6 3 solar      NaN       NaN
NL0 6 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
NL0 6 4 solar  0.109658    305.078264
NL0 6 2 solar  0.106855  12146.500504
NL0 6 1 solar  0.105727   9054.870506
NL0 6 0 solar  0.104408      2.064675
NL0 6 3 solar  0.000000      0.000000
Remaining top solar capacity outside the cluster: 11451.578768086321 MW
Capacity of the last solar generator adjusted to fit cluster size: 694.921735573028 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 6 4 solar  NL0 6      PQ        13.962604        0.0              True
NL0 6 2 solar  NL0 6      PQ       691.799525        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 6 4 solar   13.962604  305.078264        NaN       0.0  ...
NL0 6 2 solar  691.799525  694.921736        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 6 4 solar               1                 0            NaN
NL0 6 2 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 6 4 solar              NaN                  1.0                   1.0
NL0 6 2 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 6 4 solar    1.0        0.0
NL0 6 2 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NL0 6 2 solar is name
NL0 6 2 solar    11451.578768
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 6 0 onwind      NaN       NaN
NL0 6 1 onwind      NaN       NaN
NL0 6 2 onwind      NaN       NaN
NL0 6 3 onwind      NaN       NaN
NL0 6 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 6 4 onwind  0.338180    80.939137
NL0 6 3 onwind  0.310539  1048.858423
NL0 6 2 onwind  0.287485  3641.613717
NL0 6 1 onwind  0.270052  2851.209959
NL0 6 0 onwind  0.250307  2138.396890
Remaining top onwind capacity outside the cluster: 129.79756002030126 MW
Capacity of the last onwind generator adjusted to fit cluster size: 919.0608628271638 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 6 4 onwind  NL0 6      PQ         0.0        0.0              True
NL0 6 3 onwind  NL0 6      PQ        35.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 6 4 onwind        0.0   80.939137        NaN       0.0  ...
NL0 6 3 onwind       35.0  919.060863        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 6 4 onwind               1                 0            NaN
NL0 6 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 6 4 onwind              NaN                  1.0                   1.0
NL0 6 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 6 4 onwind    1.0        0.0
NL0 6 3 onwind    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 6 3 onwind is name
NL0 6 3 onwind    129.79756
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 7 0 solar-hsat      NaN       NaN
                    p_max_pu    p_nom_max
name
NL0 7 0 solar-hsat  0.133007  7486.787877
Remaining top solar-hsat capacity outside the cluster: 6486.787877342223 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 7 0 solar-hsat  NL0 7      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 7 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 7 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 7 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 7 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 7 0 solar-hsat is name
NL0 7 0 solar-hsat    6486.787877
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 7 0 solar      NaN       NaN
NL0 7 1 solar      NaN       NaN
NL0 7 2 solar      NaN       NaN
NL0 7 3 solar      NaN       NaN
NL0 7 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 7 4 solar  0.115661   258.284814
NL0 7 3 solar  0.114591   370.290861
NL0 7 2 solar  0.113137  5092.175273
NL0 7 1 solar  0.110963  2232.086656
NL0 7 0 solar  0.110323   666.263564
Remaining top solar capacity outside the cluster: 4720.750947623313 MW
Capacity of the last solar generator adjusted to fit cluster size: 371.42432496059996 MW
                 bus control type       p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 7 4 solar  NL0 7      PQ        52.468049        0.0              True
NL0 7 3 solar  NL0 7      PQ        17.709513        0.0              True
NL0 7 2 solar  NL0 7      PQ       278.047584        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 7 4 solar   52.468049  258.284814        NaN       0.0  ...
NL0 7 3 solar   17.709513  370.290861        NaN       0.0  ...
NL0 7 2 solar  278.047584  371.424325        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NL0 7 4 solar               1                 0            NaN
NL0 7 3 solar               1                 0            NaN
NL0 7 2 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 7 4 solar              NaN                  1.0                   1.0
NL0 7 3 solar              NaN                  1.0                   1.0
NL0 7 2 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NL0 7 4 solar    1.0        0.0
NL0 7 3 solar    1.0        0.0
NL0 7 2 solar    1.0        0.0

[3 rows x 40 columns]
Residual capacity of generator NL0 7 2 solar is name
NL0 7 2 solar    4720.750948
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 7 0 onwind      NaN       NaN
NL0 7 1 onwind      NaN       NaN
NL0 7 2 onwind      NaN       NaN
NL0 7 3 onwind      NaN       NaN
NL0 7 4 onwind      NaN       NaN
                p_max_pu   p_nom_max
name
NL0 7 4 onwind  0.453367   86.000000
NL0 7 2 onwind  0.385579  737.170292
NL0 7 1 onwind  0.355173   79.980702
NL0 7 0 onwind  0.320454  760.588798
NL0 7 3 onwind  0.000000    0.000000
Remaining top onwind capacity outside the cluster: 663.7397914539658 MW
Capacity of the last onwind generator adjusted to fit cluster size: 96.8490061821492 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 7 4 onwind  NL0 7      PQ        86.0        0.0              True
NL0 7 2 onwind  NL0 7      PQ       219.0        0.0              True
NL0 7 1 onwind  NL0 7      PQ         0.0        0.0              True
NL0 7 0 onwind  NL0 7      PQ       352.6        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 7 4 onwind       86.0   86.000000        NaN       0.0  ...
NL0 7 2 onwind      219.0  737.170292        NaN       0.0  ...
NL0 7 1 onwind        0.0   79.980702        NaN       0.0  ...
NL0 7 0 onwind      352.6   96.849006        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 7 4 onwind               1                 0            NaN
NL0 7 2 onwind               1                 0            NaN
NL0 7 1 onwind               1                 0            NaN
NL0 7 0 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 7 4 onwind              NaN                  1.0                   1.0
NL0 7 2 onwind              NaN                  1.0                   1.0
NL0 7 1 onwind              NaN                  1.0                   1.0
NL0 7 0 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 7 4 onwind    1.0        0.0
NL0 7 2 onwind    1.0        0.0
NL0 7 1 onwind    1.0        0.0
NL0 7 0 onwind    1.0        0.0

[4 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 7 0 onwind is name
NL0 7 0 onwind    663.739791
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NL0 8 0 solar-hsat      NaN       NaN
                    p_max_pu    p_nom_max
name
NL0 8 0 solar-hsat  0.129614  9729.410496
Remaining top solar-hsat capacity outside the cluster: 8729.410496294768 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 8 0 solar-hsat  NL0 8      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NL0 8 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NL0 8 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NL0 8 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NL0 8 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NL0 8 0 solar-hsat is name
NL0 8 0 solar-hsat    8729.410496
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NL0 8 0 solar      NaN       NaN
NL0 8 1 solar      NaN       NaN
NL0 8 2 solar      NaN       NaN
NL0 8 3 solar      NaN       NaN
NL0 8 4 solar      NaN       NaN
               p_max_pu    p_nom_max
name
NL0 8 4 solar  0.110972  1080.366975
NL0 8 3 solar  0.110307  3996.877798
NL0 8 2 solar  0.108853  2745.031516
NL0 8 1 solar  0.108573  1248.990636
NL0 8 0 solar  0.107690  2129.634549
Remaining top solar capacity outside the cluster: 80.36697506670566 MW
Capacity of the last solar generator adjusted to fit cluster size: 1000.0 MW
                 bus control type      p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 8 4 solar  NL0 8      PQ       82.137539        0.0              True

               p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  up_time_before  \
name                                                      ...
NL0 8 4 solar  82.137539     1000.0        NaN       0.0  ...               1

               down_time_before  ramp_limit_up  ramp_limit_down  \
name
NL0 8 4 solar                 0            NaN              NaN

               ramp_limit_start_up  ramp_limit_shut_down weight  p_nom_opt  \
name
NL0 8 4 solar                  1.0                   1.0    1.0        0.0

               location  unit
name
NL0 8 4 solar

[1 rows x 40 columns]
Residual capacity of generator NL0 8 4 solar is name
NL0 8 4 solar    80.366975
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NL0 8 0 onwind      NaN       NaN
NL0 8 1 onwind      NaN       NaN
NL0 8 2 onwind      NaN       NaN
NL0 8 3 onwind      NaN       NaN
NL0 8 4 onwind      NaN       NaN
                p_max_pu    p_nom_max
name
NL0 8 4 onwind  0.349417    39.549192
NL0 8 3 onwind  0.327910    74.759730
NL0 8 2 onwind  0.297572  1183.947890
NL0 8 1 onwind  0.277410  1267.194431
NL0 8 0 onwind  0.255678   219.835977
Remaining top onwind capacity outside the cluster: 298.2568116096634 MW
Capacity of the last onwind generator adjusted to fit cluster size: 885.6910780232043 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NL0 8 4 onwind  NL0 8      PQ         0.0        0.0              True
NL0 8 3 onwind  NL0 8      PQ         0.0        0.0              True
NL0 8 2 onwind  NL0 8      PQ        73.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NL0 8 4 onwind        0.0   39.549192        NaN       0.0  ...
NL0 8 3 onwind        0.0   74.759730        NaN       0.0  ...
NL0 8 2 onwind       73.0  885.691078        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NL0 8 4 onwind               1                 0            NaN
NL0 8 3 onwind               1                 0            NaN
NL0 8 2 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NL0 8 4 onwind              NaN                  1.0                   1.0
NL0 8 3 onwind              NaN                  1.0                   1.0
NL0 8 2 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NL0 8 4 onwind    1.0        0.0
NL0 8 3 onwind    1.0        0.0
NL0 8 2 onwind    1.0        0.0

[3 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NL0 8 2 onwind is name
NL0 8 2 onwind    298.256812
Name: p_nom_max, dtype: float64 MW
                   p_max_pu p_nom_max
name
NO1 0 0 solar-hsat      NaN       NaN
                    p_max_pu     p_nom_max
name
NO1 0 0 solar-hsat  0.120485  31781.802252
Remaining top solar-hsat capacity outside the cluster: 30781.802251635454 MW
Capacity of the last solar-hsat generator adjusted to fit cluster size: 1000.0 MW
                      bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NO1 0 0 solar-hsat  NO1 0      PQ         0.0        0.0              True

                    p_nom_min  p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                           ...
NO1 0 0 solar-hsat        0.0     1000.0        NaN       0.0  ...

                    up_time_before  down_time_before  ramp_limit_up  \
name
NO1 0 0 solar-hsat               1                 0            NaN

                    ramp_limit_down  ramp_limit_start_up  \
name
NO1 0 0 solar-hsat              NaN                  1.0

                    ramp_limit_shut_down weight  p_nom_opt  location  unit
name
NO1 0 0 solar-hsat                   1.0    1.0        0.0

[1 rows x 40 columns]
Residual capacity of generator NO1 0 0 solar-hsat is name
NO1 0 0 solar-hsat    30781.802252
Name: p_nom_max, dtype: float64 MW
              p_max_pu p_nom_max
name
NO1 0 0 solar      NaN       NaN
NO1 0 1 solar      NaN       NaN
NO1 0 2 solar      NaN       NaN
NO1 0 3 solar      NaN       NaN
NO1 0 4 solar      NaN       NaN
               p_max_pu     p_nom_max
name
NO1 0 4 solar  0.110580    764.808856
NO1 0 3 solar  0.106391   2009.405834
NO1 0 2 solar  0.100756  16481.015531
NO1 0 1 solar  0.095891  15252.607645
NO1 0 0 solar  0.087854   2080.692943
Remaining top solar capacity outside the cluster: 1774.2146900363978 MW
Capacity of the last solar generator adjusted to fit cluster size: 235.19114360824324 MW
                 bus control type     p_nom  p_nom_mod  p_nom_extendable  \
name
NO1 0 4 solar  NO1 0      PQ       0.417370        0.0              True
NO1 0 3 solar  NO1 0      PQ       1.055028        0.0              True

               p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                       ...
NO1 0 4 solar   0.417370  764.808856        NaN       0.0  ...
NO1 0 3 solar   1.055028  235.191144        NaN       0.0  ...

               up_time_before  down_time_before  ramp_limit_up  \
name
NO1 0 4 solar               1                 0            NaN
NO1 0 3 solar               1                 0            NaN

               ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NO1 0 4 solar              NaN                  1.0                   1.0
NO1 0 3 solar              NaN                  1.0                   1.0

              weight  p_nom_opt  location  unit
name
NO1 0 4 solar    1.0        0.0
NO1 0 3 solar    1.0        0.0

[2 rows x 40 columns]
Residual capacity of generator NO1 0 3 solar is name
NO1 0 3 solar    1774.21469
Name: p_nom_max, dtype: float64 MW
               p_max_pu p_nom_max
name
NO1 0 0 onwind      NaN       NaN
NO1 0 1 onwind      NaN       NaN
NO1 0 2 onwind      NaN       NaN
NO1 0 3 onwind      NaN       NaN
NO1 0 4 onwind      NaN       NaN
                p_max_pu     p_nom_max
name
NO1 0 4 onwind  0.531543    169.547658
NO1 0 3 onwind  0.399401   4672.646264
NO1 0 2 onwind  0.277102  16408.787580
NO1 0 1 onwind  0.184118   9894.385283
NO1 0 0 onwind  0.084278  16958.526389
Remaining top onwind capacity outside the cluster: 3842.193922074869 MW
Capacity of the last onwind generator adjusted to fit cluster size: 830.4523424064948 MW
                  bus control type  p_nom  p_nom_mod  p_nom_extendable  \
name
NO1 0 4 onwind  NO1 0      PQ         0.0        0.0              True
NO1 0 3 onwind  NO1 0      PQ       744.0        0.0              True

                p_nom_min   p_nom_max  p_nom_set  p_min_pu  ...  \
name                                                        ...
NO1 0 4 onwind        0.0  169.547658        NaN       0.0  ...
NO1 0 3 onwind      744.0  830.452342        NaN       0.0  ...

                up_time_before  down_time_before  ramp_limit_up  \
name
NO1 0 4 onwind               1                 0            NaN
NO1 0 3 onwind               1                 0            NaN

                ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  \
name
NO1 0 4 onwind              NaN                  1.0                   1.0
NO1 0 3 onwind              NaN                  1.0                   1.0

               weight  p_nom_opt  location  unit
name
NO1 0 4 onwind    1.0        0.0
NO1 0 3 onwind    1.0        0.0

[2 rows x 40 columns]

WARNING:pypsa.network.transform:The attribute 'unit' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
WARNING:pypsa.network.transform:The attribute 'location' is a standard attribute for other components but not for generators. This could cause confusion and it should be renamed. See also: https://go.pypsa.org/warning-attr-misleading.
/tmp/ipykernel_18245/2144190009.py:93: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Residual capacity of generator NO1 0 3 onwind is name
NO1 0 3 onwind    3842.193922
Name: p_nom_max, dtype: float64 MW
Empty DataFrame
Columns: [p_max_pu, p_nom_max]
Index: []
Empty DataFrame
Columns: [p_max_pu, p_nom_max]
Index: []

ValueError: Not enough solar-hsat generators to reach cluster_size.

In [12]:
n.buses.loc[n.buses.index.str.contains("methanol cluster")]

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network,country,substation_lv,substation_off
name,,,,,,,,,,,,,,,,
DE0 0 methanol cluster,1.0,,11.778928,51.997389,methanol,MWh_th,DE0 0,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 11 methanol cluster,1.0,,10.426224,47.834642,methanol,MWh_th,DE0 11,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 10 methanol cluster,1.0,,12.989530,48.436497,methanol,MWh_th,DE0 10,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 19 methanol cluster,1.0,,12.574724,53.967904,methanol,MWh_th,DE0 19,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 16 methanol cluster,1.0,,8.295841,53.275471,methanol,MWh_th,DE0 16,1.0,0.0,inf,PQ,,,DE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NL0 5 methanol cluster,1.0,,5.788516,51.782718,methanol,MWh_th,NL0 5,1.0,0.0,inf,PQ,,,NL,NaN,NaN
NL0 6 methanol cluster,1.0,,6.400371,52.253520,methanol,MWh_th,NL0 6,1.0,0.0,inf,PQ,,,NL,NaN,NaN
NL0 7 methanol cluster,1.0,,4.187932,52.048726,methanol,MWh_th,NL0 7,1.0,0.0,inf,PQ,,,NL,NaN,NaN
NL0 8 methanol cluster,1.0,,4.737308,51.809393,methanol,MWh_th,NL0 8,1.0,0.0,inf,PQ,,,NL,NaN,NaN
NO1 0 methanol cluster,1.0,,6.268203,59.324070,methanol,MWh_th,NO1 0,1.0,0.0,inf,PQ,,,NO,NaN,NaN

In [13]:
n.generators_t['p_max_pu']

name,DE0 0 0 onwind,DE0 0 0 solar,DE0 0 0 solar rooftop,DE0 0 0 solar-hsat,DE0 0 1 onwind,DE0 0 1 solar,DE0 0 1 solar rooftop,DE0 0 2 onwind,DE0 0 2 solar,DE0 0 2 solar rooftop,...,NL0 8 0 solar-hsat cluster,NL0 8 4 solar cluster,NL0 8 4 onwind cluster,NL0 8 3 onwind cluster,NL0 8 2 onwind cluster,NO1 0 0 solar-hsat cluster,NO1 0 4 solar cluster,NO1 0 3 solar cluster,NO1 0 4 onwind cluster,NO1 0 3 onwind cluster
snapshot,,,,,,,,,,,,,,,,,,,,,
2013-01-01 00:00:00,0.741777,0.020643,0.020643,0.032510,0.750684,0.026455,0.026455,0.721260,0.032428,0.032428,...,0.018221,0.022472,0.549369,0.569623,0.596201,0.014350,0.022757,0.021922,0.706259,0.368256
2013-01-01 12:00:00,0.421445,0.018548,0.018548,0.013129,0.446756,0.011506,0.011506,0.423309,0.014435,0.014435,...,0.033831,0.042608,0.624631,0.528180,0.420534,0.008971,0.020818,0.010396,0.201099,0.085414
2013-01-02 00:00:00,0.453966,0.032529,0.032529,0.069007,0.481337,0.034545,0.034545,0.529012,0.054569,0.054569,...,0.089495,0.071992,0.293770,0.254937,0.203339,0.012909,0.011767,0.011465,0.675767,0.309599
2013-01-02 12:00:00,0.440688,0.008941,0.008941,0.019673,0.468406,0.010113,0.010113,0.517474,0.025165,0.025165,...,0.035869,0.047803,0.575891,0.517875,0.440059,0.006932,0.005472,0.007200,0.633523,0.281173
2013-01-03 00:00:00,0.763992,0.011339,0.011339,0.024854,0.801316,0.016118,0.016118,0.763201,0.024184,0.024184,...,0.010673,0.015378,0.719793,0.615593,0.562894,0.002584,0.012989,0.006217,0.982853,0.904390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-29 12:00:00,0.352212,0.028215,0.028215,0.020343,0.371327,0.023037,0.023037,0.388126,0.023994,0.023994,...,0.040151,0.049344,0.565847,0.485367,0.437372,0.004073,0.010061,0.012358,0.483384,0.179694
2013-12-30 00:00:00,0.244872,0.140841,0.140841,0.132179,0.246074,0.138753,0.138753,0.243761,0.140353,0.140353,...,0.062447,0.057506,0.946048,0.932963,0.881106,0.003721,0.003262,0.000984,0.712193,0.528867
2013-12-30 12:00:00,0.265229,0.074521,0.074521,0.069523,0.280216,0.072137,0.072137,0.319388,0.074391,0.074391,...,0.018966,0.017309,0.979809,0.961056,0.944532,0.002744,0.000000,0.002058,1.000000,0.999514
2013-12-31 00:00:00,0.233070,0.141873,0.141873,0.131478,0.222680,0.138280,0.138280,0.217664,0.137900,0.137900,...,0.040491,0.031803,0.795082,0.743832,0.665111,0.008380,0.016469,0.018503,0.991346,0.904180
2013-12-31 12:00:00,0.243807,0.069545,0.069545,0.064545,0.223940,0.066223,0.066223,0.281611,0.069769,0.069769,...,0.026025,0.018351,0.939884,0.901816,0.853446,0.009371,0.006070,0.004290,0.905098,0.783141

In [14]:
n.generators.loc[n.generators.index.str.contains('cluster')]

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_nom_set,p_min_pu,...,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,location,unit
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 0 solar-hsat cluster,DE0 0 cluster,PQ,,0.0,0.0,True,0.0,1000.000000,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DE0 0 4 solar cluster,DE0 0 cluster,PQ,,0.0,0.0,True,0.0,1000.000000,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DE0 0 4 onwind cluster,DE0 0 cluster,PQ,,0.0,0.0,True,0.0,267.204664,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DE0 0 3 onwind cluster,DE0 0 cluster,PQ,,0.0,0.0,True,0.0,732.795336,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DE0 11 4 solar cluster,DE0 11 cluster,PQ,,0.0,0.0,True,0.0,0.506037,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NO1 0 0 solar-hsat cluster,NO1 0 cluster,PQ,,0.0,0.0,True,0.0,1000.000000,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
NO1 0 4 solar cluster,NO1 0 cluster,PQ,,0.0,0.0,True,0.0,764.808856,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
NO1 0 3 solar cluster,NO1 0 cluster,PQ,,0.0,0.0,True,0.0,235.191144,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
NO1 0 4 onwind cluster,NO1 0 cluster,PQ,,0.0,0.0,True,0.0,169.547658,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
NO1 0 3 onwind cluster,NO1 0 cluster,PQ,,0.0,0.0,True,0.0,830.452342,NaN,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,

**Links of the Cluster Addition**

In [15]:
def add_cluster_links(n, nodes_with_clusters, cluster_cost_reduction, ongrid):

    for node in nodes_with_clusters:

        ### H2 Electrolysis ###

        link_name = f"{node} H2 Electrolysis"

        n.add(
            "Link",
            name=link_name + " cluster",
            bus0=n.links.at[link_name, "bus0"] + " cluster",
            bus1=n.links.at[link_name, "bus1"] + " cluster",
            p_nom_extendable=n.links.at[link_name, "p_nom_extendable"],
            carrier=n.links.at[link_name, "carrier"],
            efficiency=n.links.at[link_name, "efficiency"],
            capital_cost=n.links.at[link_name, "capital_cost"]*(1-cluster_cost_reduction),
            marginal_cost=n.links.at[link_name, "marginal_cost"]*(1-cluster_cost_reduction),
            lifetime=n.links.at[link_name, "lifetime"],
            reversed=False,
            overwrite=True,
        )

        ### Methanolization ###

        ### Methanolization ###

        link_name = f"{node} methanolisation"
        cluster_methanol_bus_name = f"{node} methanol cluster"

        n.add(
            "Link",
            name=link_name + " cluster",
            bus0=n.links.at[link_name, "bus0"] + " cluster",
            bus1=cluster_methanol_bus_name,
            bus2=n.links.at[link_name, "bus2"] + " cluster",
            bus3=n.links.at[link_name, "bus3"],
            bus4=n.links.at[link_name, "bus4"],
            p_nom_extendable=n.links.at[link_name, "p_nom_extendable"],
            p_min_pu=n.links.at[link_name, "p_min_pu"],
            carrier=n.links.at[link_name, "carrier"],
            efficiency=n.links.at[link_name, "efficiency"],
            efficiency2=n.links.at[link_name, "efficiency2"],
            efficiency3=n.links.at[link_name, "efficiency3"],
            efficiency4=n.links.at[link_name, "efficiency4"],
            capital_cost=n.links.at[link_name, "capital_cost"]*(1-cluster_cost_reduction),
            marginal_cost=n.links.at[link_name, "marginal_cost"]*(1-cluster_cost_reduction),
            lifetime=n.links.at[link_name, "lifetime"],
            reversed=False,
            overwrite=True,
        )

        n.add(
            "Link",
            name=f"{node} methanol cluster",
            bus0=cluster_methanol_bus_name,
            bus1=n.links.at[link_name, "bus1"],
            p_nom_extendable=True,
            carrier=n.buses.loc[n.links.at[link_name, "bus1"], "carrier"],  
            efficiency=1.0,
            capital_cost=0.0,
            marginal_cost=0.0,
            reversed=False,
            overwrite=True,


        )

    if ongrid==True :

        ### Electricity connection to grid ###

        link_name = f"{node} electricity cluster"
        
        n.add(
            "Link",
            name=link_name,
            bus0=f"{node} cluster",
            bus1=f"{node}",
            carrier=n.buses.at[f"{node}", "carrier"],  
            p_nom_extendable=True,
            efficiency=1.0,
            capital_cost=0.0,
            marginal_cost=0.0,
            reversed=False,
            overwrite=True,
        )

        link_name = f"{node} electricity cluster back"
        n.add(
            "Link",
            name=link_name,
            bus0=f"{node}",
            bus1=f"{node} cluster",
            carrier=n.buses.at[f"{node}", "carrier"],  
            p_nom_extendable=True,
            efficiency=1.0,
            capital_cost=0.0,
            marginal_cost=0.0,
            reversed=True,
            overwrite=True,
        )

    else:
        if f"{node} cluster electricity" in n.links.index:
            n.remove(
                "Link",
                name=f"{node} cluster electricity",
            )
        if f"{node} cluster electricity back" in n.links.index:
            n.remove(
                "Link",
                name=f"{node} cluster electricity back",
            )

    return n

n = add_cluster_links(n, nodes_with_clusters, cluster_cost_reduction, ongrid)

WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster', 'DE0 2 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster', 'DE0 2 methanolisation cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster', 'DE0 2 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster', 'DE0 2 methanolisation cluster'],
      dtype='object', name='name')

In [16]:
n.links.loc[n.links.index.str.contains("methanolisation cluster")]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 methanolisation cluster,DE0 0 H2 cluster,DE0 0 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
DE0 1 methanolisation cluster,DE0 1 H2 cluster,DE0 1 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
DE0 10 methanolisation cluster,DE0 10 H2 cluster,DE0 10 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
DE0 11 methanolisation cluster,DE0 11 H2 cluster,DE0 11 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
DE0 12 methanolisation cluster,DE0 12 H2 cluster,DE0 12 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 5 methanolisation cluster,SE1 5 H2 cluster,SE1 5 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 6 methanolisation cluster,SE1 6 H2 cluster,SE1 6 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 7 methanolisation cluster,SE1 7 H2 cluster,SE1 7 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 methanolisation cluster,SE1 8 H2 cluster,SE1 8 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 methanolisation cluster,SE1 9 H2 cluster,SE1 9 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

**Storages of the Cluster Addition**

In [17]:
def add_cluster_storages(n, nodes_with_clusters, cluster_cost_reduction):

    for node in nodes_with_clusters:

        link_name = f"{node} H2 Store"

    
        n.add("Store",
            name=link_name + " cluster",
            bus=n.stores.at[link_name, "bus"] + " cluster",
            carrier=n.stores.at[link_name, "carrier"],
            e_nom_extendable=True,
            capital_cost=n.stores.at[link_name, "capital_cost"]*(1-cluster_cost_reduction),
            marginal_cost=n.stores.at[link_name, "marginal_cost"]*(1-cluster_cost_reduction),
            e_initial_per_period=n.stores.at[link_name, "e_initial_per_period"],
            e_cyclic=n.stores.at[link_name, "e_cyclic"],
            e_cyclic_per_period=n.stores.at[link_name, "e_cyclic_per_period"],
            overwrite=True,
            )
        
        link_name = f"{node} battery"


        n.add(
                "Link",
                name=link_name + " charger cluster",
                bus0=f"{node} cluster",
                bus1=f"{node} battery cluster",
                carrier=n.buses.at[link_name, "carrier"],   
                p_nom_extendable=True,
                efficiency=1.0,
                capital_cost=0.0,
                marginal_cost=0.0,
                reversed=False,
                overwrite=True,
            )
        n.add(
                "Link",
                name=link_name + " discharger cluster",
                bus0=f"{node} battery cluster",
                bus1=f"{node} cluster",
                carrier=n.buses.at[link_name, "carrier"],
                p_nom_extendable=True,
                efficiency=1.0,
                capital_cost=0.0,
                marginal_cost=0.0,
                reversed=True,
                overwrite=True,
            )

        n.add("Store",
            name=link_name + " cluster" ,
            bus=f"{node} battery cluster",
            carrier=n.stores.at[link_name, "carrier"],
            e_nom_extendable=True,
            capital_cost=n.stores.at[link_name, "capital_cost"]*(1-cluster_cost_reduction),
            marginal_cost=n.stores.at[link_name, "marginal_cost"]*(1-cluster_cost_reduction),
            e_initial_per_period=n.stores.at[link_name, "e_initial_per_period"],
            e_cyclic=n.stores.at[link_name, "e_cyclic"],
            e_cyclic_per_period=n.stores.at[link_name, "e_cyclic_per_period"],
            overwrite=True,
            )
    return n

n = add_cluster_storages(n, nodes_with_clusters, cluster_cost_reduction)

WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster', 'DE0 2 methanol cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'DE0 3 methanol cluster', 'GB2 1 H2 Electrolysis cluster',
       'GB2 1 methanolisation cluster', 'GB2 1 methanol cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'GB2 2 methanol cluster', 'NO1 1 H2 Electrolysis cluster',
       'NO1 1 methanolisation cluster', 'NO1 1 methanol cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 2 methanol cluster', 'NO1 3 H2 Electrolysis cluster',
       'NO1 3 methanolisation cluster', 'NO1 3 methanol cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 4 methanol cluster', 'NO1 5 H2 Electrolysis cluster',
       'NO1 5 methanolisation cluster', 'NO1 5 methanol cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 6 methanol cluster', 'NO1 7 H2 Electrolysis cluster',
       'NO1 7 methanolisation cluster', 'NO1 7 methanol cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 8 methanol cluster', 'NO1 9 H2 Electrolysis cluster',
       'NO1 9 methanolisation cluster', 'NO1 9 methanol cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 0 methanol cluster', 'SE1 1 H2 Electrolysis cluster',
       'SE1 1 methanolisation cluster', 'SE1 1 methanol cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 10 methanol cluster', 'SE1 2 H2 Electrolysis cluster',
       'SE1 2 methanolisation cluster', 'SE1 2 methanol cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 3 methanol cluster', 'SE1 4 H2 Electrolysis cluster',
       'SE1 4 methanolisation cluster', 'SE1 4 methanol cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 5 methanol cluster', 'SE1 6 H2 Electrolysis cluster',
       'SE1 6 methanolisation cluster', 'SE1 6 methanol cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 7 methanol cluster', 'SE1 8 H2 Electrolysis cluster',
       'SE1 8 methanolisation cluster', 'SE1 8 methanol cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster',
       'SE1 9 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'GB2 1 H2 Electrolysis cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'NO1 1 H2 Electrolysis cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 3 H2 Electrolysis cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 5 H2 Electrolysis cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 7 H2 Electrolysis cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 9 H2 Electrolysis cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 1 H2 Electrolysis cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 2 H2 Electrolysis cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 4 H2 Electrolysis cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 6 H2 Electrolysis cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 8 H2 Electrolysis cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 methanolisation cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 methanolisation cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 methanolisation cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 methanolisation cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 methanolisation cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 methanolisation cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 methanolisation cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 methanolisation cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 methanolisation cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 methanolisation cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 methanolisation cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster', 'DE0 2 methanol cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'DE0 3 methanol cluster', 'GB2 1 H2 Electrolysis cluster',
       'GB2 1 methanolisation cluster', 'GB2 1 methanol cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'GB2 2 methanol cluster', 'NO1 1 H2 Electrolysis cluster',
       'NO1 1 methanolisation cluster', 'NO1 1 methanol cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 2 methanol cluster', 'NO1 3 H2 Electrolysis cluster',
       'NO1 3 methanolisation cluster', 'NO1 3 methanol cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 4 methanol cluster', 'NO1 5 H2 Electrolysis cluster',
       'NO1 5 methanolisation cluster', 'NO1 5 methanol cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 6 methanol cluster', 'NO1 7 H2 Electrolysis cluster',
       'NO1 7 methanolisation cluster', 'NO1 7 methanol cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 8 methanol cluster', 'NO1 9 H2 Electrolysis cluster',
       'NO1 9 methanolisation cluster', 'NO1 9 methanol cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 0 methanol cluster', 'SE1 1 H2 Electrolysis cluster',
       'SE1 1 methanolisation cluster', 'SE1 1 methanol cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 10 methanol cluster', 'SE1 2 H2 Electrolysis cluster',
       'SE1 2 methanolisation cluster', 'SE1 2 methanol cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 3 methanol cluster', 'SE1 4 H2 Electrolysis cluster',
       'SE1 4 methanolisation cluster', 'SE1 4 methanol cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 5 methanol cluster', 'SE1 6 H2 Electrolysis cluster',
       'SE1 6 methanolisation cluster', 'SE1 6 methanol cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 7 methanol cluster', 'SE1 8 H2 Electrolysis cluster',
       'SE1 8 methanolisation cluster', 'SE1 8 methanol cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster',
       'SE1 9 methanol cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'GB2 1 H2 Electrolysis cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'NO1 1 H2 Electrolysis cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 3 H2 Electrolysis cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 5 H2 Electrolysis cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 7 H2 Electrolysis cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 9 H2 Electrolysis cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 1 H2 Electrolysis cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 2 H2 Electrolysis cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 4 H2 Electrolysis cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 6 H2 Electrolysis cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 8 H2 Electrolysis cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 methanolisation cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 methanolisation cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 methanolisation cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 methanolisation cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 methanolisation cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 methanolisation cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 methanolisation cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 methanolisation cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 methanolisation cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 methanolisation cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 methanolisation cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following stores have buses which are not defined:
Index(['DE0 1 H2 Store cluster'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster', 'DE0 2 methanol cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'DE0 3 methanol cluster', 'GB2 1 H2 Electrolysis cluster',
       'GB2 1 methanolisation cluster', 'GB2 1 methanol cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'GB2 2 methanol cluster', 'NO1 1 H2 Electrolysis cluster',
       'NO1 1 methanolisation cluster', 'NO1 1 methanol cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 2 methanol cluster', 'NO1 3 H2 Electrolysis cluster',
       'NO1 3 methanolisation cluster', 'NO1 3 methanol cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 4 methanol cluster', 'NO1 5 H2 Electrolysis cluster',
       'NO1 5 methanolisation cluster', 'NO1 5 methanol cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 6 methanol cluster', 'NO1 7 H2 Electrolysis cluster',
       'NO1 7 methanolisation cluster', 'NO1 7 methanol cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 8 methanol cluster', 'NO1 9 H2 Electrolysis cluster',
       'NO1 9 methanolisation cluster', 'NO1 9 methanol cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 0 methanol cluster', 'SE1 1 H2 Electrolysis cluster',
       'SE1 1 methanolisation cluster', 'SE1 1 methanol cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 10 methanol cluster', 'SE1 2 H2 Electrolysis cluster',
       'SE1 2 methanolisation cluster', 'SE1 2 methanol cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 3 methanol cluster', 'SE1 4 H2 Electrolysis cluster',
       'SE1 4 methanolisation cluster', 'SE1 4 methanol cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 5 methanol cluster', 'SE1 6 H2 Electrolysis cluster',
       'SE1 6 methanolisation cluster', 'SE1 6 methanol cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 7 methanol cluster', 'SE1 8 H2 Electrolysis cluster',
       'SE1 8 methanolisation cluster', 'SE1 8 methanol cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster',
       'SE1 9 methanol cluster', 'DE0 1 battery charger cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 2 H2 Electrolysis cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'GB2 1 H2 Electrolysis cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'NO1 1 H2 Electrolysis cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 3 H2 Electrolysis cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 5 H2 Electrolysis cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 7 H2 Electrolysis cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 9 H2 Electrolysis cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 1 H2 Electrolysis cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 2 H2 Electrolysis cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 4 H2 Electrolysis cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 6 H2 Electrolysis cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 8 H2 Electrolysis cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster',
       'DE0 1 battery charger cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 methanolisation cluster', 'DE0 2 methanolisation cluster',
       'DE0 3 methanolisation cluster', 'GB2 1 methanolisation cluster',
       'GB2 2 methanolisation cluster', 'NO1 1 methanolisation cluster',
       'NO1 2 methanolisation cluster', 'NO1 3 methanolisation cluster',
       'NO1 4 methanolisation cluster', 'NO1 5 methanolisation cluster',
       'NO1 6 methanolisation cluster', 'NO1 7 methanolisation cluster',
       'NO1 8 methanolisation cluster', 'NO1 9 methanolisation cluster',
       'SE1 0 methanolisation cluster', 'SE1 1 methanolisation cluster',
       'SE1 10 methanolisation cluster', 'SE1 2 methanolisation cluster',
       'SE1 3 methanolisation cluster', 'SE1 4 methanolisation cluster',
       'SE1 5 methanolisation cluster', 'SE1 6 methanolisation cluster',
       'SE1 7 methanolisation cluster', 'SE1 8 methanolisation cluster',
       'SE1 9 methanolisation cluster'],
      dtype='object', name='name')
WARNING:pypsa.consistency:The following links have buses which are not defined:
Index(['DE0 1 H2 Electrolysis cluster', 'DE0 1 methanolisation cluster',
       'DE0 1 methanol cluster', 'DE0 2 H2 Electrolysis cluster',
       'DE0 2 methanolisation cluster', 'DE0 2 methanol cluster',
       'DE0 3 H2 Electrolysis cluster', 'DE0 3 methanolisation cluster',
       'DE0 3 methanol cluster', 'GB2 1 H2 Electrolysis cluster',
       'GB2 1 methanolisation cluster', 'GB2 1 methanol cluster',
       'GB2 2 H2 Electrolysis cluster', 'GB2 2 methanolisation cluster',
       'GB2 2 methanol cluster', 'NO1 1 H2 Electrolysis cluster',
       'NO1 1 methanolisation cluster', 'NO1 1 methanol cluster',
       'NO1 2 H2 Electrolysis cluster', 'NO1 2 methanolisation cluster',
       'NO1 2 methanol cluster', 'NO1 3 H2 Electrolysis cluster',
       'NO1 3 methanolisation cluster', 'NO1 3 methanol cluster',
       'NO1 4 H2 Electrolysis cluster', 'NO1 4 methanolisation cluster',
       'NO1 4 methanol cluster', 'NO1 5 H2 Electrolysis cluster',
       'NO1 5 methanolisation cluster', 'NO1 5 methanol cluster',
       'NO1 6 H2 Electrolysis cluster', 'NO1 6 methanolisation cluster',
       'NO1 6 methanol cluster', 'NO1 7 H2 Electrolysis cluster',
       'NO1 7 methanolisation cluster', 'NO1 7 methanol cluster',
       'NO1 8 H2 Electrolysis cluster', 'NO1 8 methanolisation cluster',
       'NO1 8 methanol cluster', 'NO1 9 H2 Electrolysis cluster',
       'NO1 9 methanolisation cluster', 'NO1 9 methanol cluster',
       'SE1 0 H2 Electrolysis cluster', 'SE1 0 methanolisation cluster',
       'SE1 0 methanol cluster', 'SE1 1 H2 Electrolysis cluster',
       'SE1 1 methanolisation cluster', 'SE1 1 methanol cluster',
       'SE1 10 H2 Electrolysis cluster', 'SE1 10 methanolisation cluster',
       'SE1 10 methanol cluster', 'SE1 2 H2 Electrolysis cluster',
       'SE1 2 methanolisation cluster', 'SE1 2 methanol cluster',
       'SE1 3 H2 Electrolysis cluster', 'SE1 3 methanolisation cluster',
       'SE1 3 methanol cluster', 'SE1 4 H2 Electrolysis cluster',
       'SE1 4 methanolisation cluster', 'SE1 4 methanol cluster',
       'SE1 5 H2 Electrolysis cluster', 'SE1 5 methanolisation cluster',
       'SE1 5 methanol cluster', 'SE1 6 H2 Electrolysis cluster',
       'SE1 6 methanolisation cluster', 'SE1 6 methanol cluster',
       'SE1 7 H2 Electrolysis cluster', 'SE1 7 methanolisation cluster',
       'SE1 7 methanol cluster', 'SE1 8 H2 Electrolysis cluster',
       'SE1 8 methanolisation cluster', 'SE1 8 methanol cluster',
       'SE1 9 H2 Electrolysis cluster', 'SE1 9 methanolisation cluster',
       'SE1 9 methanol cluster', 'DE0 1 battery charger cluster',
       'DE0 1 battery discharger cluster'],
      dtype='object', name='name')

In [18]:
n.links["reversed"] = n.links["reversed"].fillna(False).astype(bool)

**Printing to Check**

In [19]:
n.links.loc[n.links["bus1"].str.contains('methanol')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 solid biomass biomass-to-methanol,DE0 0 solid biomass,EU methanol,,biomass-to-methanol,0.6500,True,0,20.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 1 solid biomass biomass-to-methanol,DE0 1 solid biomass,EU methanol,,biomass-to-methanol,0.6500,True,0,20.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 10 solid biomass biomass-to-methanol,DE0 10 solid biomass,EU methanol,,biomass-to-methanol,0.6500,True,0,20.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 11 solid biomass biomass-to-methanol,DE0 11 solid biomass,EU methanol,,biomass-to-methanol,0.6500,True,0,20.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 12 solid biomass biomass-to-methanol,DE0 12 solid biomass,EU methanol,,biomass-to-methanol,0.6500,True,0,20.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 7 methanol cluster,SE1 7 methanol cluster,EU methanol,,methanol,1.0000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 methanolisation cluster,SE1 8 H2 cluster,SE1 8 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 methanol cluster,SE1 8 methanol cluster,EU methanol,,methanol,1.0000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 methanolisation cluster,SE1 9 H2 cluster,SE1 9 methanol cluster,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 methanol cluster,SE1 9 methanol cluster,EU methanol,,methanol,1.0000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [20]:
n.links.loc[n.links.index.str.contains("Electrolysis")]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 H2 Electrolysis,DE0 0,DE0 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 1 H2 Electrolysis,DE0 1,DE0 1 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 10 H2 Electrolysis,DE0 10,DE0 10 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 11 H2 Electrolysis,DE0 11,DE0 11 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 12 H2 Electrolysis,DE0 12,DE0 12 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 5 H2 Electrolysis cluster,SE1 5 cluster,SE1 5 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 6 H2 Electrolysis cluster,SE1 6 cluster,SE1 6 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 7 H2 Electrolysis cluster,SE1 7 cluster,SE1 7 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 H2 Electrolysis cluster,SE1 8 cluster,SE1 8 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 H2 Electrolysis cluster,SE1 9 cluster,SE1 9 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [21]:
n.links.loc[n.links["carrier"].str.contains('H2 Electrolysis')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 H2 Electrolysis,DE0 0,DE0 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 1 H2 Electrolysis,DE0 1,DE0 1 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 10 H2 Electrolysis,DE0 10,DE0 10 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 11 H2 Electrolysis,DE0 11,DE0 11 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 12 H2 Electrolysis,DE0 12,DE0 12 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 5 H2 Electrolysis cluster,SE1 5 cluster,SE1 5 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 6 H2 Electrolysis cluster,SE1 6 cluster,SE1 6 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 7 H2 Electrolysis cluster,SE1 7 cluster,SE1 7 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 H2 Electrolysis cluster,SE1 8 cluster,SE1 8 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 H2 Electrolysis cluster,SE1 9 cluster,SE1 9 H2 cluster,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [22]:
n.buses.loc[n.buses.index.str.contains("cluster")]

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network,country,substation_lv,substation_off
name,,,,,,,,,,,,,,,,
DE0 0 cluster,380.0,,11.778928,51.997389,AC,MWh_el,DE0 0,1.0,0.0,inf,Slack,,,DE,1.0,1.0
DE0 0 H2 cluster,1.0,,11.778928,51.997389,H2,MWh_LHV,DE0 0,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 0 methanol cluster,1.0,,11.778928,51.997389,methanol,MWh_th,DE0 0,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 0 battery cluster,1.0,,11.778928,51.997389,battery,MWh_el,DE0 0,1.0,0.0,inf,PQ,,,DE,NaN,NaN
DE0 11 cluster,380.0,,10.426224,47.834642,AC,MWh_el,DE0 11,1.0,0.0,inf,PQ,,,DE,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NL0 8 battery cluster,1.0,,4.737308,51.809393,battery,MWh_el,NL0 8,1.0,0.0,inf,PQ,,,NL,NaN,NaN
NO1 0 cluster,380.0,,6.268203,59.324070,AC,MWh_el,NO1 0,1.0,0.0,inf,PQ,,,NO,1.0,1.0
NO1 0 H2 cluster,1.0,,6.268203,59.324070,H2,MWh_LHV,NO1 0,1.0,0.0,inf,PQ,,,NO,NaN,NaN
NO1 0 methanol cluster,1.0,,6.268203,59.324070,methanol,MWh_th,NO1 0,1.0,0.0,inf,PQ,,,NO,NaN,NaN
NO1 0 battery cluster,1.0,,6.268203,59.324070,battery,MWh_el,NO1 0,1.0,0.0,inf,PQ,,,NO,NaN,NaN

In [23]:
n.stores.loc[n.stores.index.str.contains("cluster")]

,bus,type,carrier,e_nom,e_nom_mod,e_nom_extendable,e_nom_min,e_nom_max,e_nom_set,e_min_pu,...,marginal_cost,marginal_cost_quadratic,marginal_cost_storage,capital_cost,standing_loss,active,build_year,lifetime,e_nom_opt,location
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 H2 Store cluster,DE0 0 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,89.430064,0.0,True,0,inf,0.0,NaN
DE0 0 battery cluster,DE0 0 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
DE0 1 H2 Store cluster,DE0 1 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
DE0 1 battery cluster,DE0 1 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
DE0 10 H2 Store cluster,DE0 10 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 7 battery cluster,SE1 7 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
SE1 8 H2 Store cluster,SE1 8 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
SE1 8 battery cluster,SE1 8 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
SE1 9 H2 Store cluster,SE1 9 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
SE1 9 battery cluster,SE1 9 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN

In [24]:
n.links.loc[n.links["carrier"]=='DC']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
relation/13295785-515-DC,NO1 0,GB2 13,,DC,0.964498,True,0,inf,1400.0,0.0,...,0.0,relation/13295785,LINESTRING (-1.5404269162550226 55.14647596191...,1.0,0.983350,,NaN,,False,685.235419
relation/14126301-450-DC,GB2 10,NL0 7,,DC,0.974115,True,0,inf,1000.0,0.0,...,0.0,relation/14126301,LINESTRING (0.7161575436002887 51.440498299145...,1.0,0.977109,,NaN,,False,258.841749
relation/15775538-600-DC,GB2 11,GB2 15,,DC,0.973505,True,0,inf,2250.0,0.0,...,0.0,relation/15775538,LINESTRING (-4.894821189854914 55.718036768358...,1.0,0.892448,,NaN,,False,285.796500
relation/15781671-525-DC,GB2 8,DK0 0,,DC,0.963421,True,0,inf,1400.0,0.0,...,0.0,relation/15781671,LINESTRING (-0.2365005345670103 52.92099253311...,1.0,0.816407,,NaN,,False,733.286547
relation/16213216-525-DC,DE0 24,NO1 0,,DC,0.966595,True,0,inf,1400.0,0.0,...,0.0,relation/16213216,LINESTRING (6.7544309946114405 58.669060406684...,1.0,0.802530,,NaN,,False,591.911880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DC42-reversed,DE0 13,DE0 9,,DC,0.968206,True,2037,inf,0.0,0.0,...,1.0,"{""url"":""https://data.netzausbau.de/2037-2023/N...","LINESTRING (10.5331297 53.5252973, 9.0113444 4...",NaN,0.000000,confirmed,NaN,,True,520.333441
DC42plus-reversed,DE0 22,DE0 9,,DC,0.970511,True,2037,inf,0.0,0.0,...,1.0,"{""url"":""https://data.netzausbau.de/2037-2023/N...","LINESTRING (10.5331297 53.5252973, 9.6151453 4...",NaN,0.000000,confirmed,NaN,,True,418.165996
DC5-reversed,DE0 5,DE0 0,,DC,0.970153,True,2027,inf,0.0,0.0,...,1.0,{url:https://www.netzentwicklungsplan.de/sites...,"LINESTRING (11.6267388 52.2484924, 11.5745421 ...",NaN,0.000000,in_permitting,NaN,,True,434.000757
DC20-reversed,DE0 5,DE0 34,,DC,0.966917,True,2030,inf,0.0,0.0,...,1.0,{url:https://www.netzentwicklungsplan.de/sites...,"LINESTRING (11.3482229 53.6044461, 11.5745421 ...",NaN,0.000000,in_permitting,NaN,,True,577.605874
TYNDP2024_1229-reversed,DE0 20,DE0 16,,DC,0.971775,True,2035,inf,0.0,0.0,...,1.0,"{name:Rhine-Main-Link,url:{name:TYNDP2024_1229...","LINESTRING (8.379 53.315, 8.435 50.078)",NaN,0.000000,in_permitting,NaN,,True,362.213276

In [25]:
n.stores

,bus,type,carrier,e_nom,e_nom_mod,e_nom_extendable,e_nom_min,e_nom_max,e_nom_set,e_min_pu,...,marginal_cost,marginal_cost_quadratic,marginal_cost_storage,capital_cost,standing_loss,active,build_year,lifetime,e_nom_opt,location
name,,,,,,,,,,,,,,,,,,,,,
co2 atmosphere,co2 atmosphere,,co2,0.0,0.0,True,0.0,inf,NaN,-1.0,...,0.0,0.0,0.0,0.000000,0.0,True,0,inf,0.0,
DE0 0 co2 stored,DE0 0 co2 stored,,co2 stored,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,247.607546,0.0,True,0,inf,0.0,
DE0 1 co2 stored,DE0 1 co2 stored,,co2 stored,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,247.607546,0.0,True,0,inf,0.0,
DE0 10 co2 stored,DE0 10 co2 stored,,co2 stored,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,247.607546,0.0,True,0,inf,0.0,
DE0 11 co2 stored,DE0 11 co2 stored,,co2 stored,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,247.607546,0.0,True,0,inf,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 7 battery cluster,SE1 7 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
SE1 8 H2 Store cluster,SE1 8 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
SE1 8 battery cluster,SE1 8 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN
SE1 9 H2 Store cluster,SE1 9 H2 cluster,,H2 Store,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,2224.975719,0.0,True,0,inf,0.0,NaN
SE1 9 battery cluster,SE1 9 battery cluster,,battery,0.0,0.0,True,0.0,inf,NaN,0.0,...,0.0,0.0,0.0,6427.168612,0.0,True,0,inf,0.0,NaN

In [26]:
n.links.loc[n.links["bus0"]=='EU methanol']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
DE0 0 OCGT methanol,EU methanol,DE0 0,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 1 OCGT methanol,EU methanol,DE0 1,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 10 OCGT methanol,EU methanol,DE0 10,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 11 OCGT methanol,EU methanol,DE0 11,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
DE0 12 OCGT methanol,EU methanol,DE0 12,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 7 OCGT methanol,EU methanol,SE1 7,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
SE1 8 OCGT methanol,EU methanol,SE1 8,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
SE1 9 OCGT methanol,EU methanol,SE1 9,,OCGT methanol,0.43,True,0,25.0,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
EU industry methanol,EU methanol,EU industry methanol,,industry methanol,1.00,True,0,inf,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0
EU shipping methanol,EU methanol,EU shipping methanol,,shipping methanol,1.00,True,0,inf,0.0,0.0,...,NaN,,,NaN,NaN,,NaN,,False,0.0

In [27]:
n.carriers

,co2_emissions,color,nice_name,max_growth,max_relative_growth
name,,,,,
AC,0.0,#70af1d,AC,inf,0.0
DC,0.0,#8a1caf,DC,inf,0.0
nuclear,0.0,#ff8c00,nuclear,inf,0.0
solar-hsat,0.0,#fdb915,solar-hsat,inf,0.0
offwind-ac,0.0,#6895dd,Offshore Wind (AC),inf,0.0
...,...,...,...,...,...
oil refining,0.0,#e6e6e6,oil refining,inf,0.0
home battery discharger,0.0,#3c5221,home battery discharger,inf,0.0
rural ground heat pump,0.0,#2fb537,rural ground heat pump,inf,0.0
urban decentral air heat pump,0.0,#36eb41,urban decentral air heat pump,inf,0.0
gas pipeline,0.0,#ebbca0,gas pipeline,inf,0.0

In [28]:
n.global_constraints

,type,investment_period,bus,carrier_attribute,sense,constant,mu
name,,,,,,,
lv_limit,transmission_volume_expansion_limit,NaN,,"AC, DC",<=,9.795462e+07,0.0
biomass limit,operational_limit,NaN,,solid biomass,<=,3.278577e+08,0.0
CO2Limit,co2_atmosphere,NaN,,co2_emissions,<=,0.000000e+00,0.0

In [29]:
n.loads

,bus,carrier,type,p_set,q_set,sign,active
name,,,,,,,
DE0 0,DE0 0 low voltage,electricity,,0.0,0.0,-1.0,True
DE0 1,DE0 1 low voltage,electricity,,0.0,0.0,-1.0,True
DE0 10,DE0 10 low voltage,electricity,,0.0,0.0,-1.0,True
DE0 11,DE0 11 low voltage,electricity,,0.0,0.0,-1.0,True
DE0 12,DE0 12 low voltage,electricity,,0.0,0.0,-1.0,True
...,...,...,...,...,...,...,...
SE1 7 urban decentral heat,SE1 7 urban decentral heat,urban decentral heat,,0.0,0.0,-1.0,True
SE1 8 rural heat,SE1 8 rural heat,rural heat,,0.0,0.0,-1.0,True
SE1 8 urban decentral heat,SE1 8 urban decentral heat,urban decentral heat,,0.0,0.0,-1.0,True
SE1 9 rural heat,SE1 9 rural heat,rural heat,,0.0,0.0,-1.0,True
SE1 9 urban decentral heat,SE1 9 urban decentral heat,urban decentral heat,,0.0,0.0,-1.0,True

In [30]:
n.links

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,under_construction,tags,geometry,dc,underwater_fraction,project_status,energy to power ratio,location,reversed,length_original
name,,,,,,,,,,,,,,,,,,,,,
relation/13295785-515-DC,NO1 0,GB2 13,,DC,0.964498,True,0,inf,1400.0,0.0,...,0.0,relation/13295785,LINESTRING (-1.5404269162550226 55.14647596191...,1.0,0.983350,,NaN,,False,685.235419
relation/14126301-450-DC,GB2 10,NL0 7,,DC,0.974115,True,0,inf,1000.0,0.0,...,0.0,relation/14126301,LINESTRING (0.7161575436002887 51.440498299145...,1.0,0.977109,,NaN,,False,258.841749
relation/15775538-600-DC,GB2 11,GB2 15,,DC,0.973505,True,0,inf,2250.0,0.0,...,0.0,relation/15775538,LINESTRING (-4.894821189854914 55.718036768358...,1.0,0.892448,,NaN,,False,285.796500
relation/15781671-525-DC,GB2 8,DK0 0,,DC,0.963421,True,0,inf,1400.0,0.0,...,0.0,relation/15781671,LINESTRING (-0.2365005345670103 52.92099253311...,1.0,0.816407,,NaN,,False,733.286547
relation/16213216-525-DC,DE0 24,NO1 0,,DC,0.966595,True,0,inf,1400.0,0.0,...,0.0,relation/16213216,LINESTRING (6.7544309946114405 58.669060406684...,1.0,0.802530,,NaN,,False,591.911880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SE1 7 battery discharger cluster,SE1 7 battery cluster,SE1 7 cluster,,battery,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
SE1 8 battery charger cluster,SE1 8 cluster,SE1 8 battery cluster,,battery,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 8 battery discharger cluster,SE1 8 battery cluster,SE1 8 cluster,,battery,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
SE1 9 battery charger cluster,SE1 9 cluster,SE1 9 battery cluster,,battery,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
SE1 9 battery discharger cluster,SE1 9 battery cluster,SE1 9 cluster,,battery,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN

In [31]:
n.links.loc[n.links.index.str.contains("cluster"),n.links.columns.str.contains("bus")]

,bus0,bus1,bus4,bus3,bus2
name,,,,,
DE0 0 H2 Electrolysis cluster,DE0 0 cluster,DE0 0 H2 cluster,,,
DE0 0 methanolisation cluster,DE0 0 H2 cluster,DE0 0 methanol cluster,DE0 0 urban central heat,DE0 0 co2 stored,DE0 0 cluster
DE0 0 methanol cluster,DE0 0 methanol cluster,EU methanol,,,
DE0 1 H2 Electrolysis cluster,DE0 1 cluster,DE0 1 H2 cluster,,,
DE0 1 methanolisation cluster,DE0 1 H2 cluster,DE0 1 methanol cluster,DE0 1 urban central heat,DE0 1 co2 stored,DE0 1 cluster
...,...,...,...,...,...
SE1 7 battery discharger cluster,SE1 7 battery cluster,SE1 7 cluster,,,
SE1 8 battery charger cluster,SE1 8 cluster,SE1 8 battery cluster,,,
SE1 8 battery discharger cluster,SE1 8 battery cluster,SE1 8 cluster,,,
SE1 9 battery charger cluster,SE1 9 cluster,SE1 9 battery cluster,,,
SE1 9 battery discharger cluster,SE1 9 battery cluster,SE1 9 cluster,,,

In [32]:
print(n.generators.loc[n.generators.index.str.contains("solar")&
    ~n.generators.index.str.contains("solar-hsat") &~n.generators.index.str.contains("solar thermal") &~n.generators.index.str.contains("solar rooftop")])

                                 bus control type        p_nom  p_nom_mod  \
name
DE0 0 0 solar                  DE0 0      PQ          4.346652        0.0
DE0 0 1 solar                  DE0 0      PQ        233.845010        0.0
DE0 0 2 solar                  DE0 0      PQ       1029.977920        0.0
DE0 0 3 solar                  DE0 0      PQ       1271.875595        0.0
DE0 0 4 solar                  DE0 0      PQ        269.082065        0.0
...                              ...     ...  ...          ...        ...
NL0 7 3 solar cluster  NL0 7 cluster      PQ          0.000000        0.0
NL0 7 2 solar cluster  NL0 7 cluster      PQ          0.000000        0.0
NL0 8 4 solar cluster  NL0 8 cluster      PQ          0.000000        0.0
NO1 0 4 solar cluster  NO1 0 cluster      PQ          0.000000        0.0
NO1 0 3 solar cluster  NO1 0 cluster      PQ          0.000000        0.0

                       p_nom_extendable    p_nom_min     p_nom_max  p_nom_set  \
name
DE0 0 0 solar                      True     4.346652    229.969033        NaN
DE0 0 1 solar                      True   233.845010   3500.112603        NaN
DE0 0 2 solar                      True  1029.977920  19745.882746        NaN
DE0 0 3 solar                      True  1271.875595  23538.563162        NaN
DE0 0 4 solar                      True   269.082065   2302.066517        NaN
...                                 ...          ...           ...        ...
NL0 7 3 solar cluster              True     0.000000    370.290861        NaN
NL0 7 2 solar cluster              True     0.000000    371.424325        NaN
NL0 8 4 solar cluster              True     0.000000   1000.000000        NaN
NO1 0 4 solar cluster              True     0.000000    764.808856        NaN
NO1 0 3 solar cluster              True     0.000000    235.191144        NaN

                       p_min_pu  ...  up_time_before  down_time_before  \
name                             ...
DE0 0 0 solar               0.0  ...               1                 0
DE0 0 1 solar               0.0  ...               1                 0
DE0 0 2 solar               0.0  ...               1                 0
DE0 0 3 solar               0.0  ...               1                 0
DE0 0 4 solar               0.0  ...               1                 0
...                         ...  ...             ...               ...
NL0 7 3 solar cluster       0.0  ...               1                 0
NL0 7 2 solar cluster       0.0  ...               1                 0
NL0 8 4 solar cluster       0.0  ...               1                 0
NO1 0 4 solar cluster       0.0  ...               1                 0
NO1 0 3 solar cluster       0.0  ...               1                 0

                       ramp_limit_up  ramp_limit_down  ramp_limit_start_up  \
name
DE0 0 0 solar                    NaN              NaN                  1.0
DE0 0 1 solar                    NaN              NaN                  1.0
DE0 0 2 solar                    NaN              NaN                  1.0
DE0 0 3 solar                    NaN              NaN                  1.0
DE0 0 4 solar                    NaN              NaN                  1.0
...                              ...              ...                  ...
NL0 7 3 solar cluster            NaN              NaN                  1.0
NL0 7 2 solar cluster            NaN              NaN                  1.0
NL0 8 4 solar cluster            NaN              NaN                  1.0
NO1 0 4 solar cluster            NaN              NaN                  1.0
NO1 0 3 solar cluster            NaN              NaN                  1.0

                       ramp_limit_shut_down weight  p_nom_opt  location  unit
name
DE0 0 0 solar                           1.0    1.0        0.0
DE0 0 1 solar                           1.0    1.0        0.0
DE0 0 2 solar                           1.0    1.0        0.0
DE0 0 3 solar                           1.0    1.0        0.0
DE0 0 4 solar                           1.0    1.0        0.0
...                                     ...    ...        ...       ...   ...
NL0 7 3 solar cluster                   1.0    1.0        0.0
NL0 7 2 solar cluster                   1.0    1.0        0.0
NL0 8 4 solar cluster                   1.0    1.0        0.0
NO1 0 4 solar cluster                   1.0    1.0        0.0
NO1 0 3 solar cluster                   1.0    1.0        0.0

[564 rows x 40 columns]

In [33]:
print(n.generators.loc[n.generators.index.str.contains("solar cluster"), n.generators.columns.isin(['p_nom_max','carrier','location','pnom_extendable'])])

                          p_nom_max carrier location
name
DE0 0 4 solar cluster   1000.000000   solar
DE0 11 4 solar cluster     0.506037   solar
DE0 11 3 solar cluster   118.699940   solar
DE0 10 2 solar cluster   260.905411   solar
DE0 10 1 solar cluster   739.094589   solar
...                             ...     ...      ...
NL0 7 3 solar cluster    370.290861   solar
NL0 7 2 solar cluster    371.424325   solar
NL0 8 4 solar cluster   1000.000000   solar
NO1 0 4 solar cluster    764.808856   solar
NO1 0 3 solar cluster    235.191144   solar

[110 rows x 3 columns]

In [34]:
n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.str.contains("cluster")]

name,DE0 0 0 solar-hsat cluster,DE0 0 4 solar cluster,DE0 0 4 onwind cluster,DE0 0 3 onwind cluster,DE0 11 0 solar-hsat cluster,DE0 11 4 solar cluster,DE0 11 3 solar cluster,DE0 10 2 solar cluster,DE0 19 4 onwind cluster,DE0 16 4 onwind cluster,...,NL0 8 0 solar-hsat cluster,NL0 8 4 solar cluster,NL0 8 4 onwind cluster,NL0 8 3 onwind cluster,NL0 8 2 onwind cluster,NO1 0 0 solar-hsat cluster,NO1 0 4 solar cluster,NO1 0 3 solar cluster,NO1 0 4 onwind cluster,NO1 0 3 onwind cluster
snapshot,,,,,,,,,,,,,,,,,,,,,
2013-01-01 00:00:00,0.032510,0.020257,0.745953,0.720592,0.085242,0.120544,0.157375,0.171789,0.999292,0.692934,...,0.018221,0.022472,0.549369,0.569623,0.596201,0.014350,0.022757,0.021922,0.706259,0.368256
2013-01-01 12:00:00,0.013129,0.012368,0.415434,0.418396,0.047798,0.075827,0.080220,0.090211,0.619978,0.785965,...,0.033831,0.042608,0.624631,0.528180,0.420534,0.008971,0.020818,0.010396,0.201099,0.085414
2013-01-02 00:00:00,0.069007,0.116865,0.626378,0.600330,0.115280,0.086783,0.099190,0.054537,0.941442,0.884405,...,0.089495,0.071992,0.293770,0.254937,0.203339,0.012909,0.011767,0.011465,0.675767,0.309599
2013-01-02 12:00:00,0.019673,0.011756,0.535699,0.552085,0.036100,0.059459,0.037807,0.036225,0.992708,0.876311,...,0.035869,0.047803,0.575891,0.517875,0.440059,0.006932,0.005472,0.007200,0.633523,0.281173
2013-01-03 00:00:00,0.024854,0.022084,0.801217,0.787516,0.041355,0.041224,0.054290,0.042639,0.999592,0.999978,...,0.010673,0.015378,0.719793,0.615593,0.562894,0.002584,0.012989,0.006217,0.982853,0.904390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-29 12:00:00,0.020343,0.032795,0.448703,0.417988,0.052077,0.011271,0.017797,0.012294,0.950465,0.979491,...,0.040151,0.049344,0.565847,0.485367,0.437372,0.004073,0.010061,0.012358,0.483384,0.179694
2013-12-30 00:00:00,0.132179,0.146524,0.302903,0.262351,0.149781,0.158531,0.118618,0.166995,0.946172,0.942079,...,0.062447,0.057506,0.946048,0.932963,0.881106,0.003721,0.003262,0.000984,0.712193,0.528867
2013-12-30 12:00:00,0.069523,0.071959,0.341143,0.335387,0.096829,0.116195,0.108920,0.096888,0.889163,0.999977,...,0.018966,0.017309,0.979809,0.961056,0.944532,0.002744,0.000000,0.002058,1.000000,0.999514
2013-12-31 00:00:00,0.131478,0.146917,0.182951,0.195347,0.173574,0.162043,0.144573,0.158288,0.741581,0.797615,...,0.040491,0.031803,0.795082,0.743832,0.665111,0.008380,0.016469,0.018503,0.991346,0.904180
2013-12-31 12:00:00,0.064545,0.069458,0.279038,0.331098,0.107970,0.100140,0.080375,0.097383,0.766275,0.926045,...,0.026025,0.018351,0.939884,0.901816,0.853446,0.009371,0.006070,0.004290,0.905098,0.783141

**Exporting**

In [35]:
n.export_to_netcdf(fn)

WARNING:pypsa.networks:The network has not been optimized yet and no model is stored.
WARNING:pypsa.networks:The network has not been optimized yet and no objective value is stored.
WARNING:pypsa.networks:The network has not been optimized yet and no objective constant is stored.
WARNING:pypsa.networks:The network has not been optimized yet and no model is stored.
WARNING:pypsa.networks:The network has not been optimized yet and no objective value is stored.
WARNING:pypsa.networks:The network has not been optimized yet and no objective constant is stored.
INFO:pypsa.network.io:Exported network 'Unnamed Network' saved to 'resources/Nordics_test/networks/base_s_100__12h_2050.nc contains: links, stores, global_constraints, buses, sub_networks, storage_units, carriers, lines, generators, loads

<xarray.Dataset> Size: 25MB
Dimensions:                               (snapshots: 730, links_i: 7888,
                                           links_t_efficiency_i: 392,
                                           links_t_p_max_pu_i: 200,
                                           stores_i: 1388,
                                           stores_t_e_min_pu_i: 100,
                                           stores_t_e_max_pu_i: 192,
                                           ...
                                           storage_units_i: 72,
                                           storage_units_t_inflow_i: 47,
                                           carriers_i: 120, lines_i: 175,
                                           generators_i: 2955,
                                           generators_t_p_max_pu_i: 2287,
                                           loads_i: 1695, loads_t_p_set_i: 482)
Coordinates: (12/18)
  * snapshots                             (snapshots) int64 6kB 0 1 ... 728 729
  * links_i                               (links_i) object 63kB 'relation/132...
  * links_t_efficiency_i                  (links_t_efficiency_i) object 3kB '...
  * links_t_p_max_pu_i                    (links_t_p_max_pu_i) object 2kB 'DE...
  * stores_i                              (stores_i) object 11kB 'co2 atmosph...
  * stores_t_e_min_pu_i                   (stores_t_e_min_pu_i) object 800B '...
    ...                                    ...
  * carriers_i                            (carriers_i) object 960B 'AC' ... '...
  * lines_i                               (lines_i) object 1kB '0' '1' ... '99'
  * generators_i                          (generators_i) object 24kB 'GB2 1 n...
  * generators_t_p_max_pu_i               (generators_t_p_max_pu_i) object 18kB ...
  * loads_i                               (loads_i) object 14kB 'DE0 0' ... '...
  * loads_t_p_set_i                       (loads_t_p_set_i) object 4kB 'DE0 0...
Data variables: (12/127)
    snapshots_snapshot                    (snapshots) datetime64[ns] 6kB 2013...
    snapshots_objective                   (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_stores                      (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_generators                  (snapshots) float64 6kB 12.0 ... 12.0
    links_bus0                            (links_i) object 63kB 'NO1 0' ... '...
    links_bus1                            (links_i) object 63kB 'GB2 13' ... ...
    ...                                    ...
    generators_unit                       (generators_i) object 24kB '' ... ''
    generators_t_p_max_pu                 (snapshots, generators_t_p_max_pu_i) float64 13MB ...
    loads_bus                             (loads_i) object 14kB 'DE0 0 low vo...
    loads_carrier                         (loads_i) object 14kB 'electricity'...
    loads_p_set                           (loads_i) float64 14kB 0.0 0.0 ... 0.0
    loads_t_p_set                         (snapshots, loads_t_p_set_i) float64 3MB ...
Attributes:
    network_name:           Unnamed Network
    network_pypsa_version:  1.0.6
    network_srid:           4326
    crs:                    {"_crs": "GEOGCRS[\"WGS 84\",ENSEMBLE[\"World Geo...
    meta:                   {"version": "v2025.07.0", "tutorial": false, "log...