In [1]:
import pypsa
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import geopandas as gpd
from pypsa.plot import add_legend_lines, add_legend_patches, add_legend_semicircles
import numpy as np  
import pandas as pd
from pathlib import Path
import yaml
from matplotlib.colors import ListedColormap
import seaborn as sns

**Set Up**

In [2]:
#fn="/Users/rofrug/Library/CloudStorage/OneDrive-DanmarksTekniskeUniversitet/First Year PhD/Pypsa/results/ongrid_0.05costred_H2sto_batteries/DK_test/networks/base_s_2__12h_2050.nc"
fn = "results/DK_test/networks/base_s_2__12h_2050.nc"
config = yaml.safe_load(Path("config/config.italy.yaml").read_text())


n = pypsa.Network(fn)
stat=n.statistics()

WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.0.6 available! (Current: 0.35.2)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, global_constraints, links, loads, stores

In [ ]:
# fn_old = 'resources/DK_test/networks/base_s_2__12h_2050.nc'

# p = Path(fn_old)  
# try:
#     if p.exists():
#         p.unlink()
#         print(f"Deleted {p}")
#     else:
#         print(f"File not found: {p}")
# except Exception as e:
#     print(f"Failed to delete {p}: {e}")

**Print to Check**

In [3]:
n.buses.loc[n.buses.index.str.contains('co2'or 'CO2')]

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network,country,substation_lv,substation_off
Bus,,,,,,,,,,,,,,,,
co2 atmosphere,1.0,,-5.500000,46.000000,co2,t_co2,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 co2 stored,1.0,,9.648393,55.893047,co2 stored,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 co2 stored,1.0,,12.303316,55.515974,co2 stored,t_co2,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 co2 sequestered,1.0,,9.648393,55.893047,co2 sequestered,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 co2 sequestered,1.0,,12.303316,55.515974,co2 sequestered,t_co2,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN

In [4]:
n.links

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
relation/5487095-400-DC,DK0 0,DK1 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,False,171.53249
DK0 0 co2 sequestered,DK0 0 co2 stored,DK0 0 co2 sequestered,,co2 sequestered,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 co2 sequestered,DK1 0 co2 stored,DK1 0 co2 sequestered,,co2 sequestered,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 OCGT,DK0 0 gas,DK0 0,,OCGT,0.430000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 OCGT,DK1 0 gas,DK1 0,,OCGT,0.430000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DK1 0 urban decentral biomass boiler,DK1 0 solid biomass,DK1 0 urban decentral heat,,urban decentral biomass boiler,0.880000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral gas boiler,DK1 0 gas,DK1 0 urban decentral heat,,urban decentral gas boiler,0.990000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral resistive heater,DK1 0 low voltage,DK1 0 urban decentral heat,,urban decentral resistive heater,0.900000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral water tanks charger,DK1 0 urban decentral heat,DK1 0 urban decentral water tanks,,urban decentral water tanks charger,1.000000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,0.15,,False,0.00000
DK1 0 urban decentral water tanks discharger,DK1 0 urban decentral water tanks,DK1 0 urban decentral heat,,urban decentral water tanks discharger,1.000000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000

In [5]:
n.links.loc[n.links["bus1"].str.contains('co2 stored')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
CO2 pipeline DK0 0 -> DK1 0,DK0 0 co2 stored,DK1 0 co2 stored,,CO2 pipeline,1.0,True,0,50.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,171.53249

In [6]:
n.links.loc[(n.links["bus2"].str.contains("co2 stored", na=False) |
    n.links["bus1"].str.contains("co2 stored", na=False) |
    n.links["bus3"].str.contains("co2 stored", na=False) |
    n.links["bus4"].str.contains("co2 stored", na=False))]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 Sabatier,DK0 0 H2,DK0 0 gas,,Sabatier,0.800000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 Sabatier,DK1 0 H2,DK1 0 gas,,Sabatier,0.800000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 SMR CC,DK0 0 gas,DK0 0 H2,,SMR CC,0.690000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 SMR CC,DK1 0 gas,DK1 0 H2,,SMR CC,0.690000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central gas CHP CC,DK0 0 gas,DK0 0,,urban central gas CHP CC,0.411190,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central gas CHP CC,DK1 0 gas,DK1 0,,urban central gas CHP CC,0.411190,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central solid biomass CHP CC,DK0 0 solid biomass,DK0 0,,urban central solid biomass CHP CC,0.230363,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central solid biomass CHP CC,DK1 0 solid biomass,DK1 0,,urban central solid biomass CHP CC,0.230363,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 solid biomass for industry CC,DK0 0 solid biomass,DK0 0 solid biomass for industry,,solid biomass for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 solid biomass for industry CC,DK1 0 solid biomass,DK1 0 solid biomass for industry,,solid biomass for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 gas for industry CC,DK0 0 gas,DK0 0 gas for industry,,gas for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 gas for industry CC,DK1 0 gas,DK1 0 gas for industry,,gas for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 methanolisation,DK0 0 H2,EU methanol,,methanolisation,0.878700,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 methanolisation,DK1 0 H2,EU methanol,,methanolisation,0.878700,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 Fischer-Tropsch,DK0 0 H2,EU oil,,Fischer-Tropsch,0.799000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 Fischer-Tropsch,DK1 0 H2,EU oil,,Fischer-Tropsch,0.799000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 process emissions CC,DK0 0 process emissions,co2 atmosphere,,process emissions CC,0.050000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 process emissions CC,DK1 0 process emissions,co2 atmosphere,,process emissions CC,0.050000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central DAC,DK0 0,DK0 0 urban central heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central DAC,DK1 0,DK1 0 urban central heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
CO2 pipeline DK0 0 -> DK1 0,DK0 0 co2 stored,DK1 0 co2 stored,,CO2 pipeline,1.000000,True,0,50.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,171.53249
DK0 0 urban decentral DAC,DK0 0,DK0 0 urban decentral heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral DAC,DK1 0,DK1 0 urban decentral heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000

In [7]:
n.links.loc[(n.links["bus2"].str.contains("co2 stored", na=False) |
    n.links["bus1"].str.contains("co2 stored", na=False) |
    n.links["bus3"].str.contains("co2 stored", na=False) |
    n.links["bus4"].str.contains("co2 stored", na=False))]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 Sabatier,DK0 0 H2,DK0 0 gas,,Sabatier,0.800000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 Sabatier,DK1 0 H2,DK1 0 gas,,Sabatier,0.800000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 SMR CC,DK0 0 gas,DK0 0 H2,,SMR CC,0.690000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 SMR CC,DK1 0 gas,DK1 0 H2,,SMR CC,0.690000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central gas CHP CC,DK0 0 gas,DK0 0,,urban central gas CHP CC,0.411190,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central gas CHP CC,DK1 0 gas,DK1 0,,urban central gas CHP CC,0.411190,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central solid biomass CHP CC,DK0 0 solid biomass,DK0 0,,urban central solid biomass CHP CC,0.230363,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central solid biomass CHP CC,DK1 0 solid biomass,DK1 0,,urban central solid biomass CHP CC,0.230363,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 solid biomass for industry CC,DK0 0 solid biomass,DK0 0 solid biomass for industry,,solid biomass for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 solid biomass for industry CC,DK1 0 solid biomass,DK1 0 solid biomass for industry,,solid biomass for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 gas for industry CC,DK0 0 gas,DK0 0 gas for industry,,gas for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 gas for industry CC,DK1 0 gas,DK1 0 gas for industry,,gas for industry CC,0.900000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 methanolisation,DK0 0 H2,EU methanol,,methanolisation,0.878700,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 methanolisation,DK1 0 H2,EU methanol,,methanolisation,0.878700,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 Fischer-Tropsch,DK0 0 H2,EU oil,,Fischer-Tropsch,0.799000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 Fischer-Tropsch,DK1 0 H2,EU oil,,Fischer-Tropsch,0.799000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 process emissions CC,DK0 0 process emissions,co2 atmosphere,,process emissions CC,0.050000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 process emissions CC,DK1 0 process emissions,co2 atmosphere,,process emissions CC,0.050000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 urban central DAC,DK0 0,DK0 0 urban central heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban central DAC,DK1 0,DK1 0 urban central heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
CO2 pipeline DK0 0 -> DK1 0,DK0 0 co2 stored,DK1 0 co2 stored,,CO2 pipeline,1.000000,True,0,50.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,171.53249
DK0 0 urban decentral DAC,DK0 0,DK0 0 urban decentral heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral DAC,DK1 0,DK1 0 urban decentral heat,,DAC,-2.545455,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000

In [8]:
n.links.loc[(n.links["bus2"].str.contains("process emissions", na=False) |
    n.links["bus1"].str.contains("process emissions", na=False) |
    n.links["bus3"].str.contains("process emissions", na=False) |
    n.links["bus4"].str.contains("process emissions", na=False))]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 naphtha for industry,EU oil,DK0 0 naphtha for industry,,naphtha for industry,1.0,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 naphtha for industry,EU oil,DK1 0 naphtha for industry,,naphtha for industry,1.0,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0

In [17]:
n.links.loc[n.links['bus0'].str.contains('process emissions')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 process emissions,DK0 0 process emissions,co2 atmosphere,,process emissions,1.00,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 process emissions,DK1 0 process emissions,co2 atmosphere,,process emissions,1.00,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 0 process emissions CC,DK0 0 process emissions,co2 atmosphere,,process emissions CC,0.05,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 process emissions CC,DK1 0 process emissions,co2 atmosphere,,process emissions CC,0.05,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0

In [ ]:
n.links.loc[n.links['bus0'].str.contains('gas for industry')]

In [16]:
n.statistics.optimal_capacity()

component  carrier
Generator  Offshore Wind (AC)               2652.60077
           Offshore Wind (DC)                  0.01219
           Offshore Wind (Floating)            0.00412
           Onshore Wind                    14712.63237
           Solar                            6447.95668
                                              ...
Store      oil                                69.16862
           rural water tanks                   0.05761
           urban central water pits       122756.09133
           urban central water tanks      109420.21776
           urban decentral water tanks         0.05686
Length: 97, dtype: float64

In [19]:
n.loads.loc[(n.loads.index.str.contains('industry')|n.loads.index.str.contains('process'))]

,bus,carrier,type,p_set,q_set,sign,active
Load,,,,,,,
DK0 0 solid biomass for industry,DK0 0 solid biomass for industry,solid biomass for industry,,541.095890,0.0,-1.0,True
DK1 0 solid biomass for industry,DK1 0 solid biomass for industry,solid biomass for industry,,245.433790,0.0,-1.0,True
DK0 0 gas for industry,DK0 0 gas for industry,gas for industry,,155.251142,0.0,-1.0,True
DK1 0 gas for industry,DK1 0 gas for industry,gas for industry,,0.000000,0.0,-1.0,True
DK0 0 H2 for industry,DK0 0 H2,H2 for industry,,0.000000,0.0,-1.0,True
DK1 0 H2 for industry,DK1 0 H2,H2 for industry,,0.000000,0.0,-1.0,True
EU industry methanol,EU industry methanol,industry methanol,,0.000000,0.0,-1.0,True
DK0 0 naphtha for industry,DK0 0 naphtha for industry,naphtha for industry,,0.000000,0.0,-1.0,True
DK1 0 naphtha for industry,DK1 0 naphtha for industry,naphtha for industry,,0.000000,0.0,-1.0,True
DK0 0 low-temperature heat for industry,DK0 0 urban central heat,low-temperature heat for industry,,52.511416,0.0,-1.0,True
DK1 0 low-temperature heat for industry,DK1 0 urban central heat,low-temperature heat for industry,,15.981735,0.0,-1.0,True
DK0 0 industry electricity,DK0 0 low voltage,industry electricity,,1545.662100,0.0,-1.0,True
DK1 0 industry electricity,DK1 0 low voltage,industry electricity,,426.940639,0.0,-1.0,True
DK0 0 process emissions,DK0 0 process emissions,process emissions,,-172.374429,0.0,-1.0,True
DK1 0 process emissions,DK1 0 process emissions,process emissions,,-2.283105,0.0,-1.0,True

In [23]:
n.links.loc[n.links['bus1'].str.contains('gas')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
gas pipeline DK0 0 -> DK1 0,DK0 0 gas,DK1 0 gas,,gas pipeline,1.0,True,0,inf,1500.0,0.0,...,NaN,NaN,PLM_1339_Seg_0_Seg_0,,NaN,NaN,NaN,,False,383.277313
gas pipeline new DK0 0 <-> DK1 0,DK0 0 gas,DK1 0 gas,,gas pipeline new,1.0,True,0,50.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,257.298735
DK0 0 Sabatier,DK0 0 H2,DK0 0 gas,,Sabatier,0.8,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK1 0 Sabatier,DK1 0 H2,DK1 0 gas,,Sabatier,0.8,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK0 0 biogas to gas,DK0 0 biogas,DK0 0 gas,,biogas to gas,1.0,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK1 0 biogas to gas,DK1 0 biogas,DK1 0 gas,,biogas to gas,1.0,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK0 0 gas for industry,DK0 0 gas,DK0 0 gas for industry,,gas for industry,1.0,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK1 0 gas for industry,DK1 0 gas,DK1 0 gas for industry,,gas for industry,1.0,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK0 0 gas for industry CC,DK0 0 gas,DK0 0 gas for industry,,gas for industry CC,0.9,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
DK1 0 gas for industry CC,DK1 0 gas,DK1 0 gas for industry,,gas for industry CC,0.9,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.000000
gas pipeline DK0 0 -> DK1 0-reversed,DK1 0 gas,DK0 0 gas,,gas pipeline,1.0,True,0,inf,1500.0,0.0,...,NaN,NaN,PLM_1339_Seg_0_Seg_0,,NaN,NaN,NaN,,True,383.277313

In [ ]:
n.links.loc[n.links["carrier"].isin(['methanolisation', 'methanolisation cluster'])]

In [ ]:
n.links.loc[n.links["bus0"]=='EU methanol']

In [ ]:
n.links

In [ ]:
n.buses.loc[n.buses["carrier"].astype(str).str.contains('H2')]

In [ ]:
n.stores.loc[n.stores.index.astype(str).str.contains('cluster')]

In [ ]:
n.generators.loc[n.generators.index.astype(str).str.contains('cluster')].carrier.unique()

In [ ]:
n.generators

In [ ]:
nodes_with_clusters=n.buses.loc[n.buses.index.str.contains("cluster"), ["location"]].drop_duplicates().reset_index(drop=True)

**Mapping Technologies to Colors**

In [ ]:
label_to_colors = {'methanolisation cluster':'#a442f5',
                    'methanolisation':"#401662",
                    'solid biomass biomass-to-methanol':"#8442f5",
                    'H2 Electrolysis cluster':"#42f5d1",
                    'H2 Electrolysis':"#187878",
                    'solar rooftop':"#ffe204",                     
                    'solar':"#f47b0a",                                   
                    'solar-hsat':"#e32f0b",                                 
                    'solar-hsat cluster':"#870000",                         
                    'solar cluster':"#bff542",                              
                    'urban central solar thermal collector':"#3e1c04",      
                    'urban decentral solar thermal collector':'#87402e',    
                    'rural solar thermal collector':'#f5a4b4',
                    'Net Balance':"#FB0202",
                    'battery charger cluster':"#193ade",
                    'battery discharger cluster':"#0d0f5c",
                    'electricity cluster':"#BEBBFA",
                    'electricity cluster back':"#889899",
                    'H2 Store cluster charge':"#59786d",
                    'H2 Store cluster discharge':"#2A483B"

                   }

In [ ]:
n.links.p_nom_opt.loc[(n.links["bus1"] == "EU methanol") & (n.links.index.str.contains('IT'))].sort_values(ascending=False)/10**3

**Methanol**

In [ ]:
def plot_methanol_capacity_by_country(n):

    for country in config ["countries"]:

        methanol_capacities = n.links.p_nom_opt.loc[(n.links["bus1"] == "EU methanol") & (n.links.index.str.contains(country))].sort_values(ascending=False)/10**3

        tech = methanol_capacities.index.str.slice(start=6)

        methanol_capacities = (
            methanol_capacities
            .groupby(tech)
            .sum()
            .sort_values(ascending=False)
        )


        fig, ax = plt.subplots()

        methanol_capacities.plot.bar(ax=ax,
                                    ylabel="Capacity (GW)",
                                    title=f"Methanol production capacity by technology in {country}",
                                    color=[
                                        label_to_colors.get(label, "#cccccc")  # fallback color
                                        for label in methanol_capacities.index
                                    ])
        ax.set_xticklabels(ax.get_xticklabels(), rotation=60, ha="right")  

        plt.tight_layout()

plot_methanol_capacity_by_country(n)

In [ ]:
def plot_methanol_production_over_time(n):

    for country in config ["countries"]:


        methanol_technologies=n.links.loc[(n.links["bus1"] == "EU methanol") & (n.links.index.str.contains(country))].index

        methanol_production_t=(n.links_t["p1"][methanol_technologies]).abs().resample("72h").mean()/10**3

        tech = methanol_production_t.columns.str.slice(start=6)
        

        methanol_production_t = (
            methanol_production_t.groupby(tech, axis=1).sum()
        )

 
        fig,ax=plt.subplots(figsize=(10,5))
        methanol_production_t.plot.area(ylabel="Methanol production (GW)", 
                                        title=f"Methanol production over time by technology in {country}", 
                                        ax=ax,
                                        color=[
                                            label_to_colors.get(label, "#cccccc")  # fallback color
                                            for label in methanol_production_t.columns
                                        ]
                                        )
        
        leg = ax.legend(
            bbox_to_anchor=(1.05, 1),     
            frameon=True,                  
        )

        plt.tight_layout()

plot_methanol_production_over_time(n)

**Electrolyzers**

In [ ]:
def plot_electrolyzer_production_over_time(n):

    for country in config ["countries"]:


        electrolyzer_technologies=n.links.loc[(n.links["carrier"] == "H2 Electrolysis") & (n.links.index.str.contains(country))].index


        tech = electrolyzer_technologies.str.slice(start=6)
        

       

        electrolyzers_production_t=(n.links_t["p1"][electrolyzer_technologies].abs()).resample("72h").mean()/10**3

        electrolyzers_production_t= (
            electrolyzers_production_t.groupby(tech, axis=1).sum()
        )
        
        fig,ax=plt.subplots(figsize=(10,5))
        electrolyzers_production_t.plot.area(ylabel="Electrolyzer production (GW)", 
                                             title=f"Electrolyzer production over time by technology in {country}", 
                                             ax=ax,
                                             color=[
                                                 label_to_colors.get(label, "#cccccc")  # fallback color
                                                 for label in electrolyzers_production_t.columns
                                             ]
                                             )

        leg = ax.legend(
            bbox_to_anchor=(1.05, 1),     
            frameon=True,                  
        )

        plt.tight_layout()

plot_electrolyzer_production_over_time(n)

In [ ]:
n.links.loc[n.links.index.astype(str).str.contains('H2 turbine')]

In [ ]:
n.links.loc[n.links["bus1"].isin(['DK1 0 H2', 'DK0 0 H2'])]['p_nom_opt']

In [ ]:
n.links.p_nom_opt.loc[(n.links["carrier"] == "H2 Electrolysis") & (n.links.index.str.contains('IT'))].sort_values(ascending=False)/10**3

In [ ]:
def plot_electrolyzer_capacity(n):

    for country in config ["countries"]:

        electrolyzers_capacities = n.links.p_nom_opt.loc[(n.links["carrier"] == "H2 Electrolysis") & (n.links.index.str.contains(country))].sort_values(ascending=False)/10**3

        tech = electrolyzers_capacities.index.str.slice(start=6)
        

        electrolyzers_capacities = (
            electrolyzers_capacities.groupby(tech).sum().sort_values(ascending=False)
        )

        fig, ax = plt.subplots()
        electrolyzers_capacities.plot.bar(ax=ax,
                                    ylabel="Capacity (GW)",
                                    title=f"Electrolyzer capacity by technology in {country}",
                                    color=[
                                        label_to_colors.get(label, "#cccccc")  # fallback color
                                        for label in electrolyzers_capacities.index
                                    ])
        ax.set_xticklabels(ax.get_xticklabels(), rotation=60, ha="right")  

        plt.tight_layout()

plot_electrolyzer_capacity(n)

**Onshore Wind**

In [ ]:
def plot_renewable_capacity(n):

    for country in config ["countries"]:
        for renewable in n.generators.loc[n.generators.index.astype(str).str.contains('cluster')].carrier.unique():

            ren_capacity= n.generators.loc[ (n.generators.index.str.contains(renewable)) & (n.generators.index.str.contains(country)), 'p_nom_opt'].sort_values(ascending=False)/10**3


            idx = ren_capacity.index

            tech = idx.where(
                ~idx.str[6].str.isdigit(),
                idx.str.slice(start=8)
            ).where(
                idx.str[6].str.isdigit(),
                idx.str.slice(start=6)
            )


        

            ren_capacity = (
                ren_capacity.groupby(tech).sum().sort_values(ascending=False)
            )

            print (ren_capacity)


            fig,ax=plt.subplots()
            ren_capacity.plot.bar(ax=ax,
                                ylabel="Capacity (GW)",
                                title=f"{renewable} Capacity in {country}",
                                color=[
                                    label_to_colors.get(label, "#cccccc")  # fallback color
                                    for label in ren_capacity.index
                                ]
            )
            ax.set_xticklabels(ax.get_xticklabels(), rotation=60, ha="right")  
            plt.tight_layout()

plot_renewable_capacity(n)

**Relative Load Duration Curve**

In [ ]:
nodes_with_clusters["location"]

In [ ]:
config ["countries"]

In [ ]:
n.generators_t["p"].loc[:, n.generators_t["p"].columns.str.contains("cluster")] / 10**3

In [ ]:
def plot_load_duration_curve(tech_dictionary):

    for country in nodes_with_clusters["location"]:

        load_durations=pd.DataFrame()
        pnoms={}

        if not any(country in techname for _, techname in tech_dictionary):
            continue

        for techtype, techname in tech_dictionary:
            
            timeserie=[]
            pnom=0
        
            if techtype=="generator"  and (country in techname):
                print (techname)
                timeserie=(n.generators_t["p"].loc[:, techname]/10**3)
                pnom=n.generators.loc[techname, "p_nom_opt"]/10**3

                
            elif techtype=="link" and (country in techname):
                print (techname)

                timeserie=(n.links_t["p0"].loc[:, techname]/10**3).abs()
            

                pnom = (n.links.loc[techname,"p_nom_opt"]/10**3)

            techname = techname[8:] if techname[6].isdigit() else techname[6:]
 
            load_duration=timeserie
            load_duration=load_duration.sort_values(ascending=False).reset_index(drop=True)

            
            
            if not load_duration.le(0.1).all():
                load_durations[techname] = load_duration
                pnoms[techname] = pnom 



        load_durations.index=load_durations.index*(n.snapshot_weightings["objective"])# convert to hours


        fig,ax=plt.subplots(figsize=(10,5))
        load_durations.plot(ax=ax,
                        ylabel='Power [GW]',
                        xlabel= 'hours',
                        title=f"Load Duration Curves for renewable technologies in {country}",
                        color=[label_to_colors.get(label, "#cccccc")  # fallback color
                               for label in load_durations.columns]
                        )
    
        ax.set_xlim(left=0)
        ax.set_xlim(right=8760)
        ax.set_ylim(bottom=0)
        ax.set_ylim(top=max(pnoms.values())*1.1)

        tech_list = list(load_durations.columns)
        lines = ax.get_lines()

        for i, techname in enumerate(tech_list):
            color = lines[i].get_color()        # same color as load_duration curve
                                
            # horizontal line
            ax.hlines(y=pnoms[techname],
                    xmin=0,
                    xmax=8760,
                    colors=color,
                    linestyles="dashed")
            print (f"{techname} p_nom: {pnoms[techname]} GW")
            y_line = pnoms[techname]          
            y_offset = 0.03                 

            # label next to the line
            ax.text(
            8000,
            y_line - y_offset,
            "p_nom",
            color=color,
            va='top',
            fontsize=10,                 
            bbox=dict(
                boxstyle="round,pad=0.3",
                facecolor="white",
                edgecolor=color,
                alpha=0.8
            )
        )

        
        leg = ax.legend(
            loc='upper left',           
            bbox_to_anchor=(1.02,1),
            frameon=True,
        )

        
        fig.subplots_adjust(bottom=0.25)   
        

        
        plt.show()

    return load_durations, pnoms

cluster_components = (
    [("link", idx) for idx in n.links.index if ("cluster" in idx and "electricity" not in idx and "charger" not in idx and n.links.loc[idx, "p_nom_opt"] > 0.01)]
    + [("generator", idx) for idx in n.generators.index if ("cluster" in idx and n.generators.loc[idx, "p_nom_opt"] > 0.01)]
)

load_durations, pnoms = plot_load_duration_curve(cluster_components)

In [ ]:
n.links

**Batteries and H2 Storage**

In [ ]:
def plot_electricity_balance_by_cluster(n):
    el_balance_cluster={}
    el_net={}


    for node in nodes_with_clusters["location"]:

        el_balance_cluster[node]= pd.DataFrame()
        el_net[node]= pd.DataFrame()

        for generators in n.generators.loc[n.generators.index.str.contains('cluster')].index:
            

            if node in generators:
                clean_name = generators[8:] if generators[6].isdigit() else generators[6:]
                print (clean_name)
                el_balance_cluster[node][clean_name]=( n.generators_t["p"].loc[:, generators]/10**3).resample("72h").mean()
                

        for links in n.links.loc[n.links.index.str.contains('cluster')].index:

            if node in links:
                clean_name = links[8:] if links[6].isdigit() else links[6:]
                print (clean_name)

                if "Electrolysis" in links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p0"].loc[:, links]/-10**3).resample("72h").mean()
                elif "methanolisation" in links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p2"].loc[:, links]/-10**3).resample("72h").mean()
                elif "battery charger" in links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p1"].loc[:, links]/10**3).resample("72h").mean()
                elif "battery discharger" in links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p1"].loc[:, links]/-10**3).resample("72h").mean()
                elif f"{node} electricity cluster"==links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p0"].loc[:, links]/-10**3).resample("72h").mean()     
                elif f"{node} electricity cluster back"==links:
                    el_balance_cluster[node][clean_name]= (n.links_t["p0"].loc[:, links]/10**3).resample("72h").mean()  
                

        


        el_net[node]["el_net"]=el_balance_cluster[node].sum(axis=1)
        el_net[node].index=el_balance_cluster[node].index



        figure,ax=plt.subplots(figsize=(10,6))
        ax.plot(el_balance_cluster[node].index,el_net[node]["el_net"],
                '--', 
                color=label_to_colors['Net Balance'], 
                linewidth=2, 
                zorder=10, 
                label='Net Balance')
        el_balance_cluster[node].plot.area(ax=ax,
                                    color=[
                                        label_to_colors.get(label, "#cccccc")  # fallback color
                                        for label in el_balance_cluster[node].columns
                                    ]
                                    )


        # Layout / labels
        ax.set_xlim("2013-01","2014-01")


        ax.set_ylabel("Power [GW]")
        ax.set_title(f"Electricity Production and Consumption in the Cluster of {node}")
        ax.legend(bbox_to_anchor=(1.05,1), frameon=True)

    return el_balance_cluster

el_balance_cluster=plot_electricity_balance_by_cluster(n)

In [ ]:
el_balance_cluster["DK1 0"].columns

In [ ]:
def plot_hydrogen_balance_by_cluster(n):    
    h2_balance_cluster={}
    h2_net={}


    for node in nodes_with_clusters["location"]:

        h2_balance_cluster[node]= pd.DataFrame()
        h2_net[node]= pd.DataFrame()

        for links in n.links.loc[n.links.index.str.contains('cluster')].index:
            clean_name = links[8:] if links[6].isdigit() else links[6:]

            if node in links:
                if "Electrolysis" in links:
                    h2_balance_cluster[node][clean_name]= (n.links_t["p1"].loc[:, links]/-10**3).resample("72h").mean()
                elif "methanolisation" in links:
                    h2_balance_cluster[node][clean_name]= (n.links_t["p0"].loc[:, links]/-10**3).resample("72h").mean()
        
        for store in n.stores.loc[n.stores.index.str.contains(f"{node} H2 Store cluster")].index:
            clean_name = store[8:] if store[6].isdigit() else store[6:]
            h2_balance_cluster[node][f"{clean_name} charge"]= (((n.stores_t.p.loc[:, store]/10**3).resample("72h").mean()).clip(upper=0))
            h2_balance_cluster[node][f"{clean_name} discharge"]= (((n.stores_t.p.loc[:, store]/10**3).resample("72h").mean()).clip(lower=0))

        h2_net[node]["h2_net"]=h2_balance_cluster[node].sum(axis=1)
        h2_net[node].index=h2_balance_cluster[node].index   


        figure,ax=plt.subplots(figsize=(10,6))
        ax.plot(h2_balance_cluster[node].index, h2_net[node]["h2_net"], '--', color=label_to_colors["Net Balance"], linewidth=2, zorder=10, label='Net Balance')
        h2_balance_cluster[node].plot.area(ax=ax, color=[label_to_colors.get(label, "#cccccc")  # fallback color
                               for label in h2_balance_cluster[node].columns])

        # Layout / labels
        ax.set_xlim("2013-01","2014-01")


        ax.set_ylabel("Power [GW]")
        ax.set_title(f"Hydrogen Production and Consumption in the Cluster of {node}")
        ax.legend(bbox_to_anchor=(1.05,1), frameon=True)

plot_hydrogen_balance_by_cluster(n)

In [ ]:
def calculate_storage_equivalent_hours(n):    
    for node in nodes_with_clusters["location"]:

        H2_sto_equivalent_hours_methanolization=n.stores.loc[f"{node} H2 Store cluster","e_nom_opt"]/n.links.loc[f"{node} methanolisation cluster","p_nom_opt"]
        print(f"Equivalent hours of H2 storage in {node} to run methanolization at full capacity: {H2_sto_equivalent_hours_methanolization} hours")

        Battery_sto_equivalet_hours_electrolyzer=n.stores.loc[f"{node} battery cluster","e_nom_opt"]/n.links.loc[f"{node} H2 Electrolysis cluster","p_nom_opt"]
        print(f"Equivalent hours of Battery storage in {node} to run electrolyzer at full capacity: {Battery_sto_equivalet_hours_electrolyzer} hours")

        Batter_sto_equivalent_hours_methanolization=n.stores.loc[f"{node} battery cluster","e_nom_opt"]/abs(n.links.loc[f"{node} methanolisation cluster","p_nom_opt"]*n.links.loc[f"{node} methanolisation cluster","efficiency2"])
        print(f"Equivalent hours of Battery storage in {node} to run methanolization at full capacity: {Batter_sto_equivalent_hours_methanolization} hours")

calculate_storage_equivalent_hours(n)

**Prices Comparison**

In [ ]:
el_price={}
H2_price={}
methanol_price={}

In [ ]:
def plot_energy_prices_by_cluster(n, carrier):  
    for node in nodes_with_clusters["location"]:

        if carrier == 'electricity':

            node = node.removesuffix(" cluster")
            el_price[node]=n.buses_t["marginal_price"].loc[:,node]
            fig, ax=plt.subplots(figsize=(10,5))
            el_price[node].resample("24h").mean().plot(ax=ax, ylabel="Electricity Price [€/MWh]", title=f"Daily Average Electricity Price in {node}")

        elif carrier == 'H2':

            node = node.removesuffix(" cluster")
            H2_price[node]=n.buses_t["marginal_price"].loc[:,f"{node} H2"]
            fig, ax=plt.subplots(figsize=(10,5))
            H2_price[node].resample("24h").mean().plot(ax=ax, ylabel="Hydrogen Price [€/MWh]", title=f"Daily Average Hydrogen Price in {node}")
        
    if carrier == 'methanol':

        methanol_price=n.buses_t["marginal_price"].loc[:,"EU methanol"]
        fig, ax=plt.subplots(figsize=(10,5))
        methanol_price.resample("24h").mean().plot(ax=ax, ylabel="Methanol Price [€/MWh]", title="Daily Average Methanol Price in EU")
        # horizontal line
        y_line = 126.58
        ax.axhline(y=y_line, linestyle="dashed", linewidth=1)

        # dynamic x-position for label (near right edge)
        xmax = ax.get_xlim()[1]
        x_label_pos = xmax*1.0003   
        ax.text(
            x_label_pos,
            y_line,
            "2025 fossil methanol price",
            va='center',
            fontsize=10,
            color=ax.lines[0].get_color(),
            bbox=dict(
                boxstyle="round,pad=0.3",
                facecolor="white",
                edgecolor=ax.lines[0].get_color(),
                alpha=0.8
            )
        )


        # y-limits
        ax.set_ylim(0, 200)
        ax.set_ylabel("Price [€/MWh]")

plot_energy_prices_by_cluster(n, 'electricity')
plot_energy_prices_by_cluster(n, 'H2')
plot_energy_prices_by_cluster(n, 'methanol')

In [ ]:
n.buses_t["marginal_price"].loc[:,"DK1 0 co2 stored"].mean()

In [ ]:
n.links.loc

In [ ]:
n.global_const

In [ ]:
n.buses

**Import and Export**

In [ ]:
n.links_t.p1

In [ ]:
def plot_electricity_import_export_by_cluster(n):

    el_export={}
    el_import={}

    for node in nodes_with_clusters["location"]:
        
        cluster=node + " electricity cluster"
        if cluster in n.links_t["p1"].columns:

            el_export[cluster]= (n.links_t["p1"].loc[:, cluster]/10**3).resample("72h").mean()
            print(f"Electricity export in {node} cluster sum: {el_export[cluster].sum()} GWh")

            fig,ax =plt.subplots()
            el_export[cluster].plot(ax=ax, ylabel="Electricity Export (GW)", title=f"Electricity Export over time in {cluster}")

            cluster=node + " electricity cluster back"
            el_import[cluster] = (n.links_t["p0"].loc[:, cluster]/10**3).resample("72h").mean()
            print(f"Electricity import in {node} cluster sum: {el_import[cluster].sum()} GWh")

            fig,ax =plt.subplots()
            el_import[cluster].plot(ax=ax, ylabel="Electricity Import (GW)", title=f"Electricity Import over time in {cluster}")


plot_electricity_import_export_by_cluster(n)

In [ ]:
n.statistics.energy_balance()